- name: Interacts with webservices using password
  ansible.builtin.uri:
    url: "http://platform-auth:8000/api/{{ ITA_DFLT_Organization_ID }}/platform/workspaces"
    force_basic_auth: true
    user: "{{ ITA_DFLT_Basic_Username }}"
    password: "{{ ITA_DFLT_Basic_Password }}"
    status_code: 200
    method: GET
  register: ITA_DFLT_API_Response
