# This Playbook file installs package names specified by "ITA_DFLT_Target_Package_Name".
# Nothing will happen if the specified package names are already installed.
# "ITA_DFLT_Target_Package_Name" can specify multiple package names (list type).
- name: Ensure ITA variable is recognized
  ansible.builtin.set_fact:
    ITA_DFLT_Target_Package_Name: "{{ ITA_DFLT_Target_Package_Name }}"
  when: ITA_DFLT_Target_Package_Name is defined

- name: Manages Python library dependencies
  ansible.builtin.pip:
    name: "{{ item }}"
  loop: >-
    {{
      ITA_DFLT_Target_Package_Name if ITA_DFLT_Target_Package_Name is sequence and ITA_DFLT_Target_Package_Name is not string else [ITA_DFLT_Target_Package_Name]
    }}
