- name: Ensure ITA_DFLT_Users is recognized
  ansible.builtin.set_fact:
    ITA_DFLT_Users: "{{ ITA_DFLT_Users }}"
  when: ITA_DFLT_Users is defined

- name: Ensure ITA_DFLT_Authorized_Keys is recognized
  ansible.builtin.set_fact:
    ITA_DFLT_Authorized_Keys: "{{ ITA_DFLT_Authorized_Keys }}"
  when: ITA_DFLT_Authorized_Keys is defined

- name: Remove authorized key
  ansible.posix.authorized_key:
    user: "{{ item[0] }}"
    key: "{{ item[1] }}"
    state: absent
  loop: >-
    {{
      (ITA_DFLT_Users if ITA_DFLT_Users is sequence and ITA_DFLT_Users is not string else [ITA_DFLT_Users])
      | ansible.builtin.zip_longest(
          ITA_DFLT_Authorized_Keys if ITA_DFLT_Authorized_Keys is sequence and ITA_DFLT_Authorized_Keys is not string else [ITA_DFLT_Authorized_Keys]
        )
      | list
    }}
