- name: Ensure ITA variable is recognized
  ansible.builtin.set_fact:
    ITA_DFLT_Target_Path: "{{ ITA_DFLT_Target_Path }}"
  when: ITA_DFLT_Target_Path is defined

- name: Return a list of files based on specific criteria
  ansible.builtin.find:
    age: "{{ ITA_DFLT_Age | default('0s') }}"
    file_type: any
    paths: "{{ item }}"
    patterns:
      - "{{ ITA_DFLT_Name_Pattern | default('.*') }}"
    recurse: "{{ ITA_DFLT_Recurse | default(true) }}"
    use_regex: true
  loop: >-
    {{
      ITA_DFLT_Target_Path if ITA_DFLT_Target_Path is sequence and ITA_DFLT_Target_Path is not string else [ITA_DFLT_Target_Path]
    }}
  register: output

- name: Print statements during execution
  ansible.builtin.debug:
    var: output
    verbosity: 0
