- name: Ensure ITA_DFLT_Win_Template_Src_File_Name is recognized
  ansible.builtin.set_fact:
    ITA_DFLT_Win_Template_Src_File_Name: "{{ ITA_DFLT_Win_Template_Src_File_Name }}"
  when: ITA_DFLT_Win_Template_Src_File_Name is defined

- name: Ensure ITA_DFLT_Win_Template_Dest_Directory is recognized
  ansible.builtin.set_fact:
    ITA_DFLT_Win_Template_Dest_Directory: "{{ ITA_DFLT_Win_Template_Dest_Directory }}"
  when: ITA_DFLT_Win_Template_Dest_Directory is defined

- name: Fetch files from remote nodes
  ansible.windows.win_template:
    src: "{{ item[0] }}"
    dest: "{{ item[1] }}\\{{ item[0] | basename }}"
  loop: >-
    {{
      (ITA_DFLT_Win_Template_Src_File_Name if ITA_DFLT_Win_Template_Src_File_Name is sequence and ITA_DFLT_Win_Template_Src_File_Name is not string else [ITA_DFLT_Win_Template_Src_File_Name])
      | ansible.builtin.zip_longest(
          ITA_DFLT_Win_Template_Dest_Directory if ITA_DFLT_Win_Template_Dest_Directory is sequence and ITA_DFLT_Win_Template_Dest_Directory is not string else [ITA_DFLT_Win_Template_Dest_Directory]
        )
      | list
    }}