openapi: 3.0.3
info:
  description: ITAv2.0 admin用API
  version: 1.0.0
  title: ITA Version2.0 admin API
tags:

  - name: Organization Create
    description: Organization作成
  - name: Workspace Create
    description: Workspace作成
  - name: Initial Settings Ansible
    description: 初期データ設定(Ansible)
paths:
  /api/organizations/{organization_id}/ita/:
    post:
      tags:
        - Organization Create
      description: Organizationを作成する
      operationId: organizationCreate
      parameters:
        - name: organization_id
          in: path
          description: OrganizationID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: 000-00000
                  message:
                    type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
    delete:
      tags:
        - Organization Create
      description: Organizationを削除する
      operationId: organizationDelete
      parameters:
        - name: organization_id
          in: path
          description: OrganizationID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: 000-00000
                  message:
                    type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'

  /api/{organization_id}/workspaces/{workspace_id}/ita/:
    post:
      tags:
        - Workspace Create
      description: Workspaceを作成する
      operationId: workspaceCreate
      parameters:
        - name: organization_id
          in: path
          description: organizationID
          required: true
          schema:
            type: string
        - name: workspace_id
          in: path
          description: WorkspaceID
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              description: ロールID情報
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: 000-00000
                  message:
                    type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
    delete:
      tags:
        - Workspace Create
      description: Workspaceを削除する
      operationId: workspaceDelete
      parameters:
        - name: organization_id
          in: path
          description: organizationID
          required: true
          schema:
            type: string
        - name: workspace_id
          in: path
          description: WorkspaceID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: 000-00000
                  message:
                    type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'

  /api/ita/initial-settings/ansible/:
    get:
      tags:
        - Initial Settings Ansible
      description: Ansibleの初期データを取得する
      operationId: getInitialSetting
      parameters: []
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: 000-00000
                  data:
                    type: object
                    properties:
                      input_limit_setting:
                        type: boolean
                      execution_engine_list:
                        type: array
                        items:
                          type: "string"
                      initial_data:
                        type: object
                        properties:
                          ansible_automation_controller_host_list:
                            items:
                              properties:
                                file:
                                  type: object
                                  properties:
                                    ssh_private_key_file:
                                      type: string
                                      nullable: true
                                parameter:
                                  type: object
                                  properties:
                                    host:
                                      type: string
                                      nullable: true
                                    authentication_method:
                                      type: string
                                      nullable: true
                                    user:
                                      type: string
                                      nullable: true
                                    password:
                                      type: string
                                      nullable: true
                                    ssh_private_key_file:
                                      type: string
                                      nullable: true
                                    passphrase:
                                      type: string
                                      nullable: true
                                    isolated_tower:
                                      type: string
                                      nullable: true
                                    remarks:
                                      type: string
                                      nullable: true
                          interface_info_ansible:
                            type: object
                            properties:
                              parameter:
                                type: object
                                properties:
                                  execution_engine:
                                    type: string
                                    nullable: true
                                  representative_server:
                                    type: string
                                    nullable: true
                                  ansible_automation_controller_protocol:
                                    type: string
                                    nullable: true
                                  ansible_automation_controller_port:
                                    type: string
                                    nullable: true
                                  organization_name:
                                    type: string
                                    nullable: true
                                  authentication_token:
                                    type: string
                                    nullable: true
                                  delete_runtime_data:
                                    type: string
                                    nullable: true
                                  proxy_address:
                                    type: string
                                    nullable: true
                                  proxy_port:
                                    type: string
                                    nullable: true
                  message:
                    type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
    post:
      tags:
        - Initial Settings Ansible
      description: Ansibleの初期データを登録・更新する
      operationId: postInitialSetting
      parameters: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                input_limit_setting:
                  type: boolean
                execution_engine_list:
                  type: array
                  items:
                    type: "string"
                initial_data:
                  type: object
                  properties:
                    ansible_automation_controller_host_list:
                      items:
                        properties:
                          file:
                            type: object
                            properties:
                              ssh_private_key_file:
                                type: string
                                nullable: true
                          parameter:
                            type: object
                            properties:
                              host:
                                type: string
                                nullable: true
                              user:
                                type: string
                                nullable: true
                              password:
                                type: string
                                nullable: true
                              ssh_private_key_file:
                                type: string
                                nullable: true
                              passphrase:
                                type: string
                                nullable: true
                              isolated_tower:
                                type: string
                                nullable: true
                              remarks:
                                type: string
                                nullable: true
                    interface_info_ansible:
                      type: object
                      properties:
                        parameter:
                          type: object
                          properties:
                            execution_engine:
                              type: string
                              nullable: true
                            ansible_automation_controller_protocol:
                              type: string
                              nullable: true
                            ansible_automation_controller_port:
                              type: string
                              nullable: true
                            organization_name:
                              type: string
                              nullable: true
                            authentication_token:
                              type: string
                              nullable: true
                            delete_runtime_data:
                              type: string
                              nullable: true
                            proxy_address:
                              type: string
                              nullable: true
                            proxy_port:
                              type: string
                              nullable: true
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: 000-00000
                  message:
                    type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'

components:
  schemas:
    ERROR_TEMPLATE:
      type: object
      properties:
        result:
          type: string
          example: 001-00002
        message:
          type: string
