openapi: 3.0.3
info:
  title: Exastro ITA Ansible Execution Receiver API
  description: Exastro ITA Ansible Execution Receiver API
  version: "2.5"

servers:
  - url: "https://{host}"
    description: API endpoint
    variables:
      host:
        default: localhost
  - url: "http://{host}"
    description: API endpoint
    variables:
      host:
        default: localhost
  - url: "{protocol}://{host}:{port}"
    description: API endpoint (Development)
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
      host:
        default: localhost
      port:
        default: '30080'

tags:
  - name: Ansible Execution
    description: Ansibleの情報を取得

paths:
  /api/{organization_id}/workspaces/{workspace_id}/ansible_execution_agent/instance/unexecuted:
    get:
      tags:
        - Ansible Execution
      description: 未実行インスタンス取得
      operationId: getUnexecutedInstance
      x-openapi-router-controller: controllers.ansible_receiver_controller
      parameters:
        - name: organization_id
          in: path
          description: OrganizationID
          required: true
          schema:
            type: string
        - name: workspace_id
          in: path
          description: WorkspaceID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: 000-00000
                  data:
                    type: object
                    items: {}
                    example: {execution_no: {"driver_id": "string", "build_type": "string", "user_name": "string", "password": "string", "base_image": "string", "attach_repository": "string", "anstwr_del_runtime_data": boolean}}
                  message:
                    type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'

  /api/{organization_id}/workspaces/{workspace_id}/ansible_execution_agent/{execution_no}/notification/status:
    get:
      tags:
        - Ansible Execution
      description: 作業状態通知
      operationId: executionStatusNotification
      x-openapi-router-controller: controllers.ansible_receiver_controller
      parameters:
        - name: organization_id
          in: path
          description: OrganizationID
          required: true
          schema:
            type: string
        - name: workspace_id
          in: path
          description: WorkspaceID
          required: true
          schema:
            type: string
        - name: execution_no
          in: path
          description: 作業番号
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: 000-00000
                  data:
                    items: {}
                    example: {"scram_status": boolean}
                  message:
                    type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'

  /api/{organization_id}/workspaces/{workspace_id}/ansible_execution_agent/populated_data:
    get:
      tags:
        - Ansible Execution
      description: 投入データ取得
      operationId: getPopulatedData
      x-openapi-router-controller: controllers.ansible_receiver_controller
      parameters:
        - name: organization_id
          in: path
          description: OrganizationID
          required: true
          schema:
            type: string
        - name: workspace_id
          in: path
          description: WorkspaceID
          required: true
          schema:
            type: string
        - name: driver_id
          in: query
          description: ドライバーID
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: 000-00000
                  data:
                    type: object
                    items: {}
                    example: {execution_no: {"in_out_data": "string", "conductor_data": "string"}}
                  message:
                    type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'

  /api/{organization_id}/workspaces/{workspace_id}/ansible_execution_agent/{execution_no}/result_data:
    post:
      tags:
        - Ansible Execution
      description: 結果データ受け取り・更新
      operationId: updateResultData
      x-openapi-router-controller: controllers.ansible_receiver_controller
      parameters:
        - name: organization_id
          in: path
          description: OrganizationID
          required: true
          schema:
            type: string
        - name: workspace_id
          in: path
          description: WorkspaceID
          required: true
          schema:
            type: string
        - name: execution_no
          in: path
          description: 作業番号
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              description: ドライバーID、ステータス、各種tarファイルを指定
              properties:
                driver_id:
                  type: string
                status:
                  type: string
                file:
                  type: object
                  properties:
                    file_name:
                      type: string
                      example: base64 encode file
          multipart/form-data:
            schema:
              description: ドライバーID、ステータス、各種tarファイルを指定
              type: object
              properties:
                driver_id:
                  type: string
                status:
                  type: string
                file:
                  type: object
                  properties:
                    file_name:
                      type: string
                      example: base64 encode file
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: 000-00000
                  data:
                    type: boolean
                  message:
                    type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'

  /api/{organization_id}/workspaces/{workspace_id}/ansible_execution_agent/version:
    post:
      tags:
        - Ansible Execution
      description: バージョン通知
      operationId: agentVersion
      x-openapi-router-controller: controllers.ansible_receiver_controller
      parameters:
        - name: organization_id
          in: path
          description: OrganizationID
          required: true
          schema:
            type: string
        - name: workspace_id
          in: path
          description: WorkspaceID
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              description: エージェントID、エージェント名、バージョン情報を指定
              properties:
                agent_id:
                  type: string
                agent_name:
                  type: string
                version:
                  type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: 000-00000
                  data:
                    items: {}
                    example: {"version_diff": boolean}
                  message:
                    type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'

  /api/{organization_id}/workspaces/{workspace_id}/ansible_execution_agent/notification/execution:
    post:
      tags:
        - Ansible Execution
      description: 作業中通知
      operationId: executionNotification
      x-openapi-router-controller: controllers.ansible_receiver_controller
      parameters:
        - name: organization_id
          in: path
          description: OrganizationID
          required: true
          schema:
            type: string
        - name: workspace_id
          in: path
          description: WorkspaceID
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              description: 作業実行中の作業番号を指定する
              properties:
                legacy:
                  type: array
                  description: 作業番号を指定する
                  items:
                    type: string
                pioneer:
                  type: array
                  description: 作業番号を指定する
                  items:
                    type: string
                legacy_role:
                  type: array
                  description: 作業番号を指定する
                  items:
                    type: string
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: 000-00000
                  data:
                    type: boolean
                  message:
                    type: string
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'

components:
  schemas:
    ERROR_TEMPLATE:
      type: object
      properties:
        result:
          type: string
          example: 001-002
        message:
          type: string

  securitySchemes:
    BearerAuth:
      description: Credentials or access token for API
      type: http
      scheme: bearer
      bearerFormat: JWT
    BasicAuth:
      description: Value converted from ID/Password in base64
      type: http
      scheme: basic
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
security:
- BearerAuth: []
- BasicAuth: []
