ALTER TABLE `T_COMN_WORKSPACE_DB_INFO`
 ADD `MONGO_CONNECTION_STRING` VARCHAR(255) AFTER `DB_PASSWORD`,
 ADD `MONGO_DATABASE` VARCHAR(255) AFTER `MONGO_CONNECTION_STRING`,
 ADD `MONGO_USER` VARCHAR(255) AFTER `MONGO_DATABASE`,
 ADD `MONGO_PASSWORD` VARCHAR(255) AFTER `MONGO_USER`;
