ALTER TABLE T_COMN_WORKSPACE_DB_INFO ADD COLUMN MONGO_HOST VARCHAR(255) AFTER DB_PASSWORD;
ALTER TABLE T_COMN_WORKSPACE_DB_INFO ADD COLUMN MONGO_PORT INT AFTER MONGO_HOST;
ALTER TABLE T_COMN_WORKSPACE_DB_INFO ADD COLUMN MONGO_DATABASE VARCHAR(255) AFTER MONGO_PORT;
ALTER TABLE T_COMN_WORKSPACE_DB_INFO ADD COLUMN MONGO_USER VARCHAR(255) AFTER MONGO_DATABASE;
ALTER TABLE T_COMN_WORKSPACE_DB_INFO ADD COLUMN MONGO_PASSWORD VARCHAR(255) AFTER MONGO_USER;
