INSERT INTO T_EVRE_LABEL_KEY_INPUT (ITA_LABEL_KEY_ID,ITA_LABEL_KEY,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('uuid D','db-down',NULL,'0',_____DATE_____,1);
INSERT INTO T_EVRE_LABEL_KEY_INPUT_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,ITA_LABEL_KEY_ID,ITA_LABEL_KEY,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(1,_____DATE_____,'INSERT','uuid D','db-down',NULL,'0',_____DATE_____,1);
INSERT INTO T_EVRE_LABEL_KEY_INPUT (ITA_LABEL_KEY_ID,ITA_LABEL_KEY,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('uuid E','web-down',NULL,'0',_____DATE_____,1);
INSERT INTO T_EVRE_LABEL_KEY_INPUT_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,ITA_LABEL_KEY_ID,ITA_LABEL_KEY,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2,_____DATE_____,'INSERT','uuid E','web-down',NULL,'0',_____DATE_____,1);
INSERT INTO T_EVRE_LABEL_KEY_INPUT (ITA_LABEL_KEY_ID,ITA_LABEL_KEY,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('uuid F','hostname',NULL,'0',_____DATE_____,1);
INSERT INTO T_EVRE_LABEL_KEY_INPUT_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,ITA_LABEL_KEY_ID,ITA_LABEL_KEY,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(3,_____DATE_____,'INSERT','uuid F','hostname',NULL,'0',_____DATE_____,1);

INSERT INTO T_EVRE_CONNECTION_METHOD (AUTHENTICATION_METHOD_ID,AUTH_METHOD_NAME_EN,AUTH_METHOD_NAME_JA,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('1','Bearer Authentication','Bearer認証',NULL,'0',_____DATE_____,1);

INSERT INTO T_EVRE_CONNECTION_METHOD (AUTHENTICATION_METHOD_ID,AUTH_METHOD_NAME_EN,AUTH_METHOD_NAME_JA,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2','password authentication','パスワード認証',NULL,'0',_____DATE_____,1);

INSERT INTO T_EVRE_CONNECTION_METHOD (AUTHENTICATION_METHOD_ID,AUTH_METHOD_NAME_EN,AUTH_METHOD_NAME_JA,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('3','Authentication SharedKeyLite','SharedKeyLite認証',NULL,'0',_____DATE_____,1);

INSERT INTO T_EVRE_CONNECTION_METHOD (AUTHENTICATION_METHOD_ID,AUTH_METHOD_NAME_EN,AUTH_METHOD_NAME_JA,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('4','IMAP password authentication','IMAP パスワード認証',NULL,'0',_____DATE_____,1);

INSERT INTO T_EVRE_CONNECTION_METHOD (AUTHENTICATION_METHOD_ID,AUTH_METHOD_NAME_EN,AUTH_METHOD_NAME_JA,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('5','Zabbix Authentication','Zabbix認証',NULL,'0',_____DATE_____,1);


INSERT INTO T_EVRE_COMPARISON_METHOD (COMPARE_METHOD_ID,METHOD_NAME_EN,METHOD_NAME_JA,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('1','equals','等しい',NULL,'0',_____DATE_____,1);

INSERT INTO T_EVRE_COMPARISON_METHOD (COMPARE_METHOD_ID,METHOD_NAME_EN,METHOD_NAME_JA,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2','not equal','等しくない',NULL,'0',_____DATE_____,1);

INSERT INTO T_EVRE_COMPARISON_METHOD (COMPARE_METHOD_ID,METHOD_NAME_EN,METHOD_NAME_JA,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('3','less than','より小さい',NULL,'0',_____DATE_____,1);

INSERT INTO T_EVRE_COMPARISON_METHOD (COMPARE_METHOD_ID,METHOD_NAME_EN,METHOD_NAME_JA,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('4','less than or equal to','以下',NULL,'0',_____DATE_____,1);

INSERT INTO T_EVRE_COMPARISON_METHOD (COMPARE_METHOD_ID,METHOD_NAME_EN,METHOD_NAME_JA,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('5','greater than','より大きい',NULL,'0',_____DATE_____,1);

INSERT INTO T_EVRE_COMPARISON_METHOD (COMPARE_METHOD_ID,METHOD_NAME_EN,METHOD_NAME_JA,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('6','greater than or equal to','以上',NULL,'0',_____DATE_____,1);

INSERT INTO T_EVRE_COMPARISON_METHOD (COMPARE_METHOD_ID,METHOD_NAME_EN,METHOD_NAME_JA,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('7','regular expression','正規表現',NULL,'0',_____DATE_____,1);


INSERT INTO T_EVRE_TARGET_DATA_TYPE (TARGET_TYPE_ID,TARGET_TYPE_EN,TARGET_TYPE_JA,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('1','string','文字列',NULL,'0',_____DATE_____,1);

INSERT INTO T_EVRE_TARGET_DATA_TYPE (TARGET_TYPE_ID,TARGET_TYPE_EN,TARGET_TYPE_JA,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2','integer','整数',NULL,'0',_____DATE_____,1);

INSERT INTO T_EVRE_TARGET_DATA_TYPE (TARGET_TYPE_ID,TARGET_TYPE_EN,TARGET_TYPE_JA,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('3','float','小数',NULL,'0',_____DATE_____,1);

INSERT INTO T_EVRE_TARGET_DATA_TYPE (TARGET_TYPE_ID,TARGET_TYPE_EN,TARGET_TYPE_JA,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('4','bool','真偽値',NULL,'0',_____DATE_____,1);

INSERT INTO T_EVRE_TARGET_DATA_TYPE (TARGET_TYPE_ID,TARGET_TYPE_EN,TARGET_TYPE_JA,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('5','null','何もない',NULL,'0',_____DATE_____,1);


INSERT INTO T_EVRE_LABEL_KEY_FIXED (ITA_LABEL_KEY_ID,ITA_LABEL_KEY,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('uuid A','gathering_event_id',NULL,'0',_____DATE_____,1);

INSERT INTO T_EVRE_LABEL_KEY_FIXED (ITA_LABEL_KEY_ID,ITA_LABEL_KEY,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('uuid B','ita_start_time',NULL,'0',_____DATE_____,1);

INSERT INTO T_EVRE_LABEL_KEY_FIXED (ITA_LABEL_KEY_ID,ITA_LABEL_KEY,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('uuid C','ita_fetched_time',NULL,'0',_____DATE_____,1);


