INSERT INTO T_EVRL_CONNECTION_METHOD (CONNECTION_METHOD_ID,CONNECTION_METHOD_NAME_EN,CONNECTION_METHOD_NAME_JA,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('1','Bearer Authentication','Bearer認証',NULL,'0',_____DATE_____,1);

INSERT INTO T_EVRL_CONNECTION_METHOD (CONNECTION_METHOD_ID,CONNECTION_METHOD_NAME_EN,CONNECTION_METHOD_NAME_JA,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2','password authentication','パスワード認証',NULL,'0',_____DATE_____,1);

INSERT INTO T_EVRL_CONNECTION_METHOD (CONNECTION_METHOD_ID,CONNECTION_METHOD_NAME_EN,CONNECTION_METHOD_NAME_JA,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('3','Authentication SharedKeyLite','SharedKeyLite認証',NULL,'0',_____DATE_____,1);

INSERT INTO T_EVRL_CONNECTION_METHOD (CONNECTION_METHOD_ID,CONNECTION_METHOD_NAME_EN,CONNECTION_METHOD_NAME_JA,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('4','IMAP password authentication','IMAP パスワード認証',NULL,'0',_____DATE_____,1);

INSERT INTO T_EVRL_CONNECTION_METHOD (CONNECTION_METHOD_ID,CONNECTION_METHOD_NAME_EN,CONNECTION_METHOD_NAME_JA,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('5','Zabbix Authentication','Zabbix認証',NULL,'0',_____DATE_____,1);


INSERT INTO T_EVRL_COMPARISON_METHOD (COMPARISON_METHOD_ID,COMPARISON_METHOD_NAME_EN,COMPARISON_METHOD_NAME_JA,COMPARISON_METHOD_SYMBOL,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('1','equals','等しい','==',NULL,'0',_____DATE_____,1);

INSERT INTO T_EVRL_COMPARISON_METHOD (COMPARISON_METHOD_ID,COMPARISON_METHOD_NAME_EN,COMPARISON_METHOD_NAME_JA,COMPARISON_METHOD_SYMBOL,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2','not equal','等しくない','≠',NULL,'0',_____DATE_____,1);

INSERT INTO T_EVRL_COMPARISON_METHOD (COMPARISON_METHOD_ID,COMPARISON_METHOD_NAME_EN,COMPARISON_METHOD_NAME_JA,COMPARISON_METHOD_SYMBOL,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('3','less than','より小さい','<',NULL,'0',_____DATE_____,1);

INSERT INTO T_EVRL_COMPARISON_METHOD (COMPARISON_METHOD_ID,COMPARISON_METHOD_NAME_EN,COMPARISON_METHOD_NAME_JA,COMPARISON_METHOD_SYMBOL,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('4','less than or equal to','以下','<=',NULL,'0',_____DATE_____,1);

INSERT INTO T_EVRL_COMPARISON_METHOD (COMPARISON_METHOD_ID,COMPARISON_METHOD_NAME_EN,COMPARISON_METHOD_NAME_JA,COMPARISON_METHOD_SYMBOL,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('5','greater than','より大きい','>',NULL,'0',_____DATE_____,1);

INSERT INTO T_EVRL_COMPARISON_METHOD (COMPARISON_METHOD_ID,COMPARISON_METHOD_NAME_EN,COMPARISON_METHOD_NAME_JA,COMPARISON_METHOD_SYMBOL,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('6','greater than or equal to','以上','>=',NULL,'0',_____DATE_____,1);

INSERT INTO T_EVRL_COMPARISON_METHOD (COMPARISON_METHOD_ID,COMPARISON_METHOD_NAME_EN,COMPARISON_METHOD_NAME_JA,COMPARISON_METHOD_SYMBOL,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('7','regular expression','正規表現','RegExp',NULL,'0',_____DATE_____,1);


INSERT INTO T_EVRL_TARGET_TYPE (TYPE_ID,TYPE_EN,TYPE_JA,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('1','string','文字列',NULL,'0',_____DATE_____,1);

INSERT INTO T_EVRL_TARGET_TYPE (TYPE_ID,TYPE_EN,TYPE_JA,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2','integer','整数',NULL,'0',_____DATE_____,1);

INSERT INTO T_EVRL_TARGET_TYPE (TYPE_ID,TYPE_EN,TYPE_JA,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('3','float','小数',NULL,'0',_____DATE_____,1);

INSERT INTO T_EVRL_TARGET_TYPE (TYPE_ID,TYPE_EN,TYPE_JA,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('4','bool','真偽値',NULL,'0',_____DATE_____,1);

INSERT INTO T_EVRL_TARGET_TYPE (TYPE_ID,TYPE_EN,TYPE_JA,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('5','object','オブジェクト',NULL,'0',_____DATE_____,1);

INSERT INTO T_EVRL_TARGET_TYPE (TYPE_ID,TYPE_EN,TYPE_JA,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('6','array','配列',NULL,'0',_____DATE_____,1);

INSERT INTO T_EVRL_TARGET_TYPE (TYPE_ID,TYPE_EN,TYPE_JA,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('7','any','その他',NULL,'0',_____DATE_____,1);


INSERT INTO T_EVRL_LABEL_KEY_FIXED (LABEL_KEY_ID,LABEL_KEY,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('uuid A','event_collection_settings_id',NULL,'0',_____DATE_____,1);

INSERT INTO T_EVRL_LABEL_KEY_FIXED (LABEL_KEY_ID,LABEL_KEY,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('uuid B','exastro_end_time',NULL,'0',_____DATE_____,1);

INSERT INTO T_EVRL_LABEL_KEY_FIXED (LABEL_KEY_ID,LABEL_KEY,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('uuid C','exastro_fetched_time',NULL,'0',_____DATE_____,1);


INSERT INTO T_EVRL_LABEL_KEY_INPUT (LABEL_KEY_ID,LABEL_KEY,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('uuid D','db-down',NULL,'0',_____DATE_____,1);
INSERT INTO T_EVRL_LABEL_KEY_INPUT_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,LABEL_KEY_ID,LABEL_KEY,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(1,_____DATE_____,'INSERT','uuid D','db-down',NULL,'0',_____DATE_____,1);
INSERT INTO T_EVRL_LABEL_KEY_INPUT (LABEL_KEY_ID,LABEL_KEY,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('uuid E','web-down',NULL,'0',_____DATE_____,1);
INSERT INTO T_EVRL_LABEL_KEY_INPUT_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,LABEL_KEY_ID,LABEL_KEY,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2,_____DATE_____,'INSERT','uuid E','web-down',NULL,'0',_____DATE_____,1);
INSERT INTO T_EVRL_LABEL_KEY_INPUT (LABEL_KEY_ID,LABEL_KEY,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('uuid F','hostname',NULL,'0',_____DATE_____,1);
INSERT INTO T_EVRL_LABEL_KEY_INPUT_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,LABEL_KEY_ID,LABEL_KEY,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(3,_____DATE_____,'INSERT','uuid F','hostname',NULL,'0',_____DATE_____,1);

INSERT INTO T_EVRL_LABEL_KEY_CONCLUSION (LABEL_KEY_ID,LABEL_KEY,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('uuid G','service-down',NULL,'0',_____DATE_____,1);
INSERT INTO T_EVRL_LABEL_KEY_CONCLUSION_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,LABEL_KEY_ID,LABEL_KEY,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(1,_____DATE_____,'INSERT','uuid G','service-down',NULL,'0',_____DATE_____,1);

