INSERT INTO T_COMN_MENU_GROUP (MENU_GROUP_ID,PARENT_MENU_GROUP_ID,MENU_GROUP_NAME_JA,MENU_GROUP_NAME_EN,MENU_GROUP_ICON,MENU_CREATE_TARGET_FLAG,DISP_SEQ,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(601,NULL,'エクスポート/インポート','Export/Import','migration.png','0',25,NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_GROUP_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,MENU_GROUP_ID,PARENT_MENU_GROUP_ID,MENU_GROUP_NAME_JA,MENU_GROUP_NAME_EN,MENU_GROUP_ICON,MENU_CREATE_TARGET_FLAG,DISP_SEQ,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(601,_____DATE_____,'INSERT',601,NULL,'エクスポート/インポート','Export/Import','migration.png','0',25,NULL,'0',_____DATE_____,1);

INSERT INTO T_COMN_MENU (MENU_ID,MENU_GROUP_ID,MENU_NAME_JA,MENU_NAME_EN,MENU_NAME_REST,DISP_SEQ,AUTOFILTER_FLG,INITIAL_FILTER_FLG,WEB_PRINT_LIMIT,WEB_PRINT_CONFIRM,XLS_PRINT_LIMIT,SORT_KEY,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(60101,601,'メニューエクスポート','Menu export','menu_export',70,1,0,NULL,NULL,NULL,'[{"ASC":"column_group_name_ja"}]',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,MENU_ID,MENU_GROUP_ID,MENU_NAME_JA,MENU_NAME_EN,MENU_NAME_REST,DISP_SEQ,AUTOFILTER_FLG,INITIAL_FILTER_FLG,WEB_PRINT_LIMIT,WEB_PRINT_CONFIRM,XLS_PRINT_LIMIT,SORT_KEY,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(60101,_____DATE_____,'INSERT',60101,601,'メニューエクスポート','Menu export','menu_export',70,1,0,NULL,NULL,NULL,'[{"ASC":"column_group_name_ja"}]',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU (MENU_ID,MENU_GROUP_ID,MENU_NAME_JA,MENU_NAME_EN,MENU_NAME_REST,DISP_SEQ,AUTOFILTER_FLG,INITIAL_FILTER_FLG,WEB_PRINT_LIMIT,WEB_PRINT_CONFIRM,XLS_PRINT_LIMIT,SORT_KEY,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(60102,601,'メニューインポート','Menu import','menu_import',80,1,0,NULL,NULL,NULL,'[{"ASC":"column_group_name_ja"}]',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,MENU_ID,MENU_GROUP_ID,MENU_NAME_JA,MENU_NAME_EN,MENU_NAME_REST,DISP_SEQ,AUTOFILTER_FLG,INITIAL_FILTER_FLG,WEB_PRINT_LIMIT,WEB_PRINT_CONFIRM,XLS_PRINT_LIMIT,SORT_KEY,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(60102,_____DATE_____,'INSERT',60102,601,'メニューインポート','Menu import','menu_import',80,1,0,NULL,NULL,NULL,'[{"ASC":"column_group_name_ja"}]',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU (MENU_ID,MENU_GROUP_ID,MENU_NAME_JA,MENU_NAME_EN,MENU_NAME_REST,DISP_SEQ,AUTOFILTER_FLG,INITIAL_FILTER_FLG,WEB_PRINT_LIMIT,WEB_PRINT_CONFIRM,XLS_PRINT_LIMIT,SORT_KEY,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(60103,601,'メニューエクスポート・インポート管理','Menu export import list','menu_export_import_list',90,1,0,NULL,NULL,NULL,'[{"ASC":"column_group_name_ja"}]',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,MENU_ID,MENU_GROUP_ID,MENU_NAME_JA,MENU_NAME_EN,MENU_NAME_REST,DISP_SEQ,AUTOFILTER_FLG,INITIAL_FILTER_FLG,WEB_PRINT_LIMIT,WEB_PRINT_CONFIRM,XLS_PRINT_LIMIT,SORT_KEY,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(60103,_____DATE_____,'INSERT',60103,601,'メニューエクスポート・インポート管理','Menu export import list','menu_export_import_list',90,1,0,NULL,NULL,NULL,'[{"ASC":"column_group_name_ja"}]',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU (MENU_ID,MENU_GROUP_ID,MENU_NAME_JA,MENU_NAME_EN,MENU_NAME_REST,DISP_SEQ,AUTOFILTER_FLG,INITIAL_FILTER_FLG,WEB_PRINT_LIMIT,WEB_PRINT_CONFIRM,XLS_PRINT_LIMIT,SORT_KEY,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(60104,601,'Excel一括エクスポート','Bulk excel export','bulk_excel_export',100,1,0,NULL,NULL,NULL,'[{"ASC":"column_group_name_ja"}]',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,MENU_ID,MENU_GROUP_ID,MENU_NAME_JA,MENU_NAME_EN,MENU_NAME_REST,DISP_SEQ,AUTOFILTER_FLG,INITIAL_FILTER_FLG,WEB_PRINT_LIMIT,WEB_PRINT_CONFIRM,XLS_PRINT_LIMIT,SORT_KEY,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(60104,_____DATE_____,'INSERT',60104,601,'Excel一括エクスポート','Bulk excel export','bulk_excel_export',100,1,0,NULL,NULL,NULL,'[{"ASC":"column_group_name_ja"}]',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU (MENU_ID,MENU_GROUP_ID,MENU_NAME_JA,MENU_NAME_EN,MENU_NAME_REST,DISP_SEQ,AUTOFILTER_FLG,INITIAL_FILTER_FLG,WEB_PRINT_LIMIT,WEB_PRINT_CONFIRM,XLS_PRINT_LIMIT,SORT_KEY,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(60105,601,'Excel一括インポート','Bulk excel import','bulk_excel_import',110,1,0,NULL,NULL,NULL,'[{"ASC":"column_group_name_ja"}]',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,MENU_ID,MENU_GROUP_ID,MENU_NAME_JA,MENU_NAME_EN,MENU_NAME_REST,DISP_SEQ,AUTOFILTER_FLG,INITIAL_FILTER_FLG,WEB_PRINT_LIMIT,WEB_PRINT_CONFIRM,XLS_PRINT_LIMIT,SORT_KEY,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(60105,_____DATE_____,'INSERT',60105,601,'Excel一括インポート','Bulk excel import','bulk_excel_import',110,1,0,NULL,NULL,NULL,'[{"ASC":"column_group_name_ja"}]',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU (MENU_ID,MENU_GROUP_ID,MENU_NAME_JA,MENU_NAME_EN,MENU_NAME_REST,DISP_SEQ,AUTOFILTER_FLG,INITIAL_FILTER_FLG,WEB_PRINT_LIMIT,WEB_PRINT_CONFIRM,XLS_PRINT_LIMIT,SORT_KEY,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(60106,601,'Excel一括エクスポート・インポート管理','Bulk excel export import list','bulk_excel_export_import_list',120,1,0,NULL,NULL,NULL,'[{"ASC":"column_group_name_ja"}]',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,MENU_ID,MENU_GROUP_ID,MENU_NAME_JA,MENU_NAME_EN,MENU_NAME_REST,DISP_SEQ,AUTOFILTER_FLG,INITIAL_FILTER_FLG,WEB_PRINT_LIMIT,WEB_PRINT_CONFIRM,XLS_PRINT_LIMIT,SORT_KEY,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(60106,_____DATE_____,'INSERT',60106,601,'Excel一括エクスポート・インポート管理','Bulk excel export import list','bulk_excel_export_import_list',120,1,0,NULL,NULL,NULL,'[{"ASC":"column_group_name_ja"}]',NULL,'0',_____DATE_____,1);

INSERT INTO T_COMN_ROLE_MENU_LINK (LINK_ID,MENU_ID,ROLE_ID,PRIVILEGE,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('60101','60101','__ROLE_ID__','1',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_ROLE_MENU_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,LINK_ID,MENU_ID,ROLE_ID,PRIVILEGE,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(60101,_____DATE_____,'INSERT','60101','60101','__ROLE_ID__','1',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_ROLE_MENU_LINK (LINK_ID,MENU_ID,ROLE_ID,PRIVILEGE,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('60102','60102','__ROLE_ID__','1',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_ROLE_MENU_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,LINK_ID,MENU_ID,ROLE_ID,PRIVILEGE,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(60102,_____DATE_____,'INSERT','60102','60102','__ROLE_ID__','1',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_ROLE_MENU_LINK (LINK_ID,MENU_ID,ROLE_ID,PRIVILEGE,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('60103','60103','__ROLE_ID__','2',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_ROLE_MENU_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,LINK_ID,MENU_ID,ROLE_ID,PRIVILEGE,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(60103,_____DATE_____,'INSERT','60103','60103','__ROLE_ID__','2',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_ROLE_MENU_LINK (LINK_ID,MENU_ID,ROLE_ID,PRIVILEGE,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('60104','60104','__ROLE_ID__','1',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_ROLE_MENU_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,LINK_ID,MENU_ID,ROLE_ID,PRIVILEGE,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(60104,_____DATE_____,'INSERT','60104','60104','__ROLE_ID__','1',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_ROLE_MENU_LINK (LINK_ID,MENU_ID,ROLE_ID,PRIVILEGE,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('60105','60105','__ROLE_ID__','1',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_ROLE_MENU_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,LINK_ID,MENU_ID,ROLE_ID,PRIVILEGE,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(60105,_____DATE_____,'INSERT','60105','60105','__ROLE_ID__','1',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_ROLE_MENU_LINK (LINK_ID,MENU_ID,ROLE_ID,PRIVILEGE,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('60106','60106','__ROLE_ID__','2',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_ROLE_MENU_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,LINK_ID,MENU_ID,ROLE_ID,PRIVILEGE,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(60106,_____DATE_____,'INSERT','60106','60106','__ROLE_ID__','2',NULL,'0',_____DATE_____,1);

INSERT INTO T_COMN_MENU_TABLE_LINK (TABLE_DEFINITION_ID,MENU_ID,TABLE_NAME,VIEW_NAME,PK_COLUMN_NAME_REST,MENU_INFO_JA,MENU_INFO_EN,SHEET_TYPE,HISTORY_TABLE_FLAG,INHERIT,VERTICAL,HOSTGROUP,ROW_INSERT_FLAG,ROW_UPDATE_FLAG,ROW_DISUSE_FLAG,ROW_REUSE_FLAG,SUBSTITUTION_VALUE_LINK_FLAG,LOCK_TABLE,UNIQUE_CONSTRAINT,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('60101','60101',NULL,NULL,NULL,'下記の機能を提供しています。
    ・メニューエクスポート
            データをエクスポートするメニューを選択し、エクスポートボタンをクリックしてください。

            モード
            ・環境移行
                    指定メニューのすべてのデータをエクスポートします。インポート先のデータをすべて置き換えます。
            ・時刻指定
                    指定時刻以降のデータのみエクスポートします。インポート先のデータとIDが被った場合はエクスポートしたデータが優先してインポートされます。

            廃止情報
            ・廃止を含む
                    廃止したレコードを含めてエクスポートします。
            ・廃止を除く
                    廃止したレコードを除いてエクスポートします。','The following functions are provided.
   ・Menu export
      Select the menu that you want to export data from and click the "Export" button.

Mode
   ・Environment migration
      Exports all the data of the selected menu and replaces the data in the import destination.

   ・Time specification
      Exports the data at the specified time.
If the ID is the same as the data of the important destination, the exported data has priority over the imported data.

Abolition data
   ・All records
      Exports all records
   ・Exclude discarded records
      Exports without discarded records','20','0','0','0','0','0','0','0','0','0',NULL,NULL,NULL,NULL,NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_TABLE_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,TABLE_DEFINITION_ID,MENU_ID,TABLE_NAME,VIEW_NAME,PK_COLUMN_NAME_REST,MENU_INFO_JA,MENU_INFO_EN,SHEET_TYPE,HISTORY_TABLE_FLAG,INHERIT,VERTICAL,HOSTGROUP,ROW_INSERT_FLAG,ROW_UPDATE_FLAG,ROW_DISUSE_FLAG,ROW_REUSE_FLAG,SUBSTITUTION_VALUE_LINK_FLAG,LOCK_TABLE,UNIQUE_CONSTRAINT,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(60101,_____DATE_____,'INSERT','60101','60101',NULL,NULL,NULL,'下記の機能を提供しています。
    ・メニューエクスポート
            データをエクスポートするメニューを選択し、エクスポートボタンをクリックしてください。

            モード
            ・環境移行
                    指定メニューのすべてのデータをエクスポートします。インポート先のデータをすべて置き換えます。
            ・時刻指定
                    指定時刻以降のデータのみエクスポートします。インポート先のデータとIDが被った場合はエクスポートしたデータが優先してインポートされます。

            廃止情報
            ・廃止を含む
                    廃止したレコードを含めてエクスポートします。
            ・廃止を除く
                    廃止したレコードを除いてエクスポートします。','The following functions are provided.
   ・Menu export
      Select the menu that you want to export data from and click the "Export" button.

Mode
   ・Environment migration
      Exports all the data of the selected menu and replaces the data in the import destination.

   ・Time specification
      Exports the data at the specified time.
If the ID is the same as the data of the important destination, the exported data has priority over the imported data.

Abolition data
   ・All records
      Exports all records
   ・Exclude discarded records
      Exports without discarded records','20','0','0','0','0','0','0','0','0','0',NULL,NULL,NULL,NULL,NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_TABLE_LINK (TABLE_DEFINITION_ID,MENU_ID,TABLE_NAME,VIEW_NAME,PK_COLUMN_NAME_REST,MENU_INFO_JA,MENU_INFO_EN,SHEET_TYPE,HISTORY_TABLE_FLAG,INHERIT,VERTICAL,HOSTGROUP,ROW_INSERT_FLAG,ROW_UPDATE_FLAG,ROW_DISUSE_FLAG,ROW_REUSE_FLAG,SUBSTITUTION_VALUE_LINK_FLAG,LOCK_TABLE,UNIQUE_CONSTRAINT,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('60102','60102',NULL,NULL,NULL,'下記の機能を提供しています。
・インポートデータのアップロード
    インポートするデータを圧縮したkymファイルをアップロードしてください。

・メニューインポート
    インポート可能なメニューが一覧表示されます。
    インポートするメニューを選択し、インポートボタンをクリックしてください。
    インポートするデータの状態はメニューインポート管理で確認できます。','The following functions are provided.
・Upload import data
    Upload the kym file containing the compressed data to import

・Import data
    A list of importable menus is displayed.
    Select the menus to import and click the import button.
    The status of imported data can be checked from the "Export/Import data list".','21','0','0','0','0','0','0','0','0','0',NULL,NULL,NULL,NULL,NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_TABLE_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,TABLE_DEFINITION_ID,MENU_ID,TABLE_NAME,VIEW_NAME,PK_COLUMN_NAME_REST,MENU_INFO_JA,MENU_INFO_EN,SHEET_TYPE,HISTORY_TABLE_FLAG,INHERIT,VERTICAL,HOSTGROUP,ROW_INSERT_FLAG,ROW_UPDATE_FLAG,ROW_DISUSE_FLAG,ROW_REUSE_FLAG,SUBSTITUTION_VALUE_LINK_FLAG,LOCK_TABLE,UNIQUE_CONSTRAINT,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(60102,_____DATE_____,'INSERT','60102','60102',NULL,NULL,NULL,'下記の機能を提供しています。
・インポートデータのアップロード
    インポートするデータを圧縮したkymファイルをアップロードしてください。

・メニューインポート
    インポート可能なメニューが一覧表示されます。
    インポートするメニューを選択し、インポートボタンをクリックしてください。
    インポートするデータの状態はメニューインポート管理で確認できます。','The following functions are provided.
・Upload import data
    Upload the kym file containing the compressed data to import

・Import data
    A list of importable menus is displayed.
    Select the menus to import and click the import button.
    The status of imported data can be checked from the "Export/Import data list".','21','0','0','0','0','0','0','0','0','0',NULL,NULL,NULL,NULL,NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_TABLE_LINK (TABLE_DEFINITION_ID,MENU_ID,TABLE_NAME,VIEW_NAME,PK_COLUMN_NAME_REST,MENU_INFO_JA,MENU_INFO_EN,SHEET_TYPE,HISTORY_TABLE_FLAG,INHERIT,VERTICAL,HOSTGROUP,ROW_INSERT_FLAG,ROW_UPDATE_FLAG,ROW_DISUSE_FLAG,ROW_REUSE_FLAG,SUBSTITUTION_VALUE_LINK_FLAG,LOCK_TABLE,UNIQUE_CONSTRAINT,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('60103','60103','T_MENU_EXPORT_IMPORT',NULL,'execution_no','下記の機能を提供しています。
・エクスポート/インポートデータの閲覧','The following functions are provided.
・View of exported or imported data list','0','1','0','0','0','1','1','1','1','0',NULL,NULL,NULL,NULL,NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_TABLE_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,TABLE_DEFINITION_ID,MENU_ID,TABLE_NAME,VIEW_NAME,PK_COLUMN_NAME_REST,MENU_INFO_JA,MENU_INFO_EN,SHEET_TYPE,HISTORY_TABLE_FLAG,INHERIT,VERTICAL,HOSTGROUP,ROW_INSERT_FLAG,ROW_UPDATE_FLAG,ROW_DISUSE_FLAG,ROW_REUSE_FLAG,SUBSTITUTION_VALUE_LINK_FLAG,LOCK_TABLE,UNIQUE_CONSTRAINT,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(60103,_____DATE_____,'INSERT','60103','60103','T_MENU_EXPORT_IMPORT',NULL,'execution_no','下記の機能を提供しています。
・エクスポート/インポートデータの閲覧','The following functions are provided.
・View of exported or imported data list','0','1','0','0','0','1','1','1','1','0',NULL,NULL,NULL,NULL,NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_TABLE_LINK (TABLE_DEFINITION_ID,MENU_ID,TABLE_NAME,VIEW_NAME,PK_COLUMN_NAME_REST,MENU_INFO_JA,MENU_INFO_EN,SHEET_TYPE,HISTORY_TABLE_FLAG,INHERIT,VERTICAL,HOSTGROUP,ROW_INSERT_FLAG,ROW_UPDATE_FLAG,ROW_DISUSE_FLAG,ROW_REUSE_FLAG,SUBSTITUTION_VALUE_LINK_FLAG,LOCK_TABLE,UNIQUE_CONSTRAINT,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('60104','60104',NULL,NULL,NULL,'下記の機能を提供しています。
・Excel一括エクスポート
    データをエクスポートするメニューを選択し、エクスポートボタンをクリックしてください。
廃止情報
        ・全レコード
            全てのレコードをエクスポートします。
        ・廃止を除く
            廃止したレコードを除いてエクスポートします。
        ・廃止のみ
            廃止したレコードのみエクスポートします。','The following functions are provided.
   ・Excel Bulk Export
      Select the menu that you want to export data from and click the "Export" button.
Abolition data
   ・All records
      Exports all records
   ・Exclude discarded records
      Exports without discarded records
   ・Only discarded records
      Exports only discarded records','22','0','0','0','0','0','0','0','0','0',NULL,NULL,NULL,NULL,NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_TABLE_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,TABLE_DEFINITION_ID,MENU_ID,TABLE_NAME,VIEW_NAME,PK_COLUMN_NAME_REST,MENU_INFO_JA,MENU_INFO_EN,SHEET_TYPE,HISTORY_TABLE_FLAG,INHERIT,VERTICAL,HOSTGROUP,ROW_INSERT_FLAG,ROW_UPDATE_FLAG,ROW_DISUSE_FLAG,ROW_REUSE_FLAG,SUBSTITUTION_VALUE_LINK_FLAG,LOCK_TABLE,UNIQUE_CONSTRAINT,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(60104,_____DATE_____,'INSERT','60104','60104',NULL,NULL,NULL,'下記の機能を提供しています。
・Excel一括エクスポート
    データをエクスポートするメニューを選択し、エクスポートボタンをクリックしてください。
廃止情報
        ・全レコード
            全てのレコードをエクスポートします。
        ・廃止を除く
            廃止したレコードを除いてエクスポートします。
        ・廃止のみ
            廃止したレコードのみエクスポートします。','The following functions are provided.
   ・Excel Bulk Export
      Select the menu that you want to export data from and click the "Export" button.
Abolition data
   ・All records
      Exports all records
   ・Exclude discarded records
      Exports without discarded records
   ・Only discarded records
      Exports only discarded records','22','0','0','0','0','0','0','0','0','0',NULL,NULL,NULL,NULL,NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_TABLE_LINK (TABLE_DEFINITION_ID,MENU_ID,TABLE_NAME,VIEW_NAME,PK_COLUMN_NAME_REST,MENU_INFO_JA,MENU_INFO_EN,SHEET_TYPE,HISTORY_TABLE_FLAG,INHERIT,VERTICAL,HOSTGROUP,ROW_INSERT_FLAG,ROW_UPDATE_FLAG,ROW_DISUSE_FLAG,ROW_REUSE_FLAG,SUBSTITUTION_VALUE_LINK_FLAG,LOCK_TABLE,UNIQUE_CONSTRAINT,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('60105','60105',NULL,NULL,NULL,'下記の機能を提供しています。
・インポートデータのアップロード
    インポートするデータを圧縮したzipファイルをアップロードしてください。

・Excel一括インポート
    インポート可能なメニューが一覧表示されます。
    インポートするメニューを選択し、インポートボタンをクリックしてください。
    インポートするデータの状態はExcel一括エクスポート・インポート管理で確認できます。','The following functions are provided.
・Upload import data
    Upload the zip file containing the compressed data to import

・Excel Bulk Import
    A list of importable menus is displayed.
    Select the menus to import and click the import button.
    The status of imported data can be checked from the "Excel Bulk Export/Import list".','23','0','0','0','0','0','0','0','0','0',NULL,NULL,NULL,NULL,NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_TABLE_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,TABLE_DEFINITION_ID,MENU_ID,TABLE_NAME,VIEW_NAME,PK_COLUMN_NAME_REST,MENU_INFO_JA,MENU_INFO_EN,SHEET_TYPE,HISTORY_TABLE_FLAG,INHERIT,VERTICAL,HOSTGROUP,ROW_INSERT_FLAG,ROW_UPDATE_FLAG,ROW_DISUSE_FLAG,ROW_REUSE_FLAG,SUBSTITUTION_VALUE_LINK_FLAG,LOCK_TABLE,UNIQUE_CONSTRAINT,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(60105,_____DATE_____,'INSERT','60105','60105',NULL,NULL,NULL,'下記の機能を提供しています。
・インポートデータのアップロード
    インポートするデータを圧縮したzipファイルをアップロードしてください。

・Excel一括インポート
    インポート可能なメニューが一覧表示されます。
    インポートするメニューを選択し、インポートボタンをクリックしてください。
    インポートするデータの状態はExcel一括エクスポート・インポート管理で確認できます。','The following functions are provided.
・Upload import data
    Upload the zip file containing the compressed data to import

・Excel Bulk Import
    A list of importable menus is displayed.
    Select the menus to import and click the import button.
    The status of imported data can be checked from the "Excel Bulk Export/Import list".','23','0','0','0','0','0','0','0','0','0',NULL,NULL,NULL,NULL,NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_TABLE_LINK (TABLE_DEFINITION_ID,MENU_ID,TABLE_NAME,VIEW_NAME,PK_COLUMN_NAME_REST,MENU_INFO_JA,MENU_INFO_EN,SHEET_TYPE,HISTORY_TABLE_FLAG,INHERIT,VERTICAL,HOSTGROUP,ROW_INSERT_FLAG,ROW_UPDATE_FLAG,ROW_DISUSE_FLAG,ROW_REUSE_FLAG,SUBSTITUTION_VALUE_LINK_FLAG,LOCK_TABLE,UNIQUE_CONSTRAINT,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('60106','60106','T_BULK_EXCEL_EXPORT_IMPORT',NULL,'execution_no','下記の機能を提供しています。
・Excel一括エクスポート・インポートデータの閲覧','The following functions are provided.
・View of Excel Bulk Export・Import list','0','1','0','0','0','1','1','1','1','0',NULL,NULL,NULL,NULL,NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_TABLE_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,TABLE_DEFINITION_ID,MENU_ID,TABLE_NAME,VIEW_NAME,PK_COLUMN_NAME_REST,MENU_INFO_JA,MENU_INFO_EN,SHEET_TYPE,HISTORY_TABLE_FLAG,INHERIT,VERTICAL,HOSTGROUP,ROW_INSERT_FLAG,ROW_UPDATE_FLAG,ROW_DISUSE_FLAG,ROW_REUSE_FLAG,SUBSTITUTION_VALUE_LINK_FLAG,LOCK_TABLE,UNIQUE_CONSTRAINT,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(60106,_____DATE_____,'INSERT','60106','60106','T_BULK_EXCEL_EXPORT_IMPORT',NULL,'execution_no','下記の機能を提供しています。
・Excel一括エクスポート・インポートデータの閲覧','The following functions are provided.
・View of Excel Bulk Export・Import list','0','1','0','0','0','1','1','1','1','0',NULL,NULL,NULL,NULL,NULL,'0',_____DATE_____,1);

INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('6010301','60103','実行No.','Execution No.','execution_no',NULL,'1',10,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'EXECUTION_NO',NULL,'1','1','1','1','1','1','0',NULL,NULL,NULL,NULL,NULL,'自動採番のため編集不可。実行処理種別が【登録】の場合、空白のみ可。','Cannot edit because of auto-numbering. Must be blank when execution process type is [Register].',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(6010301,_____DATE_____,'INSERT','6010301','60103','実行No.','Execution No.','execution_no',NULL,'1',10,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'EXECUTION_NO',NULL,'1','1','1','1','1','1','0',NULL,NULL,NULL,NULL,NULL,'自動採番のため編集不可。実行処理種別が【登録】の場合、空白のみ可。','Cannot edit because of auto-numbering. Must be blank when execution process type is [Register].',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('6010302','60103','ステータス','Status','status',NULL,'7',20,'T_DP_STATUS_MASTER','ROW_ID','TASK_STATUS_NAME',NULL,'1',NULL,NULL,NULL,NULL,'STATUS',NULL,'0','1','1','0','0','1','0',NULL,NULL,NULL,NULL,NULL,'ステータスには以下の状態が存在します。
・未実行
・実行中
・完了
・完了（異常）','The following states exist for status.
・Unexecuted
・Executing
・Completed
・Completed (error)',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(6010302,_____DATE_____,'INSERT','6010302','60103','ステータス','Status','status',NULL,'7',20,'T_DP_STATUS_MASTER','ROW_ID','TASK_STATUS_NAME',NULL,'1',NULL,NULL,NULL,NULL,'STATUS',NULL,'0','1','1','0','0','1','0',NULL,NULL,NULL,NULL,NULL,'ステータスには以下の状態が存在します。
・未実行
・実行中
・完了
・完了（異常）','The following states exist for status.
・Unexecuted
・Executing
・Completed
・Completed (error)',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('6010303','60103','処理種別','Execution Type','execution_type',NULL,'7',30,'T_DP_EXECUTION_TYPE','ROW_ID','EXECUTION_TYPE_NAME',NULL,'1',NULL,NULL,NULL,NULL,'EXECUTION_TYPE',NULL,'0','1','1','0','1','1','0',NULL,NULL,NULL,NULL,NULL,'処理種別には以下が存在します。
・エクスポート
・インポート','The following states exist for Execution type.
・Export
・Import',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(6010303,_____DATE_____,'INSERT','6010303','60103','処理種別','Execution Type','execution_type',NULL,'7',30,'T_DP_EXECUTION_TYPE','ROW_ID','EXECUTION_TYPE_NAME',NULL,'1',NULL,NULL,NULL,NULL,'EXECUTION_TYPE',NULL,'0','1','1','0','1','1','0',NULL,NULL,NULL,NULL,NULL,'処理種別には以下が存在します。
・エクスポート
・インポート','The following states exist for Execution type.
・Export
・Import',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('6010304','60103','モード','Mode','mode',NULL,'7',40,'T_DP_MODE','ROW_ID','MODE_NAME',NULL,'1',NULL,NULL,NULL,NULL,'MODE',NULL,'0','1','1','0','1','1','0',NULL,NULL,NULL,NULL,NULL,'モードには以下が存在します。
・環境移行
・時刻指定','The following modes exist.
・Override
・Add',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(6010304,_____DATE_____,'INSERT','6010304','60103','モード','Mode','mode',NULL,'7',40,'T_DP_MODE','ROW_ID','MODE_NAME',NULL,'1',NULL,NULL,NULL,NULL,'MODE',NULL,'0','1','1','0','1','1','0',NULL,NULL,NULL,NULL,NULL,'モードには以下が存在します。
・環境移行
・時刻指定','The following modes exist.
・Override
・Add',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('6010305','60103','廃止情報','Abolished Type','abolished_type',NULL,'7',50,'T_DP_ABOLISHED_TYPE','ROW_ID','ABOLISHED_TYPE_NAME',NULL,'1',NULL,NULL,NULL,NULL,'ABOLISHED_TYPE',NULL,'0','1','1','0','0','1','0',NULL,NULL,NULL,NULL,NULL,'廃止情報には以下が存在します。
・廃止を含む
・廃止を除く','The following abolition data exists.
・All records
・Exclude discarded records',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(6010305,_____DATE_____,'INSERT','6010305','60103','廃止情報','Abolished Type','abolished_type',NULL,'7',50,'T_DP_ABOLISHED_TYPE','ROW_ID','ABOLISHED_TYPE_NAME',NULL,'1',NULL,NULL,NULL,NULL,'ABOLISHED_TYPE',NULL,'0','1','1','0','0','1','0',NULL,NULL,NULL,NULL,NULL,'廃止情報には以下が存在します。
・廃止を含む
・廃止を除く','The following abolition data exists.
・All records
・Exclude discarded records',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('6010306','60103','指定時刻','Specified Time','specified_time',NULL,'5',60,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'SPECIFIED_TIME',NULL,'0','1','1','0','0','1','0',NULL,NULL,NULL,NULL,NULL,'モードが時刻指定の場合、指定時刻移行のレコードがエクスポート/インポートされます。','If the mode is "Time specification", records after the specified time will be exported/imported.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(6010306,_____DATE_____,'INSERT','6010306','60103','指定時刻','Specified Time','specified_time',NULL,'5',60,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'SPECIFIED_TIME',NULL,'0','1','1','0','0','1','0',NULL,NULL,NULL,NULL,NULL,'モードが時刻指定の場合、指定時刻移行のレコードがエクスポート/インポートされます。','If the mode is "Time specification", records after the specified time will be exported/imported.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('6010307','60103','ファイル名','File Name','file_name',NULL,'9',70,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'FILE_NAME',NULL,'0','1','1','0','0','1','0',NULL,NULL,NULL,NULL,NULL,'自動登録のため編集不可。','Cannot be edited (auto-registration)',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(6010307,_____DATE_____,'INSERT','6010307','60103','ファイル名','File Name','file_name',NULL,'9',70,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'FILE_NAME',NULL,'0','1','1','0','0','1','0',NULL,NULL,NULL,NULL,NULL,'自動登録のため編集不可。','Cannot be edited (auto-registration)',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('6010308','60103','実行ユーザ','Execution User','execution_user',NULL,'1',80,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'EXECUTION_USER',NULL,'0','1','1','0','0','1','0',NULL,NULL,NULL,NULL,NULL,'エクスポート処理またはインポート処理を実行したユーザが表示されます。','The user who executed the Export/Import process will be displayed.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(6010308,_____DATE_____,'INSERT','6010308','60103','実行ユーザ','Execution User','execution_user',NULL,'1',80,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'EXECUTION_USER',NULL,'0','1','1','0','0','1','0',NULL,NULL,NULL,NULL,NULL,'エクスポート処理またはインポート処理を実行したユーザが表示されます。','The user who executed the Export/Import process will be displayed.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('6010309','60103','JSON格納用項目','JSON Storage Item','json_storage_item',NULL,'2',90,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'JSON_STORAGE_ITEM',NULL,'0','2','0','0','0','1','0',NULL,'{
"min_length": 0,
"max_length": 4294967296
}',NULL,NULL,NULL,'JSON格納用項目','JSON Storage Item',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(6010309,_____DATE_____,'INSERT','6010309','60103','JSON格納用項目','JSON Storage Item','json_storage_item',NULL,'2',90,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'JSON_STORAGE_ITEM',NULL,'0','2','0','0','0','1','0',NULL,'{
"min_length": 0,
"max_length": 4294967296
}',NULL,NULL,NULL,'JSON格納用項目','JSON Storage Item',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('6010310','60103','廃止フラグ','Discard','discard',NULL,'1',100,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'DISUSE_FLAG',NULL,'1','1','1','0','1','1','0',NULL,NULL,NULL,NULL,NULL,'廃止フラグ。復活以外のオペレーションは不可。','Discard flag. Cannot do operation other than restore.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(6010310,_____DATE_____,'INSERT','6010310','60103','廃止フラグ','Discard','discard',NULL,'1',100,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'DISUSE_FLAG',NULL,'1','1','1','0','1','1','0',NULL,NULL,NULL,NULL,NULL,'廃止フラグ。復活以外のオペレーションは不可。','Discard flag. Cannot do operation other than restore.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('6010311','60103','最終更新日時','Last update date/time','last_update_date_time',NULL,'13',110,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'LAST_UPDATE_TIMESTAMP',NULL,'1','0','1','0','1','1','0',NULL,NULL,NULL,NULL,NULL,'レコードの最終更新日。自動登録のため編集不可。','Last update date of record. Cannot edit because of auto-registration.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(6010311,_____DATE_____,'INSERT','6010311','60103','最終更新日時','Last update date/time','last_update_date_time',NULL,'13',110,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'LAST_UPDATE_TIMESTAMP',NULL,'1','0','1','0','1','1','0',NULL,NULL,NULL,NULL,NULL,'レコードの最終更新日。自動登録のため編集不可。','Last update date of record. Cannot edit because of auto-registration.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('6010312','60103','最終更新者','Last updated by','last_updated_user',NULL,'14',120,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'LAST_UPDATE_USER',NULL,'1','0','1','0','1','1','0',NULL,NULL,NULL,NULL,NULL,'更新者。ログインユーザのIDが自動的に登録される。編集不可。','Updated by. Login user ID is automatically registered. Cannot edit.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(6010312,_____DATE_____,'INSERT','6010312','60103','最終更新者','Last updated by','last_updated_user',NULL,'14',120,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'LAST_UPDATE_USER',NULL,'1','0','1','0','1','1','0',NULL,NULL,NULL,NULL,NULL,'更新者。ログインユーザのIDが自動的に登録される。編集不可。','Updated by. Login user ID is automatically registered. Cannot edit.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('6010601','60106','実行No.','Execution No.','execution_no',NULL,'1',10,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'EXECUTION_NO',NULL,'1','1','1','1','1','1','0',NULL,NULL,NULL,NULL,NULL,'自動採番のため編集不可。実行処理種別が【登録】の場合、空白のみ可。','Cannot edit because of auto-numbering. Must be blank when execution process type is [Register].',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(6010601,_____DATE_____,'INSERT','6010601','60106','実行No.','Execution No.','execution_no',NULL,'1',10,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'EXECUTION_NO',NULL,'1','1','1','1','1','1','0',NULL,NULL,NULL,NULL,NULL,'自動採番のため編集不可。実行処理種別が【登録】の場合、空白のみ可。','Cannot edit because of auto-numbering. Must be blank when execution process type is [Register].',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('6010602','60106','ステータス','Status','status',NULL,'7',20,'T_DP_STATUS_MASTER','ROW_ID','TASK_STATUS_NAME',NULL,'1',NULL,NULL,NULL,NULL,'STATUS',NULL,'0','1','1','0','0','1','0',NULL,NULL,NULL,NULL,NULL,'ステータスには以下の状態が存在します。
・未実行
・実行中
・完了
・完了（異常）','The following states exist for status.
・Unexecuted
・Executing
・Completed
・Completed (error)',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(6010602,_____DATE_____,'INSERT','6010602','60106','ステータス','Status','status',NULL,'7',20,'T_DP_STATUS_MASTER','ROW_ID','TASK_STATUS_NAME',NULL,'1',NULL,NULL,NULL,NULL,'STATUS',NULL,'0','1','1','0','0','1','0',NULL,NULL,NULL,NULL,NULL,'ステータスには以下の状態が存在します。
・未実行
・実行中
・完了
・完了（異常）','The following states exist for status.
・Unexecuted
・Executing
・Completed
・Completed (error)',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('6010603','60106','処理種別','Execution Type','execution_type',NULL,'7',30,'T_DP_EXECUTION_TYPE','ROW_ID','EXECUTION_TYPE_NAME',NULL,'1',NULL,NULL,NULL,NULL,'EXECUTION_TYPE',NULL,'0','1','1','0','1','1','0',NULL,NULL,NULL,NULL,NULL,'処理種別には以下が存在します。
・エクスポート
・インポート','The following states exist for Execution type.
・Export
・Import',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(6010603,_____DATE_____,'INSERT','6010603','60106','処理種別','Execution Type','execution_type',NULL,'7',30,'T_DP_EXECUTION_TYPE','ROW_ID','EXECUTION_TYPE_NAME',NULL,'1',NULL,NULL,NULL,NULL,'EXECUTION_TYPE',NULL,'0','1','1','0','1','1','0',NULL,NULL,NULL,NULL,NULL,'処理種別には以下が存在します。
・エクスポート
・インポート','The following states exist for Execution type.
・Export
・Import',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('6010604','60106','廃止情報','Abolished Type','abolished_type',NULL,'7',40,'T_DP_ABOLISHED_TYPE','ROW_ID','ABOLISHED_TYPE_NAME',NULL,'1',NULL,NULL,NULL,NULL,'ABOLISHED_TYPE',NULL,'0','1','1','0','0','1','0',NULL,NULL,NULL,NULL,NULL,'廃止情報には以下が存在します。
・全レコード
・廃止を含む
・廃止を除く','The following abolition data exists.
・All records
・Exclude discarded records
・Only discarded records',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(6010604,_____DATE_____,'INSERT','6010604','60106','廃止情報','Abolished Type','abolished_type',NULL,'7',40,'T_DP_ABOLISHED_TYPE','ROW_ID','ABOLISHED_TYPE_NAME',NULL,'1',NULL,NULL,NULL,NULL,'ABOLISHED_TYPE',NULL,'0','1','1','0','0','1','0',NULL,NULL,NULL,NULL,NULL,'廃止情報には以下が存在します。
・全レコード
・廃止を含む
・廃止を除く','The following abolition data exists.
・All records
・Exclude discarded records
・Only discarded records',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('6010605','60106','実行ユーザ','Execution User','execution_user',NULL,'27',50,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'EXECUTION_USER',NULL,'0','1','1','0','0','1','0',NULL,NULL,NULL,NULL,NULL,'エクスポート処理またはインポート処理を実行したユーザが表示されます。','The user who executed the Export/Import process will be displayed.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(6010605,_____DATE_____,'INSERT','6010605','60106','実行ユーザ','Execution User','execution_user',NULL,'27',50,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'EXECUTION_USER',NULL,'0','1','1','0','0','1','0',NULL,NULL,NULL,NULL,NULL,'エクスポート処理またはインポート処理を実行したユーザが表示されます。','The user who executed the Export/Import process will be displayed.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('6010606','60106','ファイル名','File Name','file_name',NULL,'9',60,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'FILE_NAME',NULL,'0','1','1','0','0','1','0',NULL,NULL,NULL,NULL,NULL,'自動登録のため編集不可。','Cannot be edited (auto-registration)',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(6010606,_____DATE_____,'INSERT','6010606','60106','ファイル名','File Name','file_name',NULL,'9',60,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'FILE_NAME',NULL,'0','1','1','0','0','1','0',NULL,NULL,NULL,NULL,NULL,'自動登録のため編集不可。','Cannot be edited (auto-registration)',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('6010607','60106','言語','Language','language',NULL,'1',70,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'LANGUAGE',NULL,'0','1','1','0','0','1','0',NULL,NULL,NULL,NULL,NULL,'自動登録のため編集不可。','Cannot be edited (auto-registration)',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(6010607,_____DATE_____,'INSERT','6010607','60106','言語','Language','language',NULL,'1',70,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'LANGUAGE',NULL,'0','1','1','0','0','1','0',NULL,NULL,NULL,NULL,NULL,'自動登録のため編集不可。','Cannot be edited (auto-registration)',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('6010608','60106','結果','Result File','result_file',NULL,'9',80,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'RESULT_FILE',NULL,'0','1','1','0','0','1','0',NULL,NULL,NULL,NULL,NULL,'自動登録のため編集不可。','Cannot be edited (auto-registration)',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(6010608,_____DATE_____,'INSERT','6010608','60106','結果','Result File','result_file',NULL,'9',80,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'RESULT_FILE',NULL,'0','1','1','0','0','1','0',NULL,NULL,NULL,NULL,NULL,'自動登録のため編集不可。','Cannot be edited (auto-registration)',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('6010609','60106','JSON格納用項目','JSON Storage Item','json_storage_item',NULL,'2',90,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'JSON_STORAGE_ITEM',NULL,'0','2','0','0','0','1','0',NULL,'{
"min_length": 0,
"max_length": 4294967296
}',NULL,NULL,NULL,'JSON格納用項目','JSON Storage Item',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(6010609,_____DATE_____,'INSERT','6010609','60106','JSON格納用項目','JSON Storage Item','json_storage_item',NULL,'2',90,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'JSON_STORAGE_ITEM',NULL,'0','2','0','0','0','1','0',NULL,'{
"min_length": 0,
"max_length": 4294967296
}',NULL,NULL,NULL,'JSON格納用項目','JSON Storage Item',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('6010610','60106','廃止フラグ','Discard','discard',NULL,'1',110,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'DISUSE_FLAG',NULL,'1','1','1','0','1','1','0',NULL,NULL,NULL,NULL,NULL,'廃止フラグ。復活以外のオペレーションは不可。','Discard flag. Cannot do operation other than restore.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(6010610,_____DATE_____,'INSERT','6010610','60106','廃止フラグ','Discard','discard',NULL,'1',110,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'DISUSE_FLAG',NULL,'1','1','1','0','1','1','0',NULL,NULL,NULL,NULL,NULL,'廃止フラグ。復活以外のオペレーションは不可。','Discard flag. Cannot do operation other than restore.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('6010611','60106','最終更新日時','Last update date/time','last_update_date_time',NULL,'13',120,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'LAST_UPDATE_TIMESTAMP',NULL,'1','0','1','0','1','1','0',NULL,NULL,NULL,NULL,NULL,'レコードの最終更新日。自動登録のため編集不可。','Last update date of record. Cannot edit because of auto-registration.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(6010611,_____DATE_____,'INSERT','6010611','60106','最終更新日時','Last update date/time','last_update_date_time',NULL,'13',120,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'LAST_UPDATE_TIMESTAMP',NULL,'1','0','1','0','1','1','0',NULL,NULL,NULL,NULL,NULL,'レコードの最終更新日。自動登録のため編集不可。','Last update date of record. Cannot edit because of auto-registration.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('6010612','60106','最終更新者','Last updated by','last_updated_user',NULL,'14',130,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'LAST_UPDATE_USER',NULL,'1','0','1','0','1','1','0',NULL,NULL,NULL,NULL,NULL,'更新者。ログインユーザのIDが自動的に登録される。編集不可。','Updated by. Login user ID is automatically registered. Cannot edit.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(6010612,_____DATE_____,'INSERT','6010612','60106','最終更新者','Last updated by','last_updated_user',NULL,'14',130,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'LAST_UPDATE_USER',NULL,'1','0','1','0','1','1','0',NULL,NULL,NULL,NULL,NULL,'更新者。ログインユーザのIDが自動的に登録される。編集不可。','Updated by. Login user ID is automatically registered. Cannot edit.',NULL,'0',_____DATE_____,1);

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('1','20206');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('2','20207');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('3','20208');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('4','20209');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('5','20210');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('6','20308');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('7','20309');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('8','20310');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('9','20311');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('10','20312');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('11','20408');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('12','20409');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('13','20410');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('14','20411');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('15','20412');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('16','30104');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('17','30105');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('18','30106');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('19','30108');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('20','30109');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('21','50101');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('22','50109');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('23','50191');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('24','50192');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('25','60101');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('26','60102');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('27','60103');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('28','60104');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('29','60105');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('30','60106');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('31','60107');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('32','80113');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('33','80114');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('34','80115');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('35','80116');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('36','80117');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('37','90108');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('38','90109');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('39','90110');

INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('40','90111');


INSERT INTO T_DP_STATUS_MASTER (ROW_ID,TASK_STATUS_NAME_JA,TASK_STATUS_NAME_EN,DISP_SEQ,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(1,'未実行','Unexecuted',10,NULL,'0',_____DATE_____,1);

INSERT INTO T_DP_STATUS_MASTER (ROW_ID,TASK_STATUS_NAME_JA,TASK_STATUS_NAME_EN,DISP_SEQ,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2,'実行中','Executing',20,NULL,'0',_____DATE_____,1);

INSERT INTO T_DP_STATUS_MASTER (ROW_ID,TASK_STATUS_NAME_JA,TASK_STATUS_NAME_EN,DISP_SEQ,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(3,'完了','Completed',30,NULL,'0',_____DATE_____,1);

INSERT INTO T_DP_STATUS_MASTER (ROW_ID,TASK_STATUS_NAME_JA,TASK_STATUS_NAME_EN,DISP_SEQ,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(4,'完了 (異常)','Completed (error)',40,NULL,'0',_____DATE_____,1);


INSERT INTO T_DP_EXECUTION_TYPE (ROW_ID,EXECUTION_TYPE_NAME_JA,EXECUTION_TYPE_NAME_EN,DISP_SEQ,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(1,'エクスポート','Export',10,NULL,'0',_____DATE_____,1);

INSERT INTO T_DP_EXECUTION_TYPE (ROW_ID,EXECUTION_TYPE_NAME_JA,EXECUTION_TYPE_NAME_EN,DISP_SEQ,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2,'インポート','Import',20,NULL,'0',_____DATE_____,1);


INSERT INTO T_DP_MODE (ROW_ID,MODE_NAME_JA,MODE_NAME_EN,DISP_SEQ,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(1,'環境移行','Override',10,NULL,'0',_____DATE_____,1);

INSERT INTO T_DP_MODE (ROW_ID,MODE_NAME_JA,MODE_NAME_EN,DISP_SEQ,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2,'時刻指定','Add',20,NULL,'0',_____DATE_____,1);


INSERT INTO T_DP_ABOLISHED_TYPE (ROW_ID,ABOLISHED_TYPE_NAME_JA,ABOLISHED_TYPE_NAME_EN,DISP_SEQ,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(1,'廃止を含む','All records',10,NULL,'0',_____DATE_____,1);

INSERT INTO T_DP_ABOLISHED_TYPE (ROW_ID,ABOLISHED_TYPE_NAME_JA,ABOLISHED_TYPE_NAME_EN,DISP_SEQ,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2,'廃止を除く','Exclude discarded records',20,NULL,'0',_____DATE_____,1);

INSERT INTO T_DP_ABOLISHED_TYPE (ROW_ID,ABOLISHED_TYPE_NAME_JA,ABOLISHED_TYPE_NAME_EN,DISP_SEQ,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(3,'廃止のみ','Only discarded records',30,NULL,'0',_____DATE_____,1);


