-- Terraformステータスマスタ
CREATE TABLE T_TERF_EXEC_STATUS
(
    EXEC_STATUS_ID                  VARCHAR(2),                                 -- UUID
    EXEC_STATUS_NAME_JA             VARCHAR(256),                               -- 実行状態名(ja)
    EXEC_STATUS_NAME_EN             VARCHAR(256),                               -- 実行状態名(en)
    DISP_SEQ                        INT,                                        -- 表示順序
    NOTE                            VARCHAR(4000),                              -- 備考
    DISUSE_FLAG                     VARCHAR(1),                                 -- 廃止フラグ
    LAST_UPDATE_TIMESTAMP           DATETIME(6),                                -- 最終更新日時
    LAST_UPDATE_USER                VARCHAR(40),                                -- 最終更新者
    PRIMARY KEY(EXEC_STATUS_ID)
)ENGINE = InnoDB, CHARSET = utf8mb4, COLLATE = utf8mb4_bin, ROW_FORMAT=COMPRESSED ,KEY_BLOCK_SIZE=8;




-- Terraform実行種別マスタ
CREATE TABLE T_TERF_EXEC_MODE
(
    EXEC_MODE_ID                    VARCHAR(2),                                 -- UUID
    EXEC_MODE_NAME_JA               VARCHAR(256),                               -- 実行モード名(ja)
    EXEC_MODE_NAME_EN               VARCHAR(256),                               -- 実行モード名(en)
    DISP_SEQ                        INT,                                        -- 表示順序
    NOTE                            VARCHAR(4000),                              -- 備考
    DISUSE_FLAG                     VARCHAR(1),                                 -- 廃止フラグ
    LAST_UPDATE_TIMESTAMP           DATETIME(6),                                -- 最終更新日時
    LAST_UPDATE_USER                VARCHAR(40),                                -- 最終更新者
    PRIMARY KEY(EXEC_MODE_ID)
)ENGINE = InnoDB, CHARSET = utf8mb4, COLLATE = utf8mb4_bin, ROW_FORMAT=COMPRESSED ,KEY_BLOCK_SIZE=8;




-- Terraformタイプマスタ
CREATE TABLE T_TERF_TYPE_MASTER
(
    TYPE_ID                         VARCHAR(2),                                 -- UUID
    TYPE_NAME                       VARCHAR(256),                               -- タイプ名
    MEMBER_VARS_FLAG                VARCHAR(1),                                 -- メンバー変数フラグ
    ASSIGN_SEQ_FLAG                 VARCHAR(1),                                 -- 代入順序フラグ
    ENCODE_FLAG                     VARCHAR(1),                                 -- エンコードフラグ
    DISP_SEQ                        INT,                                        -- 表示順序
    NOTE                            VARCHAR(4000),                              -- 備考
    DISUSE_FLAG                     VARCHAR(1),                                 -- 廃止フラグ
    LAST_UPDATE_TIMESTAMP           DATETIME(6),                                -- 最終更新日時
    LAST_UPDATE_USER                VARCHAR(40),                                -- 最終更新者
    PRIMARY KEY(TYPE_ID)
)ENGINE = InnoDB, CHARSET = utf8mb4, COLLATE = utf8mb4_bin, ROW_FORMAT=COMPRESSED ,KEY_BLOCK_SIZE=8;




-- 登録方式
CREATE TABLE T_TERF_AUTOREG_REG_TYPE
(
    TYPE_ID                         VARCHAR(2),                                 -- UUID
    TYPE_NAME_JA                    VARCHAR(256),                               -- タイプ名(日本語)
    TYPE_NAME_EN                    VARCHAR(256),                               -- タイプ名(英語)
    DISP_SEQ                        INT,                                        -- 表示順序
    NOTE                            VARCHAR(4000),                              -- 備考
    DISUSE_FLAG                     VARCHAR(1),                                 -- 廃止フラグ
    LAST_UPDATE_TIMESTAMP           DATETIME(6),                                -- 最終更新日時
    LAST_UPDATE_USER                VARCHAR(40),                                -- 最終更新者
    PRIMARY KEY(TYPE_ID)
)ENGINE = InnoDB, CHARSET = utf8mb4, COLLATE = utf8mb4_bin, ROW_FORMAT=COMPRESSED ,KEY_BLOCK_SIZE=8;




-- 代入値自動登録用項目表示
CREATE VIEW V_TERF_COLUMN_LIST AS 
SELECT
TAB_A.COLUMN_DEFINITION_ID,
TAB_A.MENU_ID,
TAB_A.COLUMN_NAME_JA,
TAB_A.COLUMN_NAME_EN,
TAB_A.COLUMN_NAME_REST,
TAB_A.COL_GROUP_ID,
TAB_A.COLUMN_CLASS,
TAB_A.COLUMN_DISP_SEQ,
TAB_A.REF_TABLE_NAME,
TAB_A.REF_PKEY_NAME,
TAB_A.REF_COL_NAME,
TAB_A.REF_SORT_CONDITIONS,
TAB_A.REF_MULTI_LANG,
TAB_A.SENSITIVE_COL_NAME,
TAB_A.FILE_UPLOAD_PLACE,
TAB_A.COL_NAME,
TAB_A.SAVE_TYPE,
TAB_A.AUTO_INPUT,
TAB_A.INPUT_ITEM,
TAB_A.VIEW_ITEM,
TAB_A.UNIQUE_ITEM,
TAB_A.REQUIRED_ITEM,
TAB_A.AUTOREG_HIDE_ITEM,
TAB_A.AUTOREG_ONLY_ITEM,
TAB_A.INITIAL_VALUE,
TAB_A.VALIDATE_OPTION,
TAB_A.BEFORE_VALIDATE_REGISTER,
TAB_A.AFTER_VALIDATE_REGISTER,
TAB_A.DESCRIPTION_JA,
TAB_A.DESCRIPTION_EN,
TAB_A.NOTE,
TAB_A.DISUSE_FLAG,
TAB_A.LAST_UPDATE_TIMESTAMP,
TAB_A.LAST_UPDATE_USER,
TAB_B.VERTICAL,
concat(TAB_D.MENU_GROUP_NAME_JA, ":", concat(TAB_C.MENU_NAME_JA, ":" , TAB_A.COLUMN_NAME_JA)) as GROUP_MENU_COLUMN_NAME_JA,
concat(TAB_D.MENU_GROUP_NAME_EN, ":", concat(TAB_C.MENU_NAME_EN, ":" , TAB_A.COLUMN_NAME_EN)) as GROUP_MENU_COLUMN_NAME_EN
FROM T_COMN_MENU_COLUMN_LINK TAB_A 
LEFT JOIN T_COMN_MENU_TABLE_LINK TAB_B ON (TAB_A.MENU_ID = TAB_B.MENU_ID)
LEFT JOIN T_COMN_MENU TAB_C ON (TAB_B.MENU_ID = TAB_C.MENU_ID)
LEFT JOIN T_COMN_MENU_GROUP TAB_D ON ( TAB_C.MENU_GROUP_ID = TAB_D.MENU_GROUP_ID )
WHERE TAB_A.AUTOREG_HIDE_ITEM = 0
AND TAB_A.DISUSE_FLAG = 0
AND TAB_B.SHEET_TYPE = 3
AND TAB_B.DISUSE_FLAG = 0
AND TAB_B.SUBSTITUTION_VALUE_LINK_FLAG =1
AND TAB_C.DISUSE_FLAG = 0
AND TAB_D.DISUSE_FLAG = 0;
CREATE VIEW V_TERF_COLUMN_LIST_JNL AS 
SELECT
TAB_A.JOURNAL_SEQ_NO,
TAB_A.JOURNAL_REG_DATETIME,
TAB_A.JOURNAL_ACTION_CLASS,
TAB_A.COLUMN_DEFINITION_ID,
TAB_A.MENU_ID,
TAB_A.COLUMN_NAME_JA,
TAB_A.COLUMN_NAME_EN,
TAB_A.COLUMN_NAME_REST,
TAB_A.COL_GROUP_ID,
TAB_A.COLUMN_CLASS,
TAB_A.COLUMN_DISP_SEQ,
TAB_A.REF_TABLE_NAME,
TAB_A.REF_PKEY_NAME,
TAB_A.REF_COL_NAME,
TAB_A.REF_SORT_CONDITIONS,
TAB_A.REF_MULTI_LANG,
TAB_A.SENSITIVE_COL_NAME,
TAB_A.FILE_UPLOAD_PLACE,
TAB_A.COL_NAME,
TAB_A.SAVE_TYPE,
TAB_A.AUTO_INPUT,
TAB_A.INPUT_ITEM,
TAB_A.VIEW_ITEM,
TAB_A.UNIQUE_ITEM,
TAB_A.REQUIRED_ITEM,
TAB_A.AUTOREG_HIDE_ITEM,
TAB_A.AUTOREG_ONLY_ITEM,
TAB_A.INITIAL_VALUE,
TAB_A.VALIDATE_OPTION,
TAB_A.BEFORE_VALIDATE_REGISTER,
TAB_A.AFTER_VALIDATE_REGISTER,
TAB_A.DESCRIPTION_JA,
TAB_A.DESCRIPTION_EN,
TAB_A.NOTE,
TAB_A.DISUSE_FLAG,
TAB_A.LAST_UPDATE_TIMESTAMP,
TAB_A.LAST_UPDATE_USER,
TAB_B.VERTICAL,
concat(TAB_D.MENU_GROUP_NAME_JA, ":", concat(TAB_C.MENU_NAME_JA, ":" , TAB_A.COLUMN_NAME_JA)) as GROUP_MENU_COLUMN_NAME_JA,
concat(TAB_D.MENU_GROUP_NAME_EN, ":", concat(TAB_C.MENU_NAME_EN, ":" , TAB_A.COLUMN_NAME_EN)) as GROUP_MENU_COLUMN_NAME_EN
FROM T_COMN_MENU_COLUMN_LINK_JNL TAB_A 
LEFT JOIN T_COMN_MENU_TABLE_LINK_JNL TAB_B ON (TAB_A.MENU_ID = TAB_B.MENU_ID)
LEFT JOIN T_COMN_MENU_JNL TAB_C ON (TAB_B.MENU_ID = TAB_C.MENU_ID)
LEFT JOIN T_COMN_MENU_GROUP_JNL TAB_D ON ( TAB_C.MENU_GROUP_ID = TAB_D.MENU_GROUP_ID )
WHERE TAB_A.AUTOREG_HIDE_ITEM = 0
AND TAB_A.DISUSE_FLAG = 0
AND TAB_B.SHEET_TYPE = 3
AND TAB_B.DISUSE_FLAG = 0
AND TAB_B.SUBSTITUTION_VALUE_LINK_FLAG =1
AND TAB_C.DISUSE_FLAG = 0
AND TAB_D.DISUSE_FLAG = 0;



-- 代入値自動登録用メニュー表示
CREATE VIEW V_TERF_MENU AS 
SELECT
TAB_A.COLUMN_DEFINITION_ID,
TAB_A.MENU_ID,
TAB_A.COLUMN_NAME_JA,
TAB_A.COLUMN_NAME_EN,
TAB_A.COLUMN_NAME_REST,
TAB_A.COL_GROUP_ID,
TAB_A.COLUMN_CLASS,
TAB_A.COLUMN_DISP_SEQ,
TAB_A.REF_TABLE_NAME,
TAB_A.REF_PKEY_NAME,
TAB_A.REF_COL_NAME,
TAB_A.REF_SORT_CONDITIONS,
TAB_A.REF_MULTI_LANG,
TAB_A.SENSITIVE_COL_NAME,
TAB_A.FILE_UPLOAD_PLACE,
TAB_A.COL_NAME,
TAB_A.SAVE_TYPE,
TAB_A.AUTO_INPUT,
TAB_A.INPUT_ITEM,
TAB_A.VIEW_ITEM,
TAB_A.UNIQUE_ITEM,
TAB_A.REQUIRED_ITEM,
TAB_A.AUTOREG_HIDE_ITEM,
TAB_A.AUTOREG_ONLY_ITEM,
TAB_A.INITIAL_VALUE,
TAB_A.VALIDATE_OPTION,
TAB_A.BEFORE_VALIDATE_REGISTER,
TAB_A.AFTER_VALIDATE_REGISTER,
TAB_A.DESCRIPTION_JA,
TAB_A.DESCRIPTION_EN,
TAB_A.NOTE,
TAB_A.DISUSE_FLAG,
TAB_A.LAST_UPDATE_TIMESTAMP,
TAB_A.LAST_UPDATE_USER,
TAB_C.MENU_NAME_JA,
TAB_C.MENU_NAME_EN
FROM
T_COMN_MENU_COLUMN_LINK TAB_A 
LEFT JOIN
T_COMN_MENU_TABLE_LINK TAB_B ON (TAB_A.MENU_ID = TAB_B.MENU_ID)
LEFT JOIN
T_COMN_MENU TAB_C ON (TAB_B.MENU_ID = TAB_C.MENU_ID)
WHERE TAB_A.AUTOREG_HIDE_ITEM = 0
AND TAB_A.DISUSE_FLAG = 0
AND TAB_B.SHEET_TYPE = 3
AND TAB_B.DISUSE_FLAG = 0
AND TAB_B.SUBSTITUTION_VALUE_LINK_FLAG =1
AND TAB_C.DISUSE_FLAG = 0;
CREATE VIEW V_TERF_MENU_JNL AS 
SELECT
TAB_A.JOURNAL_SEQ_NO,
TAB_A.JOURNAL_REG_DATETIME,
TAB_A.JOURNAL_ACTION_CLASS,
TAB_A.COLUMN_DEFINITION_ID,
TAB_A.MENU_ID,
TAB_A.COLUMN_NAME_JA,
TAB_A.COLUMN_NAME_EN,
TAB_A.COLUMN_NAME_REST,
TAB_A.COL_GROUP_ID,
TAB_A.COLUMN_CLASS,
TAB_A.COLUMN_DISP_SEQ,
TAB_A.REF_TABLE_NAME,
TAB_A.REF_PKEY_NAME,
TAB_A.REF_COL_NAME,
TAB_A.REF_SORT_CONDITIONS,
TAB_A.REF_MULTI_LANG,
TAB_A.SENSITIVE_COL_NAME,
TAB_A.FILE_UPLOAD_PLACE,
TAB_A.COL_NAME,
TAB_A.SAVE_TYPE,
TAB_A.AUTO_INPUT,
TAB_A.INPUT_ITEM,
TAB_A.VIEW_ITEM,
TAB_A.UNIQUE_ITEM,
TAB_A.REQUIRED_ITEM,
TAB_A.AUTOREG_HIDE_ITEM,
TAB_A.AUTOREG_ONLY_ITEM,
TAB_A.INITIAL_VALUE,
TAB_A.VALIDATE_OPTION,
TAB_A.BEFORE_VALIDATE_REGISTER,
TAB_A.AFTER_VALIDATE_REGISTER,
TAB_A.DESCRIPTION_JA,
TAB_A.DESCRIPTION_EN,
TAB_A.NOTE,
TAB_A.DISUSE_FLAG,
TAB_A.LAST_UPDATE_TIMESTAMP,
TAB_A.LAST_UPDATE_USER,
TAB_C.MENU_NAME_JA,
TAB_C.MENU_NAME_EN
FROM
T_COMN_MENU_COLUMN_LINK_JNL TAB_A 
LEFT JOIN
T_COMN_MENU_TABLE_LINK_JNL TAB_B ON (TAB_A.MENU_ID = TAB_B.MENU_ID)
LEFT JOIN
T_COMN_MENU_JNL TAB_C ON (TAB_B.MENU_ID = TAB_C.MENU_ID)
WHERE TAB_A.AUTOREG_HIDE_ITEM = 0
AND TAB_A.DISUSE_FLAG = 0
AND TAB_B.SHEET_TYPE = 3
AND TAB_B.DISUSE_FLAG = 0
AND TAB_B.SUBSTITUTION_VALUE_LINK_FLAG =1
AND TAB_C.DISUSE_FLAG = 0;



