#
# https://docs.github.com/en/enterprise-cloud@latest/code-security/secret-scanning/configuring-secret-scanning-for-your-repositories#excluding-directories-from-secret-scanning-alerts-for-users
#
paths-ignore:
  - "ita_root/ita_api_organization/tests/db/exports/**"
  - "ita_root/ita_api_organization/pytest.ini.sample"
  - "ita_root/ita_by_oase_conclusion/tests/db/exports/**"
  - "ita_root/ita_by_oase_conclusion/pytest.ini.sample"
