-- CREATE TABLE/VIEW: -2.1.0
    -- V_MENU_PARAMETER_SHEET_REFERENCE_ITEM

-- ALTER: -2.1.0
    -- T_MENU_DEFINE


-- パラメータシート定義一覧
ALTER TABLE T_MENU_DEFINE ADD COLUMN HOSTGROUP VARCHAR(2) AFTER VERTICAL;
ALTER TABLE T_MENU_DEFINE_JNL ADD COLUMN HOSTGROUP VARCHAR(2) AFTER VERTICAL;

-- パラメータシート参照用ビュー
CREATE OR REPLACE VIEW V_MENU_PARAMETER_SHEET_REFERENCE_ITEM AS
SELECT
    TAB_A.COLUMN_DEFINITION_ID,
    TAB_B.MENU_GROUP_ID,
    TAB_D.MENU_GROUP_NAME_JA,
    TAB_D.MENU_GROUP_NAME_EN,
    TAB_B.MENU_ID,
    TAB_B.MENU_NAME_JA,
    TAB_B.MENU_NAME_EN,
    TAB_C.TABLE_NAME,
    TAB_C.VIEW_NAME,
    TAB_A.COLUMN_CLASS,
    TAB_A.COLUMN_NAME_REST,
    TAB_A.COLUMN_NAME_JA,
    TAB_A.COLUMN_NAME_EN,
    TAB_A.COL_GROUP_ID,
    TAB_E.FULL_COL_GROUP_NAME_JA,
    TAB_E.FULL_COL_GROUP_NAME_EN,
    CASE WHEN TAB_E.FULL_COL_GROUP_NAME_JA IS NULL THEN CONCAT(TAB_D.MENU_GROUP_NAME_JA,':',TAB_B.MENU_NAME_JA,':',TAB_A.COLUMN_NAME_JA) ELSE CONCAT(TAB_D.MENU_GROUP_NAME_JA,':',TAB_B.MENU_NAME_JA,':',TAB_E.FULL_COL_GROUP_NAME_JA,'/',TAB_A.COLUMN_NAME_JA) END AS SELECT_FULL_NAME_JA,
    CASE WHEN TAB_E.FULL_COL_GROUP_NAME_EN IS NULL THEN CONCAT(TAB_D.MENU_GROUP_NAME_EN,':',TAB_B.MENU_NAME_EN,':',TAB_A.COLUMN_NAME_EN) ELSE CONCAT(TAB_D.MENU_GROUP_NAME_EN,':',TAB_B.MENU_NAME_EN,':',TAB_E.FULL_COL_GROUP_NAME_EN,'/',TAB_A.COLUMN_NAME_EN) END AS SELECT_FULL_NAME_EN,
    TAB_A.COLUMN_DISP_SEQ,
    TAB_A.NOTE,
    TAB_A.DISUSE_FLAG,
    TAB_A.LAST_UPDATE_TIMESTAMP,
    TAB_A.LAST_UPDATE_USER
FROM
    T_COMN_MENU_COLUMN_LINK TAB_A
LEFT JOIN T_COMN_MENU TAB_B ON (TAB_A.MENU_ID = TAB_B.MENU_ID)
LEFT JOIN T_COMN_MENU_TABLE_LINK TAB_C ON (TAB_B.MENU_ID = TAB_C.MENU_ID)
LEFT JOIN T_COMN_MENU_GROUP TAB_D ON (TAB_B.MENU_GROUP_ID = TAB_D.MENU_GROUP_ID)
LEFT JOIN T_COMN_COLUMN_GROUP TAB_E ON (TAB_A.COL_GROUP_ID = TAB_E.COL_GROUP_ID)
WHERE TAB_A.COL_NAME = "DATA_JSON"
AND TAB_C.SHEET_TYPE = 3
AND TAB_C.VERTICAL = 0
AND TAB_C.SUBSTITUTION_VALUE_LINK_FLAG = 1
AND (TAB_A.COLUMN_CLASS != 7 AND TAB_A.COLUMN_CLASS != 11 AND TAB_A.COLUMN_CLASS != 21)
AND TAB_A.DISUSE_FLAG = 0
AND TAB_B.DISUSE_FLAG = 0
AND TAB_C.DISUSE_FLAG = 0
AND TAB_D.DISUSE_FLAG = 0
AND TAB_E.DISUSE_FLAG = 0
;
CREATE OR REPLACE VIEW V_MENU_PARAMETER_SHEET_REFERENCE_ITEM_JNL AS
SELECT
    TAB_A.JOURNAL_SEQ_NO,
    TAB_A.JOURNAL_REG_DATETIME,
    TAB_A.JOURNAL_ACTION_CLASS,
    TAB_A.COLUMN_DEFINITION_ID,
    TAB_B.MENU_GROUP_ID,
    TAB_D.MENU_GROUP_NAME_JA,
    TAB_D.MENU_GROUP_NAME_EN,
    TAB_B.MENU_ID,
    TAB_A.COLUMN_NAME_REST,
    TAB_B.MENU_NAME_JA,
    TAB_B.MENU_NAME_EN,
    TAB_C.TABLE_NAME,
    TAB_C.VIEW_NAME,
    TAB_A.COLUMN_CLASS,
    TAB_A.COLUMN_NAME_JA,
    TAB_A.COLUMN_NAME_EN,
    TAB_A.COL_GROUP_ID,
    TAB_E.FULL_COL_GROUP_NAME_JA,
    TAB_E.FULL_COL_GROUP_NAME_EN,
    CASE WHEN TAB_E.FULL_COL_GROUP_NAME_JA IS NULL THEN CONCAT(TAB_D.MENU_GROUP_NAME_JA,':',TAB_B.MENU_NAME_JA,':',TAB_A.COLUMN_NAME_JA) ELSE CONCAT(TAB_D.MENU_GROUP_NAME_JA,':',TAB_B.MENU_NAME_JA,':',TAB_E.FULL_COL_GROUP_NAME_JA,'/',TAB_A.COLUMN_NAME_JA) END AS SELECT_FULL_NAME_JA,
    CASE WHEN TAB_E.FULL_COL_GROUP_NAME_EN IS NULL THEN CONCAT(TAB_D.MENU_GROUP_NAME_EN,':',TAB_B.MENU_NAME_EN,':',TAB_A.COLUMN_NAME_EN) ELSE CONCAT(TAB_D.MENU_GROUP_NAME_EN,':',TAB_B.MENU_NAME_EN,':',TAB_E.FULL_COL_GROUP_NAME_EN,'/',TAB_A.COLUMN_NAME_EN) END AS SELECT_FULL_NAME_EN,
    TAB_A.COLUMN_DISP_SEQ,
    TAB_A.NOTE,
    TAB_A.DISUSE_FLAG,
    TAB_A.LAST_UPDATE_TIMESTAMP,
    TAB_A.LAST_UPDATE_USER
FROM
    T_COMN_MENU_COLUMN_LINK_JNL TAB_A
LEFT JOIN T_COMN_MENU_JNL TAB_B ON (TAB_A.MENU_ID = TAB_B.MENU_ID)
LEFT JOIN T_COMN_MENU_TABLE_LINK_JNL TAB_C ON (TAB_B.MENU_ID = TAB_C.MENU_ID)
LEFT JOIN T_COMN_MENU_GROUP_JNL TAB_D ON (TAB_B.MENU_GROUP_ID = TAB_D.MENU_GROUP_ID)
LEFT JOIN T_COMN_COLUMN_GROUP_JNL TAB_E ON (TAB_A.COL_GROUP_ID = TAB_E.COL_GROUP_ID)
WHERE TAB_A.COL_NAME = "DATA_JSON"
AND TAB_C.SHEET_TYPE = 3
AND TAB_C.VERTICAL = 0
AND TAB_C.SUBSTITUTION_VALUE_LINK_FLAG = 1
AND (TAB_A.COLUMN_CLASS != 7 AND TAB_A.COLUMN_CLASS != 11 AND TAB_A.COLUMN_CLASS != 21)
AND TAB_A.DISUSE_FLAG = 0
AND TAB_B.DISUSE_FLAG = 0
AND TAB_C.DISUSE_FLAG = 0
AND TAB_D.DISUSE_FLAG = 0
AND TAB_E.DISUSE_FLAG = 0
;

