cd ita_ag_oase
poetry update
cd ../ita_api_admin
poetry update
cd ../ita_api_oase_receiver
poetry update
cd ../ita_api_organization
poetry update
cd ../ita_by_ansible_execute
poetry update
cd ../ita_by_ansible_legacy_role_vars_listup
poetry update
cd ../ita_by_ansible_legacy_vars_listup
poetry update
cd ../ita_by_ansible_pioneer_vars_listup
poetry update
cd ../ita_by_ansible_towermaster_sync
poetry update
cd ../ita_by_cicd_for_iac
poetry update
cd ../ita_by_collector
poetry update
cd ../ita_by_conductor_regularly
poetry update
cd ../ita_by_conductor_synchronize
poetry update
cd ../ita_by_excel_export_import
poetry update
cd ../ita_by_execinstance_dataautoclean
poetry update
cd ../ita_by_file_autoclean
poetry update
cd ../ita_by_hostgroup_split
poetry update
cd ../ita_by_menu_create
poetry update
cd ../ita_by_menu_export_import
poetry update
cd ../ita_by_oase_conclusion
poetry update
cd ../ita_by_terraform_cli_execute
poetry update
cd ../ita_by_terraform_cli_vars_listup
poetry update
cd ../ita_by_terraform_cloud_ep_execute
poetry update
cd ../ita_by_terraform_cloud_ep_vars_listup
poetry update
cd ../ita_migration
poetry update
