-- ------------------------------------------------------------
-- ▼TABLE MASTER UPDATE START
-- ------------------------------------------------------------
-- 20108　管理対象外変数一覧:　item レコード追加
INSERT INTO T_ANSC_UNMANAGED_VARLIST (ROW_ID,VAR_NAME,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(15,'item','ansibleマジック変数','0',_____DATE_____,1);
INSERT INTO T_ANSC_UNMANAGED_VARLIST_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,ROW_ID,VAR_NAME,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(15,_____DATE_____,'INSERT',15,'item','ansibleマジック変数','0',_____DATE_____,1);

-- 20102 インターフェース情報: REST APIタイムアウト値(単位 秒)　追加
DELETE FROM T_COMN_MENU_COLUMN_LINK     WHERE COLUMN_DEFINITION_ID in ("2010209",
                                                                       "2010210",
                                                                       "2010211",
                                                                       "2010212",
                                                                       "2010213",
                                                                       "2010214",
                                                                       "2010215",
                                                                       "2010216",
                                                                       "2010217",
                                                                       "2010218",
                                                                       "2010219",
                                                                       "2010220",
                                                                       "2010221",
                                                                       "2010222",
                                                                       "2010223",
                                                                       "2010224",
                                                                       "2010225",
                                                                       "2010226",
                                                                       "2010227",
                                                                       "2010228");
DELETE FROM T_COMN_MENU_COLUMN_LINK_JNL WHERE COLUMN_DEFINITION_ID in ("2010209",
                                                                       "2010210",
                                                                       "2010211",
                                                                       "2010212",
                                                                       "2010213",
                                                                       "2010214",
                                                                       "2010215",
                                                                       "2010216",
                                                                       "2010217",
                                                                       "2010218",
                                                                       "2010219",
                                                                       "2010220",
                                                                       "2010221",
                                                                       "2010222",
                                                                       "2010223",
                                                                       "2010224",
                                                                       "2010225",
                                                                       "2010226",
                                                                       "2010227",
                                                                       "2010228");
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2010209','20102','REST APIタイムアウト値(単位 秒)','Restapi timeout value (seconds)','restapi_timeout_value','2010202','3',90,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'ANSTWR_REST_TIMEOUT',NULL,'0','1','1','0','0','1','0','60','{
"int_min": 60,
"int_max": 3600
}',NULL,NULL,NULL,'Ansible Automation ControllerへのRestAPI発行時のタイムアウト値を60～3600の範囲で入力します。
通常は60秒程度が推奨値です。
空白の場合は、デフォルト値(60)が使用します。','Enter a timeout value between 60 and 3600 for issuing RestAPI to the Ansible Automation Controller.
60 seconds is the recommended value.
If blank, the default value (60) will be used.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2010209,_____DATE_____,'INSERT','2010209','20102','REST APIタイムアウト値(単位 秒)','Restapi timeout value (seconds)','restapi_timeout_value','2010202','3',90,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'ANSTWR_REST_TIMEOUT',NULL,'0','1','1','0','0','1','0','60','{
"int_min": 60,
"int_max": 3600
}',NULL,NULL,NULL,'Ansible Automation ControllerへのRestAPI発行時のタイムアウト値を60～3600の範囲で入力します。
通常は60秒程度が推奨値です。
空白の場合は、デフォルト値(60)が使用します。','Enter a timeout value between 60 and 3600 for issuing RestAPI to the Ansible Automation Controller.
60 seconds is the recommended value.
If blank, the default value (60) will be used.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2010210','20102','Address','Address','proxy_address','2010203','1',100,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'ANSIBLE_PROXY_ADDRESS',NULL,'0','1','1','0','0','1','0',NULL,'{
"min_length": 0,
"max_length": 255
}',NULL,NULL,NULL,'Proxyサーバのアドレス','Proxy server address',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2010210,_____DATE_____,'INSERT','2010210','20102','Address','Address','proxy_address','2010203','1',100,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'ANSIBLE_PROXY_ADDRESS',NULL,'0','1','1','0','0','1','0',NULL,'{
"min_length": 0,
"max_length": 255
}',NULL,NULL,NULL,'Proxyサーバのアドレス','Proxy server address',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2010211','20102','Port','Port','proxy_port','2010203','3',110,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'ANSIBLE_PROXY_PORT',NULL,'0','1','1','0','0','1','0',NULL,'{
"int_min": 0,
"int_max": 65535
}',NULL,NULL,NULL,'Proxyサーバのポート','Proxy server port',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2010211,_____DATE_____,'INSERT','2010211','20102','Port','Port','proxy_port','2010203','3',110,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'ANSIBLE_PROXY_PORT',NULL,'0','1','1','0','0','1','0',NULL,'{
"int_min": 0,
"int_max": 65535
}',NULL,NULL,NULL,'Proxyサーバのポート','Proxy server port',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2010212','20102','Ansible-vaultパスワード','Ansible-vault password','ansible_vault_password',NULL,'8',120,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'ANSIBLE_VAULT_PASSWORD',NULL,'0','1','1','0','0','1','0',NULL,'{
"min_length": 0,
"max_length": 64
}',NULL,NULL,NULL,'ansible-vaultコマンドで変数の具体値を暗号化する場合のパスワードを入力します。
空白の場合は、デフォルト値が使用します。
[最大長]64バイト','Enter the password when encrypting the concrete value of the variable with ansible-vault command.
If blank, the default value will be used.
[Maximum length] 64 bytes',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2010212,_____DATE_____,'INSERT','2010212','20102','Ansible-vaultパスワード','Ansible-vault password','ansible_vault_password',NULL,'8',120,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'ANSIBLE_VAULT_PASSWORD',NULL,'0','1','1','0','0','1','0',NULL,'{
"min_length": 0,
"max_length": 64
}',NULL,NULL,NULL,'ansible-vaultコマンドで変数の具体値を暗号化する場合のパスワードを入力します。
空白の場合は、デフォルト値が使用します。
[最大長]64バイト','Enter the password when encrypting the concrete value of the variable with ansible-vault command.
If blank, the default value will be used.
[Maximum length] 64 bytes',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2010213','20102','Ansible-Coreインストールパス','Ansible-Core install path','ansible_core_install_path',NULL,'1',130,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'ANSIBLE_CORE_PATH',NULL,'0','2','0','0','1','1','0',NULL,'{
"min_length": 0,
"max_length": 255
}',NULL,NULL,NULL,'Ansible-Coreインストールパス','Ansible-Core install path',NULL,'1',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2010213,_____DATE_____,'INSERT','2010213','20102','Ansible-Coreインストールパス','Ansible-Core install path','ansible_core_install_path',NULL,'1',130,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'ANSIBLE_CORE_PATH',NULL,'0','2','0','0','1','1','0',NULL,'{
"min_length": 0,
"max_length": 255
}',NULL,NULL,NULL,'Ansible-Coreインストールパス','Ansible-Core install path',NULL,'1',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2010214','20102','ホスト名','Host name','host_name','2010204','1',140,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'ANS_GIT_HOSTNAME',NULL,'0','2','0','0','0','1','0',NULL,'{
"min_length": 0,
"max_length": 255
}',NULL,NULL,NULL,'Ansible Automation Controllerから連携先のGitリポジトリへsshプロトコルでログインする為のホスト名(またはIPアドレス)を入力します。
Ansible driverのバックヤード機能がインストールされているホストにAnsible Automation Controllerと連携するGitリポジトリが作成されます。
実行エンジンがAnsible Automation Controllerの場合に必須入力です。','Input the Host name (or IP Address) needed in order to login to the Git repository from the Ansible Automation Controller with ssh protocol.
A Git repository linked with the Ansible Automation Controller will be created to the Host installed by the Ansible backyard function.
This item is required if the selected Execution engine is \"Ansible Automation Controller\".',NULL,'1',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2010214,_____DATE_____,'INSERT','2010214','20102','ホスト名','Host name','host_name','2010204','1',140,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'ANS_GIT_HOSTNAME',NULL,'0','2','0','0','0','1','0',NULL,'{
"min_length": 0,
"max_length": 255
}',NULL,NULL,NULL,'Ansible Automation Controllerから連携先のGitリポジトリへsshプロトコルでログインする為のホスト名(またはIPアドレス)を入力します。
Ansible driverのバックヤード機能がインストールされているホストにAnsible Automation Controllerと連携するGitリポジトリが作成されます。
実行エンジンがAnsible Automation Controllerの場合に必須入力です。','Input the Host name (or IP Address) needed in order to login to the Git repository from the Ansible Automation Controller with ssh protocol.
A Git repository linked with the Ansible Automation Controller will be created to the Host installed by the Ansible backyard function.
This item is required if the selected Execution engine is \"Ansible Automation Controller\".',NULL,'1',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2010215','20102','ユーザ','User','user','2010205','1',150,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'ANS_GIT_USER',NULL,'0','2','0','0','0','1','0',NULL,'{
"min_length": 0,
"max_length": 255
}',NULL,NULL,NULL,'Ansible Automation Controllerから連携先のGitリポジトリへsshプロトコルで接続する為のユーザを入力します。
実行エンジンがAnsible Automation Controllerの場合に必須入力です。','Input the User needed in order to login to the Git repository from the Ansible Automation Controller with ssh protocol.
This item is required if the selected Execution engine is \"Ansible Automation Controller\".',NULL,'1',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2010215,_____DATE_____,'INSERT','2010215','20102','ユーザ','User','user','2010205','1',150,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'ANS_GIT_USER',NULL,'0','2','0','0','0','1','0',NULL,'{
"min_length": 0,
"max_length": 255
}',NULL,NULL,NULL,'Ansible Automation Controllerから連携先のGitリポジトリへsshプロトコルで接続する為のユーザを入力します。
実行エンジンがAnsible Automation Controllerの場合に必須入力です。','Input the User needed in order to login to the Git repository from the Ansible Automation Controller with ssh protocol.
This item is required if the selected Execution engine is \"Ansible Automation Controller\".',NULL,'1',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2010216','20102','ssh秘密鍵ファイル','ssh secret key file','ssh_private_key_file','2010205','20',160,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'ANS_GIT_SSH_KEY_FILE',NULL,'0','2','0','0','0','1','0',NULL,'{
"upload_max_size": 104857600
}',NULL,NULL,NULL,'Ansible Automation Controllerから連携先のGitリポジトリへsshプロトコルの鍵認証で接続する為の公開鍵ファイルを入力します。
実行エンジンがAnsible Automation Controllerの場合に必須入力です。','Input the public key  needed in order to login to the Git repository from the Ansible Automation Controller with ssh protocol.
This item is required if the selected Execution engine is \"Ansible Automation Controller\".',NULL,'1',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2010216,_____DATE_____,'INSERT','2010216','20102','ssh秘密鍵ファイル','ssh secret key file','ssh_private_key_file','2010205','20',160,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'ANS_GIT_SSH_KEY_FILE',NULL,'0','2','0','0','0','1','0',NULL,'{
"upload_max_size": 104857600
}',NULL,NULL,NULL,'Ansible Automation Controllerから連携先のGitリポジトリへsshプロトコルの鍵認証で接続する為の公開鍵ファイルを入力します。
実行エンジンがAnsible Automation Controllerの場合に必須入力です。','Input the public key  needed in order to login to the Git repository from the Ansible Automation Controller with ssh protocol.
This item is required if the selected Execution engine is \"Ansible Automation Controller\".',NULL,'1',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2010217','20102','パスフレーズ','Passphrase','passphrase','2010205','8',170,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'ANS_GIT_SSH_KEY_FILE_PASS',NULL,'0','2','0','0','0','1','0',NULL,NULL,NULL,NULL,NULL,'ssh秘密鍵ファイルに設定されているパスフレーズを入力します。','Input the passphrase set to the ssh secret key file.',NULL,'1',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2010217,_____DATE_____,'INSERT','2010217','20102','パスフレーズ','Passphrase','passphrase','2010205','8',170,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'ANS_GIT_SSH_KEY_FILE_PASS',NULL,'0','2','0','0','0','1','0',NULL,NULL,NULL,NULL,NULL,'ssh秘密鍵ファイルに設定されているパスフレーズを入力します。','Input the passphrase set to the ssh secret key file.',NULL,'1',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2010218','20102','データリレイストレージパス(ITA)','Data relay storage path (ITA)','ita_data_relay_storage_path',NULL,'1',180,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'ANSIBLE_STORAGE_PATH_LNX',NULL,'0','2','0','0','0','1','0',NULL,'{
"min_length": 1,
"max_length": 255
}',NULL,NULL,NULL,'ITAサーバとの共有ディレクトリです。','This is a shared directory with ITA server.',NULL,'1',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2010218,_____DATE_____,'INSERT','2010218','20102','データリレイストレージパス(ITA)','Data relay storage path (ITA)','ita_data_relay_storage_path',NULL,'1',180,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'ANSIBLE_STORAGE_PATH_LNX',NULL,'0','2','0','0','0','1','0',NULL,'{
"min_length": 1,
"max_length": 255
}',NULL,NULL,NULL,'ITAサーバとの共有ディレクトリです。','This is a shared directory with ITA server.',NULL,'1',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2010219','20102','データリレイストレージパス(Ansible)','Data relay storage path (Ansible)','ansible_data_relay_storage_path',NULL,'1',190,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'ANSIBLE_STORAGE_PATH_ANS',NULL,'0','2','0','0','0','1','0',NULL,'{
"min_length": 1,
"max_length": 255
}',NULL,NULL,NULL,'Ansibleサーバとの共有ディレクトリです。
実行エンジンがAnsible Core以外では使用しない情報です。','This is the Ansible server shared directory.
This information is not used if the execution engine is not set to Ansible Core.',NULL,'1',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2010219,_____DATE_____,'INSERT','2010219','20102','データリレイストレージパス(Ansible)','Data relay storage path (Ansible)','ansible_data_relay_storage_path',NULL,'1',190,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'ANSIBLE_STORAGE_PATH_ANS',NULL,'0','2','0','0','0','1','0',NULL,'{
"min_length": 1,
"max_length": 255
}',NULL,NULL,NULL,'Ansibleサーバとの共有ディレクトリです。
実行エンジンがAnsible Core以外では使用しない情報です。','This is the Ansible server shared directory.
This information is not used if the execution engine is not set to Ansible Core.',NULL,'1',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2010220','20102','Conductorインスタンスデータリレイストレージパス(Ansible)','Conductor instance data relay storage path(Ansible)','conductor_instance_data relay_storage_path',NULL,'1',200,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'CONDUCTOR_STORAGE_PATH_ANS',NULL,'0','2','0','0','0','1','0',NULL,'{
"min_length": 1,
"max_length": 255
}',NULL,NULL,NULL,'Conductorインスタンスの各Movementが共有するディレクトリをAnsibleサーバで共有する為のパスです。
実行エンジンがAnsible Core以外では使用しない情報です。','This path is used to share the Conductor instance Movements\' shared directory within Ansible Server.
This information is not used if the execution engine is not set to Ansible Core.',NULL,'1',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2010220,_____DATE_____,'INSERT','2010220','20102','Conductorインスタンスデータリレイストレージパス(Ansible)','Conductor instance data relay storage path(Ansible)','conductor_instance_data relay_storage_path',NULL,'1',200,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'CONDUCTOR_STORAGE_PATH_ANS',NULL,'0','2','0','0','0','1','0',NULL,'{
"min_length": 1,
"max_length": 255
}',NULL,NULL,NULL,'Conductorインスタンスの各Movementが共有するディレクトリをAnsibleサーバで共有する為のパスです。
実行エンジンがAnsible Core以外では使用しない情報です。','This path is used to share the Conductor instance Movements\' shared directory within Ansible Server.
This information is not used if the execution engine is not set to Ansible Core.',NULL,'1',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2010221','20102','オプションパラメータ','Optional parameter','optional_parameter',NULL,'1',210,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'ANSIBLE_EXEC_OPTIONS',NULL,'0','1','1','0','0','1','0',NULL,'{
"min_length": 0,
"max_length": 4000
}',NULL,NULL,NULL,'Movement共通のansible-playbookコマンドのオプションパラメータを設定します。
Movement固有のオプションパラメータはMovement一覧で設定します。
Ansible:
  ansible-playbookコマンドのパラメータを設定します。
　-i オプションはITAが設定します。
Ansible Automation Controller:
　以下のパラメータが設定できます。
　　-verbosity
　　-f FORKS,--forks=FORKS
　　-l SUBSET,--limit=SUBSET
　　-e EXTRA_VARS,--extra-vars=EXTRA_VARS
        EXTRA_VARS:  変数名=具体値 変数名=具体値 .....
　　-t TAGS,--tags=TAGS
　　-b,--become
　　-D,--diff
　　--skip-tags=SKIP_TAGS
　　--start-at-task=START_AT_TASK
　以下はAnsible Automation Controller独自のパラメータです。
　　-ufc,--use_fact_cache　　　ファクトのキャッシュの使用
　　-as,--allow_simultaneous　 同時実行ジョブの有効化
　　-jsc,--job_slice_count=　　JOB SLICING
　詳細はAnsible利用手順マニュアルを参照して下さい。','Optional parameter of ansible-playbook command.
Movement-specific optional parameters are set in the Movement list.
Ansible:
　Set the parameters of nible-playbook command.
　ITA sets -i option.

Ansible Automation Controller:
　Options that can be set
　　-verbosity
　　-f FORKS,--forks=FORKS
　　-l SUBSET,--limit=SUBSET
　　-e EXTRA_VARS,--extra-vars=EXTRA_VARS
　　-t TAGS,--tags=TAGS
　　-b,--become
　　-D,--diff
　　--skip-tags=SKIP_TAGS
　　--start-at-task=START_AT_TASK
　Ansible Automation Controller only parameters
　　-ufc,--use_fact_cache　　　
　　-as,--allow_simultaneous　
　　-jsc,--job_slice_count
　Refer to the Ansible User Manual for details.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2010221,_____DATE_____,'INSERT','2010221','20102','オプションパラメータ','Optional parameter','optional_parameter',NULL,'1',210,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'ANSIBLE_EXEC_OPTIONS',NULL,'0','1','1','0','0','1','0',NULL,'{
"min_length": 0,
"max_length": 4000
}',NULL,NULL,NULL,'Movement共通のansible-playbookコマンドのオプションパラメータを設定します。
Movement固有のオプションパラメータはMovement一覧で設定します。
Ansible:
  ansible-playbookコマンドのパラメータを設定します。
　-i オプションはITAが設定します。
Ansible Automation Controller:
　以下のパラメータが設定できます。
　　-verbosity
　　-f FORKS,--forks=FORKS
　　-l SUBSET,--limit=SUBSET
　　-e EXTRA_VARS,--extra-vars=EXTRA_VARS
        EXTRA_VARS:  変数名=具体値 変数名=具体値 .....
　　-t TAGS,--tags=TAGS
　　-b,--become
　　-D,--diff
　　--skip-tags=SKIP_TAGS
　　--start-at-task=START_AT_TASK
　以下はAnsible Automation Controller独自のパラメータです。
　　-ufc,--use_fact_cache　　　ファクトのキャッシュの使用
　　-as,--allow_simultaneous　 同時実行ジョブの有効化
　　-jsc,--job_slice_count=　　JOB SLICING
　詳細はAnsible利用手順マニュアルを参照して下さい。','Optional parameter of ansible-playbook command.
Movement-specific optional parameters are set in the Movement list.
Ansible:
　Set the parameters of nible-playbook command.
　ITA sets -i option.

Ansible Automation Controller:
　Options that can be set
　　-verbosity
　　-f FORKS,--forks=FORKS
　　-l SUBSET,--limit=SUBSET
　　-e EXTRA_VARS,--extra-vars=EXTRA_VARS
　　-t TAGS,--tags=TAGS
　　-b,--become
　　-D,--diff
　　--skip-tags=SKIP_TAGS
　　--start-at-task=START_AT_TASK
　Ansible Automation Controller only parameters
　　-ufc,--use_fact_cache　　　
　　-as,--allow_simultaneous　
　　-jsc,--job_slice_count
　Refer to the Ansible User Manual for details.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2010222','20102','NULL連携','NULL link','null_link',NULL,'7',220,'T_COMN_BOOLEAN_FLAG','FLAG_ID','FLAG_NAME',NULL,'0',NULL,NULL,NULL,NULL,'NULL_DATA_HANDLING_FLG',NULL,'0','1','1','0','1','1','0',NULL,NULL,NULL,NULL,NULL,'代入値自動登録設定でパラメータシートの具体値がNULL(空白)の場合に、代入値管理への登録を有効にするかのデフォルトを設定します。
有効:NULLデータを登録する。
無効:NULLデータは登録しない。','If specific value of parameter sheet is NULL in Substitut val-auto-reg, validates registration in Substitution value list or set default.
valid: Register NULL data.
Invalid: Do not register null data.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2010222,_____DATE_____,'INSERT','2010222','20102','NULL連携','NULL link','null_link',NULL,'7',220,'T_COMN_BOOLEAN_FLAG','FLAG_ID','FLAG_NAME',NULL,'0',NULL,NULL,NULL,NULL,'NULL_DATA_HANDLING_FLG',NULL,'0','1','1','0','1','1','0',NULL,NULL,NULL,NULL,NULL,'代入値自動登録設定でパラメータシートの具体値がNULL(空白)の場合に、代入値管理への登録を有効にするかのデフォルトを設定します。
有効:NULLデータを登録する。
無効:NULLデータは登録しない。','If specific value of parameter sheet is NULL in Substitut val-auto-reg, validates registration in Substitution value list or set default.
valid: Register NULL data.
Invalid: Do not register null data.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2010223','20102','並列実行数','Number of parallel executions','number_of_parallel_executions',NULL,'3',230,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'ANSIBLE_NUM_PARALLEL_EXEC',NULL,'0','0','1','0','1','1','0',NULL,'{
"int_min": 1,
"int_max": 1000
}',NULL,NULL,NULL,'同時に実行できるMovement(Legacy/Pioneer/Legacy-Role)の最大数です。','The maximum number of Movements (Legacy / Pioneer / Legacy-Role) that can be executed simultaneously.',NULL,'1',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2010223,_____DATE_____,'INSERT','2010223','20102','並列実行数','Number of parallel executions','number_of_parallel_executions',NULL,'3',230,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'ANSIBLE_NUM_PARALLEL_EXEC',NULL,'0','0','1','0','1','1','0',NULL,'{
"int_min": 1,
"int_max": 1000
}',NULL,NULL,NULL,'同時に実行できるMovement(Legacy/Pioneer/Legacy-Role)の最大数です。','The maximum number of Movements (Legacy / Pioneer / Legacy-Role) that can be executed simultaneously.',NULL,'1',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2010224','20102','状態監視周期(単位ミリ秒)','Status monitoring cycle (milliseconds)','status_monitoring_cycle',NULL,'3',240,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'ANSIBLE_REFRESH_INTERVAL',NULL,'0','1','1','0','1','1','0',NULL,'{
"int_min": 1000,
"int_max": 2147483647
}',NULL,NULL,NULL,'作業実行時の作業ログをリフレッシュする間隔です。
環境毎にチューニングを要しますが、通常は3000ミリ秒程度が推奨値です。','It is interval to refresh execution log when performing an execution.
 While tuning is required for each environment, recommended value is 3000 milliseconds.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2010224,_____DATE_____,'INSERT','2010224','20102','状態監視周期(単位ミリ秒)','Status monitoring cycle (milliseconds)','status_monitoring_cycle',NULL,'3',240,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'ANSIBLE_REFRESH_INTERVAL',NULL,'0','1','1','0','1','1','0',NULL,'{
"int_min": 1000,
"int_max": 2147483647
}',NULL,NULL,NULL,'作業実行時の作業ログをリフレッシュする間隔です。
環境毎にチューニングを要しますが、通常は3000ミリ秒程度が推奨値です。','It is interval to refresh execution log when performing an execution.
 While tuning is required for each environment, recommended value is 3000 milliseconds.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2010225','20102','進行状態表示行数','Number of rows to display progress status','number_of_rows_to_display_progress_status',NULL,'3',250,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'ANSIBLE_TAILLOG_LINES',NULL,'0','1','1','0','1','1','0',NULL,'{
"int_min": 0,
"int_max": 2147483647
}',NULL,NULL,NULL,'作業実行時の[作業状態確認]メニューの[進行状況]のログ出力行数です。
ステータスが[未実行]、[準備中]、[実行中]、[実行中(遅延)]の場合、指定した行数でログを出力します。
ステータスが[完了]、[完了(異常)]、[想定外エラー]、[緊急停止]、[未実行(予約)]、[予約取消]の場合、指定した行数ではなくすべてのログを出力します。
環境毎にチューニングを要しますが、通常は1000行程度が推奨値です。','The number of lines that will be output to the [Progress status] log in the [Check operation status] menu when executing an operation.
The log will only output the specified number of lines if the status displays [Not yet executed], [Preparing], [Executing] or [Executing (Delayed)].
If the status displays [Completed], [Completed(error)], [Unexpected error], [Emergency stop], [Not yet executed(reserved)] or [Reservation deleted], the log will ignore the set number and output the whole log.
While this number should be tuned depending on the environment, the recommended value is 1000 lines.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2010225,_____DATE_____,'INSERT','2010225','20102','進行状態表示行数','Number of rows to display progress status','number_of_rows_to_display_progress_status',NULL,'3',250,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'ANSIBLE_TAILLOG_LINES',NULL,'0','1','1','0','1','1','0',NULL,'{
"int_min": 0,
"int_max": 2147483647
}',NULL,NULL,NULL,'作業実行時の[作業状態確認]メニューの[進行状況]のログ出力行数です。
ステータスが[未実行]、[準備中]、[実行中]、[実行中(遅延)]の場合、指定した行数でログを出力します。
ステータスが[完了]、[完了(異常)]、[想定外エラー]、[緊急停止]、[未実行(予約)]、[予約取消]の場合、指定した行数ではなくすべてのログを出力します。
環境毎にチューニングを要しますが、通常は1000行程度が推奨値です。','The number of lines that will be output to the [Progress status] log in the [Check operation status] menu when executing an operation.
The log will only output the specified number of lines if the status displays [Not yet executed], [Preparing], [Executing] or [Executing (Delayed)].
If the status displays [Completed], [Completed(error)], [Unexpected error], [Emergency stop], [Not yet executed(reserved)] or [Reservation deleted], the log will ignore the set number and output the whole log.
While this number should be tuned depending on the environment, the recommended value is 1000 lines.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2010226','20102','備考','Remarks','remarks',NULL,'12',260,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'NOTE',NULL,'0','1','1','0','0','1','0',NULL,'{
"min_length": 0,
"max_length": 4000
}',NULL,NULL,NULL,'自由記述欄。レコードの廃止・復活時にも記載可能。','Comments section. Can comment when removing or restoring records.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2010226,_____DATE_____,'INSERT','2010226','20102','備考','Remarks','remarks',NULL,'12',260,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'NOTE',NULL,'0','1','1','0','0','1','0',NULL,'{
"min_length": 0,
"max_length": 4000
}',NULL,NULL,NULL,'自由記述欄。レコードの廃止・復活時にも記載可能。','Comments section. Can comment when removing or restoring records.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2010227','20102','廃止フラグ','Discard','discard',NULL,'1',270,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'DISUSE_FLAG',NULL,'1','1','1','0','1','1','0',NULL,NULL,NULL,NULL,NULL,'廃止フラグ。復活以外のオペレーションは不可','Discard flag. Cannot do operation other than restore.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2010227,_____DATE_____,'INSERT','2010227','20102','廃止フラグ','Discard','discard',NULL,'1',270,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'DISUSE_FLAG',NULL,'1','1','1','0','1','1','0',NULL,NULL,NULL,NULL,NULL,'廃止フラグ。復活以外のオペレーションは不可','Discard flag. Cannot do operation other than restore.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2010228','20102','最終更新日時','Last update date/time','last_update_date_time',NULL,'13',280,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'LAST_UPDATE_TIMESTAMP',NULL,'1','0','1','0','1','1','0',NULL,NULL,NULL,NULL,NULL,'レコードの最終更新日。更新可否判定に使用。自動登録のため編集不可。','Last update date of record. Useful for judging the possibility of an update. Cannot edit because of auto-numbering.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2010228,_____DATE_____,'INSERT','2010228','20102','最終更新日時','Last update date/time','last_update_date_time',NULL,'13',280,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'LAST_UPDATE_TIMESTAMP',NULL,'1','0','1','0','1','1','0',NULL,NULL,NULL,NULL,NULL,'レコードの最終更新日。更新可否判定に使用。自動登録のため編集不可。','Last update date of record. Useful for judging the possibility of an update. Cannot edit because of auto-numbering.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2010229','20102','最終更新者','Last updated by','last_updated_user',NULL,'14',290,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'LAST_UPDATE_USER',NULL,'1','0','1','0','1','1','0',NULL,NULL,NULL,NULL,NULL,'更新者。ログインユーザのIDが自動的に登録される。編集不可。','Updated by. Login user ID is automatically registered. Cannot edit.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2010229,_____DATE_____,'INSERT','2010229','20102','最終更新者','Last updated by','last_updated_user',NULL,'14',290,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'LAST_UPDATE_USER',NULL,'1','0','1','0','1','1','0',NULL,NULL,NULL,NULL,NULL,'更新者。ログインユーザのIDが自動的に登録される。編集不可。','Updated by. Login user ID is automatically registered. Cannot edit.',NULL,'0',_____DATE_____,1);

-- popの有効/無効の記述を True/Falseに変更　追加
DELETE FROM T_COMN_MENU_COLUMN_LINK     WHERE COLUMN_DEFINITION_ID in ("2010222",
                                                                       "2020509",
                                                                       "2030709",
                                                                       "2040710");
DELETE FROM T_COMN_MENU_COLUMN_LINK_JNL WHERE COLUMN_DEFINITION_ID in ("2010222",
                                                                       "2020509",
                                                                       "2030709",
                                                                       "2040710")
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2010222','20102','NULL連携','NULL link','null_link',NULL,'7',220,'T_COMN_BOOLEAN_FLAG','FLAG_ID','FLAG_NAME',NULL,'0',NULL,NULL,NULL,NULL,'NULL_DATA_HANDLING_FLG',NULL,'0','1','1','0','1','1','0',NULL,NULL,NULL,NULL,NULL,'代入値自動登録設定でパラメータシートの具体値がNULL(空白)の場合に、代入値管理への登録を有効にするかのデフォルトを設定します。
True:NULLデータを登録する。
False:NULLデータは登録しない。','If specific value of parameter sheet is NULL in Substitut val-auto-reg, validates registration in Substitution value list or set default.
True: Register NULL data.
False: Do not register null data.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2010222,_____DATE_____,'INSERT','2010222','20102','NULL連携','NULL link','null_link',NULL,'7',220,'T_COMN_BOOLEAN_FLAG','FLAG_ID','FLAG_NAME',NULL,'0',NULL,NULL,NULL,NULL,'NULL_DATA_HANDLING_FLG',NULL,'0','1','1','0','1','1','0',NULL,NULL,NULL,NULL,NULL,'代入値自動登録設定でパラメータシートの具体値がNULL(空白)の場合に、代入値管理への登録を有効にするかのデフォルトを設定します。
True:NULLデータを登録する。
False:NULLデータは登録しない。','If specific value of parameter sheet is NULL in Substitut val-auto-reg, validates registration in Substitution value list or set default.
True: Register NULL data.
False: Do not register null data.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2020509','20205','NULL連携','NULL link','null_link',NULL,'7',90,'T_COMN_BOOLEAN_FLAG','FLAG_ID','FLAG_NAME',NULL,'0',NULL,NULL,NULL,NULL,'NULL_DATA_HANDLING_FLG',NULL,'0','1','1','0','0','1','0',NULL,NULL,NULL,NULL,NULL,'パラメータシートの具体値がNULL(空白)の場合、代入値管理への登録を有効にするかを設定します。
空白:Ansible共通インターフェース情報のNULL連携に従う。
True:NULLデータを登録する。
False:NULLデータは登録しない。','If specific value of parameter sheet is NULL, set whether to enable Substitution value list registration.
Blank: Follow Null linkage of Ansible common interface information.
True: Register NULL data.
False: Do not register null data.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2020509,_____DATE_____,'INSERT','2020509','20205','NULL連携','NULL link','null_link',NULL,'7',90,'T_COMN_BOOLEAN_FLAG','FLAG_ID','FLAG_NAME',NULL,'0',NULL,NULL,NULL,NULL,'NULL_DATA_HANDLING_FLG',NULL,'0','1','1','0','0','1','0',NULL,NULL,NULL,NULL,NULL,'パラメータシートの具体値がNULL(空白)の場合、代入値管理への登録を有効にするかを設定します。
空白:Ansible共通インターフェース情報のNULL連携に従う。
True:NULLデータを登録する。
False:NULLデータは登録しない。','If specific value of parameter sheet is NULL, set whether to enable Substitution value list registration.
Blank: Follow Null linkage of Ansible common interface information.
True: Register NULL data.
False: Do not register null data.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2030709','20307','NULL連携','NULL link','null_link',NULL,'7',100,'T_COMN_BOOLEAN_FLAG','FLAG_ID','FLAG_NAME',NULL,'0',NULL,NULL,NULL,NULL,'NULL_DATA_HANDLING_FLG',NULL,'0','1','1','0','0','1','0',NULL,NULL,NULL,NULL,NULL,'パラメータシートの具体値がNULL(空白)の場合、代入値管理への登録を有効にするかを設定します。
空白:Ansible共通インターフェース情報のNULL連携に従う。
True:NULLデータを登録する。
False:NULLデータは登録しない。','If specific value of parameter sheet is NULL, set whether to enable Substitution value list registration.
Blank: Follow Null linkage of Ansible common interface information.
True: Register NULL data.
False: Do not register null data.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2030709,_____DATE_____,'INSERT','2030709','20307','NULL連携','NULL link','null_link',NULL,'7',100,'T_COMN_BOOLEAN_FLAG','FLAG_ID','FLAG_NAME',NULL,'0',NULL,NULL,NULL,NULL,'NULL_DATA_HANDLING_FLG',NULL,'0','1','1','0','0','1','0',NULL,NULL,NULL,NULL,NULL,'パラメータシートの具体値がNULL(空白)の場合、代入値管理への登録を有効にするかを設定します。
空白:Ansible共通インターフェース情報のNULL連携に従う。
True:NULLデータを登録する。
False:NULLデータは登録しない。','If specific value of parameter sheet is NULL, set whether to enable Substitution value list registration.
Blank: Follow Null linkage of Ansible common interface information.
True: Register NULL data.
False: Do not register null data.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2040710','20407','NULL連携','NULL link','null_link',NULL,'7',100,'T_COMN_BOOLEAN_FLAG','FLAG_ID','FLAG_NAME',NULL,'0',NULL,NULL,NULL,NULL,'NULL_DATA_HANDLING_FLG',NULL,'0','1','1','0','0','1','0',NULL,NULL,NULL,NULL,NULL,'パラメータシートの具体値がNULL(空白)の場合、代入値管理への登録を有効にするかを設定します。
空白:Ansible共通インターフェース情報のNULL連携に従う。
True:NULLデータを登録する。
False:NULLデータは登録しない。','If specific value of parameter sheet is NULL, set whether to enable Substitution value list registration.
Blank: Follow Null linkage of Ansible common interface information.
True: Register NULL data.
False: Do not register null data.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2040710,_____DATE_____,'INSERT','2040710','20407','NULL連携','NULL link','null_link',NULL,'7',100,'T_COMN_BOOLEAN_FLAG','FLAG_ID','FLAG_NAME',NULL,'0',NULL,NULL,NULL,NULL,'NULL_DATA_HANDLING_FLG',NULL,'0','1','1','0','0','1','0',NULL,NULL,NULL,NULL,NULL,'パラメータシートの具体値がNULL(空白)の場合、代入値管理への登録を有効にするかを設定します。
空白:Ansible共通インターフェース情報のNULL連携に従う。
True:NULLデータを登録する。
False:NULLデータは登録しない。','If specific value of parameter sheet is NULL, set whether to enable Substitution value list registration.
Blank: Follow Null linkage of Ansible common interface information.
True: Register NULL data.
False: Do not register null data.',NULL,'0',_____DATE_____,1);

-- ------------------------------------------------------------
-- ▲TABLE MASTER UPDATE END
-- ------------------------------------------------------------
