-- INSERT/UPDATE: -2.1.1
    -- T_COMN_MENU_COLUMN_LINK: UPDATE and INSERT

-- T_COMN_MENU_COLUMN_LINK: UPDATE and INSERT
UPDATE T_COMN_MENU_COLUMN_LINK SET REF_TABLE_NAME = 'V_COMPARE_MENU_COLUMN_PULLDOWN_1', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE COLUMN_DEFINITION_ID = '4010204';
UPDATE T_COMN_MENU_COLUMN_LINK_JNL SET REF_TABLE_NAME = 'V_COMPARE_MENU_COLUMN_PULLDOWN_1', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE COLUMN_DEFINITION_ID = '4010204';
UPDATE T_COMN_MENU_COLUMN_LINK SET REF_TABLE_NAME = 'V_COMPARE_MENU_COLUMN_PULLDOWN_2', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE COLUMN_DEFINITION_ID = '4010205';
UPDATE T_COMN_MENU_COLUMN_LINK_JNL SET REF_TABLE_NAME = 'V_COMPARE_MENU_COLUMN_PULLDOWN_2', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE COLUMN_DEFINITION_ID = '4010205';
