-- INSERT/UPDATE: -2.1.1
    -- T_COMN_MENU_COLUMN_LINK: UPDATE

-- T_COMN_MENU: UPDATE
UPDATE T_COMN_MENU_COLUMN_LINK SET REQUIRED_ITEM = '0', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE COLUMN_DEFINITION_ID = '7010303';
UPDATE T_COMN_MENU_COLUMN_LINK_JNL SET REQUIRED_ITEM = '0', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE COLUMN_DEFINITION_ID = '7010303';
