-- CREATE TABLE/VIEW: -2.1.1
    -- V_HGSP_SPLIT_TARGET_MENU
    -- V_HGSP_REGISTER_TARGET_MENU

-- 分割対象メニュープルダウン用
CREATE OR REPLACE VIEW V_HGSP_SPLIT_TARGET_MENU AS
SELECT
    TAB_A.*,
    TAB_C.MENU_GROUP_NAME_JA,
    TAB_C.MENU_GROUP_NAME_EN
FROM
    T_COMN_MENU TAB_A
LEFT JOIN T_COMN_MENU_TABLE_LINK TAB_B
    ON (TAB_A.MENU_ID = TAB_B.MENU_ID)
LEFT JOIN T_COMN_MENU_GROUP TAB_C
    ON (TAB_A.MENU_GROUP_ID = TAB_C.MENU_GROUP_ID)
WHERE
    ( TAB_B.SHEET_TYPE = 1  OR TAB_B.SHEET_TYPE = 3 OR TAB_B.SHEET_TYPE = 4)
AND TAB_A.DISUSE_FLAG = 0
AND TAB_B.DISUSE_FLAG = 0
AND TAB_B.SUBSTITUTION_VALUE_LINK_FLAG = 0
AND TAB_B.HOSTGROUP = 1
;


-- 登録対象メニュープルダウン用
CREATE OR REPLACE VIEW V_HGSP_REGISTER_TARGET_MENU AS
SELECT
    TAB_A.*,
    TAB_C.MENU_GROUP_NAME_JA,
    TAB_C.MENU_GROUP_NAME_EN
FROM
    T_COMN_MENU TAB_A
LEFT JOIN T_COMN_MENU_TABLE_LINK TAB_B
    ON (TAB_A.MENU_ID = TAB_B.MENU_ID)
LEFT JOIN T_COMN_MENU_GROUP TAB_C
    ON (TAB_A.MENU_GROUP_ID = TAB_C.MENU_GROUP_ID)
WHERE
    ( TAB_B.SHEET_TYPE = 1  OR TAB_B.SHEET_TYPE = 3 OR TAB_B.SHEET_TYPE = 4)
AND TAB_A.DISUSE_FLAG = 0
AND TAB_B.DISUSE_FLAG = 0
AND TAB_B.SUBSTITUTION_VALUE_LINK_FLAG = 1
AND TAB_B.HOSTGROUP = 1
;