-- CREATE TABLE/VIEW: -2.1.1
    -- V_COMN_OPERATION

-- オペレーション一覧ビュー
CREATE OR REPLACE VIEW V_COMN_OPERATION AS
SELECT
    OPERATION_ID,
    OPERATION_NAME,
    CONCAT(DATE_FORMAT( OPERATION_DATE, '%Y/%m/%d %H:%i' ),'_',OPERATION_NAME) OPERATION_DATE_NAME,
    CASE
        WHEN LAST_EXECUTE_TIMESTAMP IS NULL THEN OPERATION_DATE
        ELSE LAST_EXECUTE_TIMESTAMP
    END BASE_TIMESTAMP,
    OPERATION_DATE,
    DATE_FORMAT( OPERATION_DATE, '%Y/%m/%d %H:%i' ) OPERATION_DATE_DISP,
    LAST_EXECUTE_TIMESTAMP,
    ENVIRONMENT,
    LANGUAGE,
    NOTE,
    DISUSE_FLAG,
    LAST_UPDATE_TIMESTAMP,
    LAST_UPDATE_USER
FROM
    T_COMN_OPERATION
;
CREATE OR REPLACE VIEW V_COMN_OPERATION_JNL AS
SELECT
    JOURNAL_SEQ_NO,
    JOURNAL_REG_DATETIME,
    JOURNAL_ACTION_CLASS,
    OPERATION_ID,
    OPERATION_NAME,
    CONCAT(DATE_FORMAT( OPERATION_DATE, '%Y/%m/%d %H:%i' ),'_',OPERATION_NAME) OPERATION_DATE_NAME,
    CASE
        WHEN LAST_EXECUTE_TIMESTAMP IS NULL THEN OPERATION_DATE
        ELSE LAST_EXECUTE_TIMESTAMP
    END BASE_TIMESTAMP,
    OPERATION_DATE,
    DATE_FORMAT( OPERATION_DATE, '%Y/%m/%d %H:%i' ) OPERATION_DATE_DISP,
    LAST_EXECUTE_TIMESTAMP,
    ENVIRONMENT,
    LANGUAGE,
    NOTE,
    DISUSE_FLAG,
    LAST_UPDATE_TIMESTAMP,
    LAST_UPDATE_USER
FROM
    T_COMN_OPERATION_JNL
;
