-- INSERT/UPDATE: -2.1.1
    -- T_COMN_MENU_COLUMN_LINK: UPDATE and INSERT

-- T_COMN_MENU: UPDATE and INSERT
UPDATE T_COMN_MENU_COLUMN_LINK SET COLUMN_DISP_SEQ = '70', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE COLUMN_DEFINITION_ID = '1020106';
UPDATE T_COMN_MENU_COLUMN_LINK_JNL SET COLUMN_DISP_SEQ = '70', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE COLUMN_DEFINITION_ID = '1020106';
UPDATE T_COMN_MENU_COLUMN_LINK SET COLUMN_DISP_SEQ = '80', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE COLUMN_DEFINITION_ID = '1020107';
UPDATE T_COMN_MENU_COLUMN_LINK_JNL SET COLUMN_DISP_SEQ = '80', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE COLUMN_DEFINITION_ID = '1020107';
UPDATE T_COMN_MENU_COLUMN_LINK SET COLUMN_DISP_SEQ = '90', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE COLUMN_DEFINITION_ID = '1020108';
UPDATE T_COMN_MENU_COLUMN_LINK_JNL SET COLUMN_DISP_SEQ = '90', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE COLUMN_DEFINITION_ID = '1020108';
UPDATE T_COMN_MENU_COLUMN_LINK SET COLUMN_DISP_SEQ = '100', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE COLUMN_DEFINITION_ID = '1020109';
UPDATE T_COMN_MENU_COLUMN_LINK_JNL SET COLUMN_DISP_SEQ = '100', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE COLUMN_DEFINITION_ID = '1020109';

INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('1020110','10201','言語','Language','language',NULL,'1',60,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'LANGUAGE',NULL,'1','0','1','0','0','1','0',NULL,'{
"min_length": 0,
"max_length": 40
}',NULL,NULL,NULL,'自動登録のため編集不可。','Cannot be edited (auto-registration)',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(1020110,_____DATE_____,'INSERT','1020110','10201','言語','Language','language',NULL,'1',60,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'LANGUAGE',NULL,'1','0','1','0','0','1','0',NULL,'{
"min_length": 0,
"max_length": 40
}',NULL,NULL,NULL,'自動登録のため編集不可。','Cannot be edited (auto-registration)',NULL,'0',_____DATE_____,1);
