////////////////////////////////////////////////////////////////////////////////////////////////////
//
//   Exastro IT Automation / messageid_en.js
//
//   -----------------------------------------------------------------------------------------------
//
//   Copyright 2025 NEC Corporation
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//
////////////////////////////////////////////////////////////////////////////////////////////////////

// メッセージIDの頭文字 FTE
// 標準メニュー        00001～01000
// メニュー定義・作成   01001～02000
// Conductorクラス編集 02001～03000
// Conductor作業確認   03001～04000
// 作業実行            04001～05000
// 作業状態確認        05001～06000
// DashBoard           08001～09000
// Terraform          09001～10000
// Ui common           10001～11000
// AI                  14001～15000


export function messageid_en() {

    const message = {
        // Default menu
        'FTE00001' : "Filter",
        'FTE00002' : "Close",
        'FTE00003' : "Open",
        'FTE00004' : "Please make a selection.",
        'FTE00005' : "Working execution",
        'FTE00006' : "Dry run",
        'FTE00007' : "Parameter Confirmation",
        'FTE00008' : "Register",
        'FTE00009' : "Edit",
        'FTE00010' : "This menu is for viewing only.",
        'FTE00011' : "Edit Confirmation",
        'FTE00012' : "Add",
        'FTE00013' : "Duplicate",
        'FTE00014' : "Delete",
        'FTE00015' : "Discard",
        'FTE00016' : "Restore",
        'FTE00017' : "Cancel edit",
        'FTE00018' : "Cancel Confirmation",
        'FTE00019' : "Do you have data that is being edited and would you like to discard it?",
        'FTE00020' : "Discard",
        'FTE00021' : "Back to edit",
        'FTE00022' : "Edit reflection",
        'FTE00023' : "Return to Registration/Editing",
        'FTE00024' : "Before change",
        'FTE00025' : "Non-display",
        'FTE00026' : "Display",
        'FTE00027' : "Historical view",
        'FTE00028' : "History reset",
        'FTE00029' : "Target ",
        'FTE00030' : " and enter",
        'FTE00031' : "press the history display.",
        'FTE00032' : "Select",
        'FTE00033' : "Division",
        'FTE00034' : "Contents",
        'FTE00035' : "History log No.",
        'FTE00036' : "Change date/time",
        'FTE00037' : "Required",
        'FTE00038' : "Discard",
        'FTE00039' : "Search from pulldown",
        'FTE00040' : "All records",
        'FTE00041' : "Exclude discarded records",
        'FTE00042' : "Only discarded records",
        'FTE00043' : "Filter",
        'FTE00044' : "Clear filter",
        'FTE00045' : "Auto-filter",
        'FTE00046' : "Excel download",
        'FTE00047' : "JSON download",
        'FTE00048' : "Maximum line count for Excel output",
        'FTE00049' : "line",
        'FTE00050' : "cannot download because it has been exceeded.",
        'FTE00051' : "Operation",
        'FTE00052' : "Enter password",
        'FTE00053' : "Delete entered passwords",
        'FTE00054' : "There is no content available for display.",
        'FTE00055' : "The initial filter is off.",
        'FTE00056' : "Filter to view.",
        'FTE00057' : "History",
        'FTE00058' : "Number of filter results",
        'FTE00059' : "0 record",
        'FTE00060' : "Number of items to be displayed on one page",
        'FTE00061' : "page",
        'FTE00062' : "Number of edits",
        'FTE00063' : " records",
        'FTE00064' : "Share",
        'FTE00065' : "Validation error",
        'FTE00066' : function( result, limit ){ return `The maximum number of items has been exceeded.\nMay I display it?\n(Maximum number of items: ${limit}, Record count: ${result})`},
        'FTE00067' : function( result, limit ){ return `The maximum number of items that can be displayed has been exceeded.\nPlease refine your filter criteria.\n(Maximum number of items: ${limit}, Record count: ${result})`},
        'FTE00068' : "Validation errors occurred.",
        'FTE00069' : "Register",
        'FTE00070' : "Error string",
        'FTE00071' : "Error",
        'FTE00072' : "Register",
        'FTE00073' : "Update",
        'FTE00074' : "Discard",
        'FTE00075' : "Restore",
        'FTE00076' : "File clear",
        'FTE00077' : "Welcome to IT Automation",
        'FTE00078' : "Menu information",
        'FTE00079' : "View Menu information",
        'FTE00080' : "Check execution status",
        'FTE00081' : "Execution log",
        'FTE00082' : "Error log",
        'FTE00083' : "Bulk registration confirmation",
        'FTE00084' : "Bulk registration in progress",
        'FTE00085' : function( result, limit ){ return `line count for Excel output: ${result}lines\n\nDownload will be canceled because the Maximum line count for Excel output(${limit}lines) has been exceeded.`},
        'FTE00086' : "Table setting",
        'FTE00087' : "Apply",
        'FTE00088' : "Cancel",
        'FTE00089' : "Reset individual settings",
        'FTE00090' : "Item display direction",
        'FTE00091' : "Vertical",
        'FTE00092' : "Horizontal",
        'FTE00093' : "",
        'FTE00094' : "Filter display position",
        'FTE00095' : "Inside",
        'FTE00096' : "Outside",
        'FTE00097' : "Item menu display",
        'FTE00098' : "Omit",
        'FTE00099' : "Show",
        'FTE00100' : "Item Show/Hide, Fixed left/right",
        'FTE00101' : "Set the display direction of the item.",
        'FTE00102' : "Set the display position of the filter. If the item display direction is horizontal, it will be fixed to the outside.",
        'FTE00103' : "Set the display method of the item menu.",
        'FTE00104' : "Set Show/Hide, Fixed left/right side for each item.",
        'FTE00105' : "Common setting",
        'FTE00106' : "Default",
        'FTE00107' : "Custom",
        'FTE00108' : "Individual setting",
        'FTE00109' : "Input field color setting",
        'FTE00110' : "Set color of input field.",
        'FTE00111' : "Any",
        'FTE00112' : "Required",
        'FTE00113' : "Typing",
        'FTE00114' : "Entered",
        'FTE00115' : "Border",
        'FTE00116' : "BG",
        'FTE00117' : "Text",
        'FTE00118' : " confirmation",
        'FTE00119' : function( text ){ return `Are you sure you want to run the "${text}"?`;},
        'FTE00120' : "Internal execution",
        'FTE00121' : "Execution result",
        'FTE00122' : "Execution",
        'FTE00123' : "Cancel",
        'FTE00124' : ['First','Second','Third','Fourth','Last'],
        'FTE00125' : ['Sunday','Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'],
        'FTE00126' : "Time",
        'FTE00127' : "Day",
        'FTE00128' : "Week",
        'FTE00129' : "Month(Specify day)",
        'FTE00130' : "Month(Specify day of week)",
        'FTE00131' : "End of month",
        'FTE00132' : "Interval",
        'FTE00133' : "Time",
        'FTE00134' : "Day",
        'FTE00135' : "Week",
        'FTE00136' : "Month",
        'FTE00137' : "day",
        'FTE00138' : "Day",
        'FTE00139' : "Day of week",
        'FTE00140' : "Hour",
        'FTE00141' : "Minutes",
        'FTE00142' : "Schedule setting",
        'FTE00143' : "Apply",
        'FTE00144' : "Cancel",
        'FTE00145' : "Work period",
        'FTE00146' : "Start",
        'FTE00147' : "End",
        'FTE00148' : "to",
        'FTE00149' : "Schedule",
        'FTE00150' : "Work suspension period",
        'FTE00151' : "Start",
        'FTE00152' : "End",
        'FTE00153' : "Note",
        'FTE00154' : "Please enter a work start date.",
        'FTE00155' : "start date",
        'FTE00156' : "end date",
        'FTE00157' : "start of work suspension period",
        'FTE00158' : "end of work suspension period",
        'FTE00159' : function( text ){ return `Invalid ${text} value(Valid only for official datetime in "yyyy/MM/dd HH:mm:ss" format)`;},
        'FTE00160' : "Start date must be earlier than end date.",
        'FTE00161' : "The start of the suspension period must be earlier the end",
        'FTE00162' : "Suspension period must be entered for both start and end.",
        'FTE00163' : "The work suspension period must be within the work period.",
        'FTE00164' : "Period",
        'FTE00165' : "Seconds",
        'FTE00166' : "Filter validation error",
        'FTE00167' : "Plan confirmation",
        'FTE00168' : "Update",
        'FTE00169' : "Download",
        'FTE00170' : "Close",
        'FTE00171' : "Name",
        'FTE00172' : "Mode",
        'FTE00173' : "Theme",
        'FTE00174' : "ITA original variable",
        'FTE00175' : "Edit",
        'FTE00176' : "Preview",
        'FTE00177' : "Blank",
        'FTE00178' : "Item menu",
        'FTE00179' : "Failed to get file.",
        'FTE00180' : "Loading file",
        'FTE00181' : "WARNING: Downloading JSON file.\nLarge file within the records may overload the memory, leading to possible system failure.\nWould you like to continue?",
        'FTE00182' : "Download all (JSON:No File)",
        'FTE00183' : "JSON download (No File)",
        'FTE00184' : "Editing reflected",
        'FTE00185' : "Download",
        'FTE00186' : function( statusCode ){return `An error occurred while registering the data. (${statusCode})`},
        'FTE00187' : 'Regular execution of weekly tasks assumes Sunday as the start of the week. Recurrence schedules are calculated based on settings.',
        'FTE00188' : "Delete",
        'FTE00189' : "Delete",
        'FTE00190' : "Delete confirmation",
        'FTE00191' : "Delete",
        'FTE00192' : "Return to list",
        'FTE00193' : "This file does not support content previewing or editing. Please download it to view the contents.",
        'FTE00194' : "This file does not support previewing. Please download it to view the content.",

        // Create parameter sheet
        'FTE01001' : "Item",
        'FTE01002' : "Group",
        'FTE01003' : "Cancel",
        'FTE01004' : "Redo",
        'FTE01005' : "Preview",
        'FTE01006' : "Log",
        'FTE01007' : "List(Preview)",
        'FTE01008' : "Parameter sheet creation information",
        'FTE01009' : "Basic information",
        'FTE01010' : "ID",
        'FTE01011' : "Auto-input",
        'FTE01012' : "Parameter sheet name",
        'FTE01013' : "Parameter sheet name(Rest)",
        'FTE01014' : "Creation target",
        'FTE01015' : "Display order",
        'FTE01016' : "Create as bundle",
        'FTE01017' : "Last modified",
        'FTE01018' : "Last updated by",
        'FTE01019' : "Target menu group",
        'FTE01020' : "Input",
        'FTE01021' : "Substitution value",
        'FTE01022' : "Reference",
        'FTE01023' : "Unique constraint(Multiple items)",
        'FTE01024' : "Pattern",
        'FTE01025' : "Permission role",
        'FTE01026' : "Role",
        'FTE01027' : "Explanation",
        'FTE01028' : "Remarks",
        'FTE01029' : "Enter the parameter sheet name of the parameter sheet to be created.\nThe maximum size is 255 bytes.\nThe parameter sheet name &quot;Main menu&quot; cannot be used.\n &quot;&#92;&#47;&#58;&#42;&#63;&#34;&#60;&#62;&#124;&#91;&#93;：￥／＊［］&quot; characters cannot be used.",
        'FTE01030' : "Enter the name for the REST API of the parameter sheet to be created.\nThe maximum size is 240 bytes.\nOnly single-byte alphanumeric characters and the symbol &quot;-_&quot; can be used.",
        'FTE01031' : "Select &quot;Parameter Sheet (Host / Operation)&quot; or &quot;Parameter Sheet (Operation)&quot; or\n&quot;Data Sheet (master available)&quot; from the pull-down menu.",
        'FTE01032' : "Enter the display order in the menu group. They are displayed in ascending order.\nInteger value from 0 to 2147483647 can be entered.",
        'FTE01033' : "If the &quot;use&quot; checkbox is checked, a parameter sheet corresponding to the vertical parameter sheet will be created.",
        'FTE01034' : "Yes",
        'FTE01035' : "Select Target menu group",
        'FTE01036' : "Select Unique constraint(Multiple items)",
        'FTE01037' : "Select Permission role",
        'FTE01038' : "Enter the description.\nThe maximum size is 1024 bytes.",
        'FTE01039' : "Enter the remarks.\nThe maximum size is 4000 bytes.",
        'FTE01040' : "Required item",
        'FTE01041' : "Create",
        'FTE01042' : "Edit",
        'FTE01043' : "Initialize",
        'FTE01044' : "Diversion new",
        'FTE01045' : "Parameter sheet creation history",
        'FTE01046' : "Create(Initialize)",
        'FTE01047' : "Reload",
        'FTE01048' : "Cancel",
        'FTE01049' : "Create(Edit)",
        'FTE01050' : "Close",
        'FTE01051' : "Decision",
        'FTE01052' : "Cansel",
        'FTE01053' : "Item",
        'FTE01054' : "Group",
        'FTE01055' : "Maximum number of bytes",
        'FTE01056' : "Regular expression",
        'FTE01057' : "Minimum value",
        'FTE01058' : "Maximum value",
        'FTE01059' : "Digit number",
        'FTE01060' : "Selection item",
        'FTE01061' : "Required",
        'FTE01062' : "Unique constraint",
        'FTE01063' : "Explanation",
        'FTE01064' : "Remark",
        'FTE01065' : "Host name",
        'FTE01066' : "Operation",
        'FTE01067' : "Parameter",
        'FTE01068' : "Operation name",
        'FTE01069' : "Reference date and time",
        'FTE01070' : "Scheduled date",
        'FTE01071' : "Last run date",
        'FTE01072' : "Remark",
        'FTE01073' : "Last Modified",
        'FTE01074' : "Last updated by",
        'FTE01075' : "Operation",
        'FTE01076' : "System Administrator",
        'FTE01077' : "Target menu group",
        'FTE01078' : "Repeat item will be canceled.",
        'FTE01079' : "Items containing repeats cannot be copied.",
        'FTE01080' : "Input",
        'FTE01081' : "Substitution<br>value",
        'FTE01082' : "Reference",
        'FTE01083' : "Menu group name",
        'FTE01084' : "About bundle",
        'FTE01085' : "Yes",
        'FTE01086' : "Maximum number of bytes in the file",
        'FTE01087' : "Reference item",
        'FTE01088' : "[Referenced value]",
        'FTE01089' : "Select reference item",
        'FTE01090' : "Create",
        'FTE01091' : "Unique constraint(Multiple items)",
        'FTE01092' : "Permission role",
        'FTE01093' : "Reference Item",
        'FTE01094' : "Default value",
        'FTE01095' : "Menu",
        'FTE01096' : "Item",
        'FTE01097' : "String",
        'FTE01098' : "Multi string",
        'FTE01099' : "Password",
        'FTE01100' : "File",
        'FTE01101' : "Link",
        'FTE01102' : "[Referenced value]",
        'FTE01103' : "Move item.",
        'FTE01104' : "Enter the item name to be displayed on the parameter sheet.\nThe maximum size is 255bytes.\nDo not use \"/\" in the item names.",
        'FTE01105' : "Enter the name of the item (for REST API).\nThe maximum size is 255bytes.\nOnly alphanumeric characters and _- are allowed.",
        'FTE01106' : "Delete the item.",
        'FTE01107' : "Copy the item.",
        'FTE01108' : "Enter the number of repeats.\nInteger value from 2 to 99 can be entered.",
        'FTE01109' : "Selecte \"String\", \"Multi string\", \"Integer\", \"Decimal number\", \"Date\", \"Date/time\",\n\"Pull down selection\", \"Password\", \"File upload\", \"Link\" from the pulldown menu.",
        'FTE01110' : "Enter the maximum number of bytes.\nThe maximum size is 65536 bytes.\nFor editing, it is possible to increase it from the original value.\nThe byte count of half-width alphanumeric characters are equivalent to the number of characters.\nFor full-width characters, the number of characters x 3 + 2 bytes is required.",
        'FTE01111' : "If you want to check input values with regular expression, enter the regular expression.\nThe maximum size is 8192 bytes.\nExample: For half-width numeric items of 0 bytes or more: ^[0-9]*$\n For half-width alphanumeric characters of 1 byte or more: ^[a-zA-Z0-9]+$",
        'FTE01112' : "Enter the minimum value of the column.\nFor editing, it is possible to reduce it from the original value.\nInteger value from -2147483648 to 2147483647 can be entered.\nThe value will be -2147483648 if not entered.\nPlease enter value smaller than the maximum value.",
        'FTE01113' : "Enter the maximum value of the column.\nFor editing, it is possible to increase it from the original value.\nInteger value from -2147483648 to 2147483647 can be entered.\nThe value will be 2147483647 if not entered.\nPlease enter value larger than the minimum value.",
        'FTE01114' : "Enter the minimum value of the column.\nFor editing, it is possible to reduce it from the original value.\nInteger value from -99999999999999 to 99999999999999 with total digit for whole\nnumber + fraction part less than 14 digits can be entered.\nThe value will be -99999999999999 if not entered.\nPlease enter value smaller than the maximum value.",
        'FTE01115' : "Enter the maximum value of the column.\nFor editing, it is possible to increase it from the original value.\nInteger value from -99999999999999 to 99999999999999 with total digit for whole\nnumber + fraction part less than 14 digits can be entered.\nThe value will be 99999999999999 if not entered.\nPlease enter value larger than the minimum value.",
        'FTE01116' : "Enter the upper limit of the total digit for whole number + fraction part.\nFor editing, it is possible to increase it from the original valu.\n\nExample: 0.123 has 4 digits (whole number 1 digit, fraction part 3 digits)\n 11.1111 has 6 digits (whole number 2 digit2, fraction part 3 digits)\nInteger value from 1 to 14 can be entered.",
        'FTE01117' : "Select the item to be referenced in the pulldown menu from the pull-down menu.\n※Items that satisfy the following conditions are displayed in the pull-down menu .\Parameter sheet: 「Basic Console: Device List」 and parameter sheet created with this function\nItem: String, required and unique constraint item.",
        'FTE01118' : "You can refer to other items based on the parameter sheet item you selected in \"Pulldown Selection\".",
        'FTE01119' : function(size){ return `Enter the maximum number of bytes for the file to upload.\nFor editing, it is possible to increase it from the original value.\nThe maximum size is ${size} bytes.`},
        'FTE01120' : "Select the item to be referenced from the parameter sheet items created in the Creation target \"Parameter Sheet(Operation)\".\nRefers to the value of the same operation from the selected items.",
        'FTE01121' : "When registering from the created parameter sheet, set the value to be entered in the input field by default.\nYou cannot set a value that exceeds the \"Maximum number of bytes\" or a value that does not match the \"Regular expression\".",
        'FTE01122' : "When registering from the created parameter sheet, set the value to be entered in the input field by default.\nYou cannot set a Values outside the range of \"Maximum value\" and \"Minimum value\".",
        'FTE01123' : "When registering from the created parameter sheet, set the value to be entered in the input field by default.\nYou cannot set a Values outside the range of \"Maximum value\" and \"Minimum value\" and \"Digit number\".",
        'FTE01124' : "When registering from the created parameter sheet, set the value to be entered in the input field by default.",
        'FTE01125' : "When registering from the created parameter sheet, set the value to be entered in the input field by default.\nYou cannot set a value that exceeds the \"Maximum number of bytes\".",
        'FTE01126' : "When registering from the created parameter sheet, Set the value selected by default.",
        'FTE01127' : "To make it a required item, check the check box.",
        'FTE01128' : "To make it a unique item, check the check box.",
        'FTE01129' : "Enter the description that will be displayed when users hover mouse cursor over the item name.\nThe maximum size is 1024 bytes.",
        'FTE01130' : "Enter the remarks column.\nThe maximum size is 4000 bytes.",
        'FTE01131' : "Please Wait... Loading",
        'FTE01132' : "Failed to get the Default value",
        'FTE01133' : "Exchange ID has failed",
        'FTE01134' : "Date/time",
        'FTE01135' : "Date",
        'FTE01136' : "Do you want to create the parameter sheet?\n*If a parameter sheet with the same parameter sheet name or a parameter sheet the same 'Parameter sheet definition information' ID already exists, the existing data will be deleted and overwritten by the new data.\\nIf you need to retain the existing data, select 'Cancel' and perform a backup.",
        'FTE01137' : "Do you want to perform parameter sheet initialization? \n*The data you have already entered in this parameter sheet will be deleted. \nIf you need the entered data, please select \"Cancel\" to back up the data.",
        'FTE01138' : "Do you want to perform an edit of the parameter sheet? \n*The data entered in the existing item will remain, but if you had deleted the existing item, the data entered in that item will be deleted. \nIf you change the \"Regular expression\" in an existing item, it may cause inconsistency with the existing data. \nAlso, if the newly added item was set as \"Required\" and \"Unique constraint\", empty data will be entered in the required field, which may cause data inconsistency. \nIf you need to modify the data, please select \"Cancel\".",
        'FTE01139' : "Failed to get the reference item.",
        'FTE01140' : "Parameter sheet creation was accepted.\nPlease click the parameter sheet creation history button and check the creation status.\nUUID:",
        'FTE01141' : "Validation errors occurred.",
        'FTE01142' : "No items.",
        'FTE01143' : "Delete",
        'FTE01144' : "Add a pattern",
        'FTE01145' : "No patterns.",
        'FTE01146' : "Item name",
        'FTE01147' : "Item name(rest)",
        'FTE01148' : "Full screen",
        'FTE01149' : "Exit full screen",
        'FTE01150' : "Enter the maximum number of bytes.\nThe maximum size is 255 bytes.\nFor editing, it is possible to increase it from the original value.\nThe byte count of half-width alphanumeric characters are equivalent to the number of characters.\nFor full-width characters, the number of characters x 3 + 2 bytes is required.",
        'FTE01151' : "Create(New)",
        'FTE01152' : "There are no items available for reference.",
        'FTE01153' : "Create as hostgroup",
        'FTE01154' : "If the &quot;use&quot; checkbox is checked, a &quot;Host name/Host Group name&quot; parameter sheet will be created in the &quot;Input&quot; Menu group.\nIf the &quot;use &quot; checkbox is unchecked, a &quot;host name&quot; parameter sheet will be created.",
        'FTE01155' : function(id){ return `Duplicate ID（${id}）.`;},
        'FTE01156' : function(id){ return `ID（${id}） specified in columns was not found.`;},
        'FTE01157': 'Failed to load JSON.',
        'FTE01158' : "Enter the maximum number of bytes.\nThe maximum size is 8192 bytes.\nFor editing, it is possible to increase it from the original value.\nThe byte count of half-width alphanumeric characters are equivalent to the number of characters.\nFor full-width characters, the number of characters x 3 + 2 bytes is required.",
        'FTE01159' : "Group and Item Count",
        'FTE01160' : "An empty group is included. Add items to the group or delete the empty group.",
        'FTE01161' : function(num){ return `Group and Item count exceeds the limit (${num}).`;},

        // Conductor
        'FTE02001' : "Conductor instance id is not yet set.",
        'FTE02002' : "Enter the Conductor instance ID and click the Work Confirm button, or",
        'FTE02003' : "Conductor history",
        'FTE02004' : " click the Details button on the page.",
        'FTE02005' : "Select",
        'FTE02006' : "Register",
        'FTE02007' : "Reset",
        'FTE02008' : "Edit",
        'FTE02009' : "Execution",
        'FTE02010' : "Diversion",
        'FTE02011' : "New",
        'FTE02012' : "Update",
        'FTE02013' : "Reload",
        'FTE02014' : "Cancel",
        'FTE02015' : "Operation check",
        'FTE02016' : "Schedule cancellation",
        'FTE02017' : "Emergency stop",
        'FTE02018' : "Conductor instance ID",
        'FTE02019' : "Full screen",
        'FTE02020' : "Full screen release",
        'FTE02021' : "JSON save",
        'FTE02022' : "JSON read",
        'FTE02023' : "Operation cancel",
        'FTE02024' : "Operation redo",
        'FTE02025' : "Selected node deletion",
        'FTE02026' : "The entire display",
        'FTE02027' : "Log",
        'FTE02028' : "failed to read.",
        'FTE02029' : "Failed to execute operation.",
        'FTE02030' : "Do you want to register?",
        'FTE02031' : "Registration completed.",
        'FTE02032' : "Failed to register",
        'FTE02033' : "Loading completed.",
        'FTE02034' : "Do you want to reset it?",
        'FTE02035' : "Reset.",
        'FTE02036' : "Do you want to divert?",
        'FTE02037' : "Diversion.",
        'FTE02038' : "Do you want to update?",
        'FTE02039' : "Updated.",
        'FTE02040' : "Update failed.",
        'FTE02041' : "Are you sure you want to refresh?",
        'FTE02042' : "Reloaded.",
        'FTE02043' : "Cancel a Conductor reservation?",
        'FTE02044' : "Do you want an emergency stop?",
        'FTE02045' : "Normal end",
        'FTE02046' : "Abend",
        'FTE02047' : "Unexpected error",
        'FTE02048' : "Emergency stop",
        'FTE02049' : "Preparation error",
        'FTE02050' : "Skip end",
        'FTE02051' : "Warning end",
        'FTE02052' : "Other",
        'FTE02053' : "There is a maximum of 6 conditional branches.",
        'FTE02054' : "There is no connection destination.",
        'FTE02055' : "Cannot be merged.",
        'FTE02056' : "Normal",
        'FTE02057' : "Abnormal",
        'FTE02058' : "Warning",
        'FTE02059' : "Filter settings",
        'FTE02060' : "Do not use regular expressions",
        'FTE02061' : "Use regular expressions",
        'FTE02062' : "Orchestrator Selection",
        'FTE02063' : "Setting",
        'FTE02064' : "Cancel",
        'FTE02065' : "Remarks",
        'FTE02066' : "Enter description (Maximum length) 4000 bytes",
        'FTE02067' : "Conductor Information",
        'FTE02068' : "Enter Conductor name.(Maximum length) 255 bytes",
        'FTE02069' : "Name",
        'FTE02070' : "Update Date",
        'FTE02071' : "Movement Information",
        'FTE02072' : "ID",
        'FTE02073' : "Skip",
        'FTE02074' : "Individual operation",
        'FTE02075' : "Operation selection",
        'FTE02076' : "Clear",
        'FTE02077' : "Exit Status",
        'FTE02078' : "Parallel branch setting",
        'FTE02079' : "Branch addition",
        'FTE02080' : "Branch deletion",
        'FTE02081' : "Parallel merge setting",
        'FTE02082' : "Merge addition",
        'FTE02083' : "Merge deletion",
        'FTE02084' : "Conditional branch setting",
        'FTE02085' : "Branch addition",
        'FTE02086' : "Branch deletion",
        'FTE02087' : "Conductor call information",
        'FTE02088' : "Skip",
        'FTE02089' : "Call conductor",
        'FTE02090' : "Conductor selection",
        'FTE02091' : "Clear",
        'FTE02092' : "Individual operation",
        'FTE02093' : "Operation selection",
        'FTE02094' : "Clear",
        'FTE02095' : "Status file branch setting",
        'FTE02096' : "Condition addition",
        'FTE02097' : "Condition deletion",
        'FTE02098' : "Node alignment",
        'FTE02099' : "Alignment",
        'FTE02100' : "Align horizontally to the left",
        'FTE02101' : "Align horizontally to the center",
        'FTE02102' : "Align horizontally to the right",
        'FTE02103' : "Align vertically to the top",
        'FTE02104' : "Align vertically to the center",
        'FTE02105' : "Align vertically to the bottom",
        'FTE02106' : "Equal space",
        'FTE02107' : "Distribute evenly vertically",
        'FTE02108' : "Distribute evenly horizontally",
        'FTE02109' : "Conductor instance information",
        'FTE02110' : "Status",
        'FTE02111' : "Start time",
        'FTE02112' : "End time",
        'FTE02113' : "Execution user",
        'FTE02114' : "Scheduled date/time",
        'FTE02115' : "Emergency stop",
        'FTE02116' : "Operation",
        'FTE02117' : "Node instance information",
        'FTE02118' : "Type",
        'FTE02119' : "Node ID",
        'FTE02120' : "St file",
        'FTE02121' : "Start date/time",
        'FTE02122' : "End date/time",
        'FTE02123' : "Operation status check",
        'FTE02124' : "Confirmation",
        'FTE02125' : "Individual operation",
        'FTE02126' : "Conductor data is incorrect.",
        'FTE02127' : "Failed to read.",
        'FTE02128' : "Check execution status",
        'FTE02129' : "Reservation cancellation failed.",
        'FTE02130' : "Emergency stop failed.",
        'FTE02131' : "Are you sure you want to cancel the suspension?",
        'FTE02132' : "Failed to release pause.",
        'FTE02133' : "Edit mode",
        'FTE02134' : "View mode",
        'FTE02135' : "Update mode",
        'FTE02136' : "Confirmation mode",
        'FTE02137' : "You cannot delete a connected branch.",
        'FTE02138' : "There are at least two branches.",
        'FTE02139' : "Looped connections are not possible.",
        'FTE02140' : "Conductor execution error.",
        'FTE02141' : "Conductor execution log.",
        'FTE02142' : "Menu",
        'FTE02143' : "Auto-input",
        'FTE02144' : "Mouse wheel",
        'FTE02145' : "Enlargement / Reduction the screen",
        'FTE02146' : "Mouse right drag",
        'FTE02147' : "Screen movement",
        'FTE02148' : "Mouse left click",
        'FTE02149' : "Node select / Delete connection line",
        'FTE02150' : "Mouse left drag",
        'FTE02151' : "Node move / Node multiple select",
        'FTE02152' : "Node select",
        'FTE02153' : "Node select / Check execution status",
        'FTE02154' : "Mouse operation",
        'FTE02155' : "Keyboard operation",
        'FTE02156' : "Select all nodes",
        'FTE02157' : "Delete selected node",
        'FTE02158' : "Move selected node",
        'FTE02159' : "Branch addition/deletion of the selected branch node",
        'FTE02160' : "Arrow key",
        'FTE02161' : "Now loading",
        'FTE02162' : "Data in the process of being edited has been read from local storage.",
        'FTE02163' : "Movement name",
        'FTE02164' : "No notice definition.\nRegister the notice definition from Conductor notice definition.",
        'FTE02165' : "No notice definition",
        'FTE02166' : "Go to Conductor notice definition",
        'FTE02167' : "Close",
        'FTE02168' : "Notice setting",
        'FTE02169' : "OK",
        'FTE02170' : "Cancel",
        'FTE02171' : "Notice Name",
        'FTE02172' : "Notice",
        'FTE02173' : "Snap to grid",
        'FTE02174' : "Movement common display settings",
        'FTE02175' : "Width",
        'FTE02176' : "Wrap name",
        'FTE02177' : "Auto",
        'FTE02178' : "Circle only",
        'FTE02179' : "Wrap",
        'FTE02180' : "Ellipsis",

        // Execution
        'FTE05001' : "Execution No.",
        'FTE05002' : "Check execution status",
        'FTE05003' : "Schedule cancellation",
        'FTE05004' : "Emergency stop",
        'FTE05005' : "Execution No. has not been set.",
        'FTE05006' : "Enter the execution No. and click the check execution status button, or",
        'FTE05007' : "Work management page",
        'FTE05008' : "Please press the Details button",
        'FTE05009' : "Operation status",
        'FTE05010' : "Execution type",
        'FTE05011' : "Status",
        'FTE05012' : "Execution engine",
        'FTE05013' : "Caller conductor",
        'FTE05014' : "Execution user",
        'FTE05015' : "Populated data",
        'FTE05016' : "Result data",
        'FTE05017' : "Operation status",
        'FTE05018' : "Scheduled date/time",
        'FTE05019' : "Start date/time",
        'FTE05020' : "End date/time",
        'FTE05021' : "Operation",
        'FTE05022' : "ID",
        'FTE05023' : "Name",
        'FTE05024' : "Confirmation of hosts to be worked on",
        'FTE05025' : "Confirmation of assignment value",
        'FTE05026' : "Movement",
        'FTE05027' : "Delay timer (minute)",
        'FTE05028' : "Movement detail confirmation",
        'FTE05029' : "Dedicated information for ansible",
        'FTE05030' : "Host specific format",
        'FTE05031' : "WinRM connection",
        'FTE05032' : "ansible.cfg",
        'FTE05033' : "Ansible Core dedicated information",
        'FTE05034' : "virtualenv",
        'FTE05035' : "Ansible Automation Controller dedicated information",
        'FTE05036' : "Execution environment",
        'FTE05037' : "Cancel a reservation?",
        'FTE05038' : "Terraform dedicated information",
        'FTE05039' : "Ansible Execution Agent information",
        'FTE05040' : "Execution environment",
        'FTE05041' : "Status",
        'FTE05042' : "Collection log",
        'FTE05043' : "Collection status",
        'FTE05044' : "Confirmation of execution list",
        'FTE05045' : 'Execution list',

        // Compare
        'FTE06001' : "Compare setting selection",
        'FTE06002' : "Host selection",
        'FTE06003' : "Compare execution",
        'FTE06004' : "Choose compare settings.",
        'FTE06005' : "Choose target host settings.",
        'FTE06006' : "Please compare execution.",
        'FTE06007' : "Compare setting",
        'FTE06008' : "Compare name",
        'FTE06009' : "Detail flg",
        'FTE06010' : "Parameter sheet name",
        'FTE06011' : "Reference date1",
        'FTE06012' : "Reference date2",
        'FTE06013' : "All output",
        'FTE06014' : "Difference only",
        'FTE06015' : "Compara target parameter sheet1",
        'FTE06016' : "Compara target parameter sheet2",
        'FTE06017' : "Output contents",
        'FTE06018' : "Host name",
        'FTE06019' : "Diff",
        'FTE06020' : "Target host",
        'FTE06021' : "Failed to compare.",
        'FTE06022' : "Compara target parameter sheet1 Reference date",
        'FTE06023' : "Compara target parameter sheet2 Reference date",
        'FTE06024' : "Item",
        'FTE06025' : "Note",
        'FTE06026' : "File difference details",
        'FTE06027' : "No file diff",
        'FTE06028' : "No compare result.",
        'FTE06029' : "Compare result",
        'FTE06030' : "File comparison",
        'FTE06031' : "Close",
        'FTE06032' : "Donwload compare result(Excel)",
        'FTE06033' : "Download failed.",
        'FTE06034' : "File comparison result print",

        // Export - Import
        'FTE07001' : "All menu",
        'FTE07002' : "Detail",
        'FTE07003' : "Export time specification",
        'FTE07004' : "Export setting",
        'FTE07005' : "Export with the following contents.",
        'FTE07006' : "Number of menus",
        'FTE07007' : "Mode",
        'FTE07008' : "Time specification",
        'FTE07009' : "Discard information",
        'FTE07010' : "Export confirmation",
        'FTE07011' : "Start export",
        'FTE07012' : "Cancel",
        'FTE07013' : "Export",
        'FTE07014' : "Export",
        'FTE07015' : "Export menu selection",
        'FTE07016' : "Environmental migration",
        'FTE07017' : "Including discard",
        'FTE07018' : "Excluding discard",
        'FTE07019' : "All records",
        'FTE07020' : "Discard only",
        'FTE07021' : "Import setting",
        'FTE07022' : "Import menu selection",
        'FTE07023' : "The selected file cannot be opened.",
        'FTE07024' : "File selection",
        'FTE07025' : "Import",
        'FTE07026' : "Please select a file to import.",
        'FTE07027' : "Import file",
        'FTE07028' : "File name",
        'FTE07029' : "Import with the following contents.",
        'FTE07030' : "Import confirmation",
        'FTE07031' : "Start import",
        'FTE07032' : "Import",
        'FTE07033' : "import failed.",
        'FTE07034' : "Unknown menu group",
        'FTE07035' : "Contains menus that cannot be imported.",
        'FTE07036' : "Loading import file",
        'FTE07037' : "History",
        'FTE07038' : "History",
        'FTE07039' : "History available",
        'FTE07040' : "No history",

        // DashBoard
        'FTE08001' : "Menu group",
        'FTE08002' : "Items per line",
        'FTE08003' : "Display format",
        'FTE08004' : "Icon",
        'FTE08005' : "List",
        'FTE08006' : "Menu group name",
        'FTE08007' : "Show",
        'FTE08008' : "Hide",
        'FTE08009' : "Menu set",
        'FTE08010' : "Create a set of menu groups separate from the menu group.",
        'FTE08011' : "Link list",
        'FTE08012' : "Create a list of links.",
        'FTE08013' : "Item",
        'FTE08014' : "Add item",
        'FTE08015' : "List download",
        'FTE08016' : "List read",
        'FTE08017' : "Name",
        'FTE08018' : "Movement registration number",
        'FTE08019' : "Display a graph of the registered movements.",
        'FTE08020' : "Conductor work status",
        'FTE08021' : "Display a graph of the conductor work status.",
        'FTE08022' : "Status",
        'FTE08023' : "Conductor work result",
        'FTE08024' : "Display a graph of the conductor work result",
        'FTE08025' : "Result",
        'FTE08026' : "Conductor work history",
        'FTE08027' : "Display a graph of the conductor work history",
        'FTE08028' : "Period",
        'FTE08029' : "Day",
        'FTE08030' : "Conductor reservation work",
        'FTE08031' : "Shows Conductor reserved for execution.",
        'FTE08032' : "Instance ID",
        'FTE08033' : "Operation name",
        'FTE08034' : "Status",
        'FTE08035' : "Reservation date",
        'FTE08036' : "Remaining to run",
        'FTE08037' : "Day",
        'FTE08038' : "h",
        'FTE08039' : "m",
        'FTE08040' : "Image",
        'FTE08041' : "Paste the image.",
        'FTE08042' : "Image URL",
        'FTE08043' : "Link URL",
        'FTE08044' : "DashBoard edit",
        'FTE08045' : "Add widget",
        'FTE08046' : "Editing apply",
        'FTE08047' : "Reset",
        'FTE08048' : "Cancel editing",
        'FTE08049' : "Reset confirmation",
        'FTE08050' : "Reset DashBoard to initial state?",
        'FTE08051' : "Reset DashBoard",
        'FTE08052' : "Cancel",
        'FTE08053' : "Edit cancellation confirmation",
        'FTE08054' : "Editing in progress, do you want to cancel?",
        'FTE08055' : "Cancel editing",
        'FTE08056' : "Continue editing",
        'FTE08057' : "Widget edit",
        'FTE08058' : "Widget remove",
        'FTE08059' : "Name",
        'FTE08060' : "Horizontal number of bonds",
        'FTE08061' : "Vertical number of bonds",
        'FTE08062' : "Widget",
        'FTE08063' : "Title bar",
        'FTE08064' : "Frame/Background",
        'FTE08065' : "Widget common setting",
        'FTE08066' : "Widget setting",
        'FTE08067' : "Sum",
        'FTE08068' : "Normal end",
        'FTE08069' : "Abend",
        'FTE08070' : "Unexpected error",
        'FTE08071' : "Emergency stop",
        'FTE08072' : "Preparation error",
        'FTE08073' : "Warning end",
        'FTE08074' : "Num",
        'FTE08075' : "Day",
        'FTE08076' : "Executing",
        'FTE08077' : "Unexecuted (schedule)",
        'FTE08078' : "Pause",
        'FTE08079' : "Unexecuted",
        'FTE08080' : function( target, today ){ return ` (${target} - ${today})`},
        'FTE08081' : function( period ){ return ` (Within ${period} days)`},
        'FTE08082' : "Page move",
        'FTE08083' : "Same tab",
        'FTE08084' : "Another tab",
        'FTE08085' : "Another window",
        'FTE08086' : "Modal",
        'FTE08087' : function( day ){ return `There is no reservation work within ${day} days.`},

        // Terraform
        'FTE09001' : "Organization registration list",
        'FTE09002' : "Workspace registration list",
        'FTE09003' : "Policy registration list",
        'FTE09004' : "PolicySet registration list",
        'FTE09005' : "Get organization registration list",
        'FTE09006' : "Get workspace registration list",
        'FTE09007' : "Get policy registration list",
        'FTE09008' : "Get policySet registration list",
        'FTE09009' : "Registered",
        'FTE09010' : "No registration",
        'FTE09011' : "Unlink",
        'FTE09012' : "ITA Registration status",
        'FTE09013' : "Delete",
        'FTE09014' : "Delete resource",
        'FTE09015' : "DDownload",
        'FTE09016' : "Linked Workspace",
        'FTE09017' : "Linked Policy",
        'FTE09018' : function( text ){ return `Please press the "${text}" button.`;},
        'FTE09019' : "Organization Name",
        'FTE09020' : "Email address",
        'FTE09021' : "Workspace Name",
        'FTE09022' : "Terraform Version",
        'FTE09023' : "Policy Name",
        'FTE09024' : "Policy code",
        'FTE09025' : "Policy Set Name",

        // UI common
        'FTE10001': 'Main menu',
        'FTE10002': 'Menu group',
        'FTE10003': 'Favorite',
        'FTE10004': 'History',
        'FTE10005': 'Switch workspace',
        'FTE10006': 'Role list',
        'FTE10007': 'Menu search',
        'FTE10008': 'List',
        'FTE10009': 'Trace history',
        'FTE10010': 'Download all and edit file uploads',
        'FTE10011': 'Download all (Excel)',
        'FTE10012': 'Download the list of registered items in an Excel sheet.',
        'FTE10013': 'Download all (JSON)',
        'FTE10014': 'Download the list of registered items in an JSON.',
        'FTE10015': 'Download for new registration (Excel)',
        'FTE10016': 'Download the Excel sheet for new registrations.',
        'FTE10017': 'Bulk registration (Excel)',
        'FTE10018': 'Excel sheets downloaded from "Download all" and "Download for new registration" can be edited and uploaded from here to be added or edited in batches.',
        'FTE10019': 'Bulk registration (JSON)',
        'FTE10020': 'JSON files can be added and edited in batches by uploading them here.',
        'FTE10021': 'The JSON format is incorrect.',
        'FTE10023': 'Download all trace history(Excel)',
        'FTE10024': 'Download an Excel sheet with the entire history of changes to the list of registered items.',
        'FTE10025': 'Bulk registration start',
        'FTE10026': 'Cancel',
        'FTE10027': 'File name',
        'FTE10028': 'File size',
        'FTE10029': 'Number',
        'FTE10030': 'System error.',
        'FTE10031': 'Excel sheets downloaded from "Download all" can be edited and uploaded from here to be edited in batches.',
        'FTE10032': 'JSON files can be added and edited in batches by uploading them here.',
        'FTE10033': 'Version Check',
        'FTE10034': 'Sign out',
        'FTE10035': 'Installed driver',
        'FTE10036': ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'],
        'FTE10037': ['January','February','March','April','May','June','July','August','September','October','November','December'],
        'FTE10038': 'Apply',
        'FTE10039': 'Current',
        'FTE10040': 'Clear',
        'FTE10041': 'Delete Entered Passwords',
        'FTE10042': 'Registration successful',
        'FTE10043': 'Close',
        'FTE10044': 'Error column',
        'FTE10045': 'Error details',
        'FTE10046': 'Registration Failed',
        'FTE10047': 'Error Log JSON Download',
        'FTE10048': 'Decision to select',
        'FTE10049': 'Operation',
        'FTE10050': 'Operation selection',
        'FTE10051': 'Specify the scheduled date/time in (yyyy/MM/dd HH:mm:ss).<br>Immediately execute when blank.',
        'FTE10052': 'Schedule',
        'FTE10053': 'Log search',
        'FTE10054': 'Display only corresponding lines',
        'FTE10055': 'Name',
        'FTE10056': ' setting',
        'FTE10057': 'Required',
        'FTE10058': 'OK',
        'FTE10059': 'Confirmation',
        'FTE10060' : function( size, limit ){ return `File bytes size exceeds the maximum file bytes size.\n\nFile bytes size: ${ Number( size ).toLocaleString() } Byte\nMaximum file bytes size: ${ Number( limit ).toLocaleString() } Byte`},
        'FTE10061': 'UI Setting',
        'FTE10062': 'Workspace list',
        'FTE10063': 'Thema',
        'FTE10064': 'Select thema',
        'FTE10065': 'Default(Initial design based on blue)',
        'FTE10066': 'Red(Design based on red)',
        'FTE10067': 'Green(Design based on green)',
        'FTE10068': 'Blue(Design based on blue)',
        'FTE10069': 'Orange(Design based on orange)',
        'FTE10070': 'Yellow(Design based on yellow)',
        'FTE10071': 'Purple(Design based on purple)',
        'FTE10072': 'Brown(Design based on brown)',
        'FTE10073': 'Gray(Design based on gray)',
        'FTE10074': 'Cool(Design based on cool colors)',
        'FTE10075': 'Cute(Design based on pink)',
        'FTE10076': 'Natural(Design inspired by nature)',
        'FTE10077': 'Gorgeous(Gorgeous design based on red and black)',
        'FTE10078': 'OASE(Exastro OASE-inspired design)',
        'FTE10079': 'EPOCH(Exastro EPOCH-inspired design)',
        'FTE10080': 'Dark mode(Dark design ideal for nighttime)',
        'FTE10081': 'Filter',
        'FTE10082': 'Grayscale',
        'FTE10083': 'Sepia',
        'FTE10084': 'Brightness',
        'FTE10085': 'Contrast',
        'FTE10086': 'Saturate',
        'FTE10087': 'Hue-Rotate',
        'FTE10088': 'Invert',
        'FTE10089': 'h',
        'FTE10090': 'm',
        'FTE10091': 's',
        'FTE10092': 'Update failed',
        'FTE10093': 'Update failed. Please try again after reloading.',
        'FTE10094': 'Filter reset',
        'FTE10095': 'Due to maintenance, the newly registered Conductor and each driver work execution, Parameter sheet create, Menu export/import, Bulk excel export/import will not be executed.',
        'FTE10096': 'Due to maintenance, data cannot be registered/updated/deleted. In addition, it is not possible to execute the work of Conductor and each driver, Parameter sheet create, Menu export/import, and Bulk excel export/import.',
        'FTE10097' : "Confirmation of execution",
        'FTE10098' : "Deleted records/files will no longer be accessible.",
        'FTE10099' : "Yes, delete",
        'FTE10100' : "Cancel",
        'FTE10101' : "Warning",
        'FTE10102' : 'If you want to continue, please enter <span style="font-weight: bold;">{0}</span>.',
        'FTE10103' : 'Please enter <span style="font-weight: bold;">{0}</span>.',
        'FTE10104': 'Deletion successful',

        // Parameter collection
        'FTE11001': 'Parameter mode',
        'FTE11002': 'Host',
        'FTE11003': 'Operation',
        'FTE11004': 'Display setting',
        'FTE11005': 'Preset registration',
        'FTE11006': 'Operation timeline',
        'FTE11007': 'Target parameter',
        'FTE11008': 'Target host',
        'FTE11009': 'Show parameters',
        'FTE11010': 'Select',
        'FTE11011': 'Clear',
        'FTE11012': 'Unselected',
        'FTE11013': 'Select parameter, host, operation<br>and prease press "Show parameters" button.',
        'FTE11014': 'No host',
        'FTE11015': 'Parameter selection',
        'FTE11016': 'Parameter editing',
        'FTE11017': 'Target operation',
        'FTE11018': 'Print',
        'FTE11019': 'Failed to read.',
        'FTE11020': 'Deleting',
        'FTE11021': 'Registering',
        'FTE11022': 'Parameter collection preset registration',
        'FTE11023': 'Parameter collection preset name change',
        'FTE11024': 'Preset registration',
        'FTE11025': 'Rename Preset',
        'FTE11026': 'Save',
        'FTE11027': 'Rename',
        'FTE11028': 'Delete',
        'FTE11029': 'There is no preset registration.',
        'FTE11030': 'Parameter collection preset',
        'FTE11031': 'Management system number',
        'FTE11032': 'Hostname',
        'FTE11033': 'DNS hostname',
        'FTE11034': 'IP address',
        'FTE11035': 'Menu ID',
        'FTE11036': 'Menu group',
        'FTE11037': 'Menu name',
        'FTE11038': 'Sheet type',
        'FTE11039': 'Bundle',
        'FTE11040': 'Host group',
        'FTE11041': 'with Host/Operation',
        'FTE11042': 'with Operation',
        'FTE11043': 'Use',
        'FTE11044': 'Host selection',
        'FTE11045': ' operations',
        'FTE11046': 'Parameter Display Settings',
        'FTE11047': 'Input order',
        'FTE11048': 'No parameters to display.',
        'FTE11049': 'Excel download',
        'FTE11050': 'Excel download failed.',
        'FTE11051': 'Save confirmation',
        'FTE11052': 'Save',
        'FTE11053': 'Delete confirmation',
        'FTE11054': 'Delete',
        'FTE11055': 'Cancel',
        'FTE11056': function( name ){ return `Save the preset "${name}".`},
        'FTE11057': function( name ){ return `Delete the preset "${name}".`},
        'FTE11058': 'Show no host',
        'FTE11059': 'Menu name search',
        'FTE11060': 'Host name search',
        'FTE11061': 'Parameter_collection_',

        // Custom menu
        'FTE12001': 'Failed to display custom menu.',

        // OASE
        'FTE13001': 'Filter Condition',
        'FTE13002': 'Label Key',
        'FTE13003': 'Condition',
        'FTE13004': 'Condition value',
        'FTE13005': 'Conclusion label setting',
        'FTE13006': 'Conclusion label key',
        'FTE13007': 'Conclusion label value',
        'FTE13008': 'Unknown events',
        'FTE13009': 'Timeout events',
        'FTE13010': 'Known events',
        'FTE13011': 'Conclusion events',
        'FTE13012': 'New events',
        'FTE13013': 'Actions',
        'FTE13014': 'Range specification',
        'FTE13015': 'Setting',
        'FTE13016': 'Range specification history',
        'FTE13017': 'Display pattern selection',
        'FTE13018': function( type ){ return `No ${type} registered.`},
        'FTE13019': function( num ){ return `Last ${num} minute${(num>1)?'s':''}`},
        'FTE13020': function( num ){ return `Last ${num} hour${(num>1)?'s':''}`},
        'FTE13021': function( num ){ return `Last ${num} day${(num>1)?'s':''}`},
        'FTE13022': function( num ){ return `Last ${num} week${(num>1)?'s':''}`},
        'FTE13023': function( num ){ return `Last ${num} month${(num>1)?'s':''}`},
        'FTE13024': function( num ){ return `Last ${num} year${(num>1)?'s':''}`},
        'FTE13025': 'RAW Event Data',
        'FTE13026': 'Event information',
        'FTE13027': 'OFF',
        'FTE13028': function( sec ){ return `${sec}sec`},
        'FTE13029': 'Auto Update',
        'FTE13030': 'Rule',
        'FTE13031': 'is the target',
        'FTE13032': '',
        'FTE13033': '',
        'FTE13034': '',
        'FTE13035': 'Switched to aggregation mode because the number of rows exceeded 100.',
        'FTE13036': 'View',
        'FTE13037': 'Detail',
        'FTE13038': 'Aggregate',
        'FTE13039': 'Processing',
        'FTE13040': 'Please wait',
        'FTE13041': 'Fetch',
        'FTE13042': 'Switched to detail mode because the number of rows is 50 or less.',
        'FTE13043': 'Move Left',
        'FTE13044': 'Move Right',
        'FTE13045': 'Widen Range',
        'FTE13046': 'Set Range specification',
        'FTE13047': 'Clear',

        //AI
        'FTE14001': 'Failed to load user ID.',
        'FTE14002': 'Development support settings',
        'FTE14003': 'Open development support',
        'FTE14004': 'Settings Update',
        'FTE14005': 'Close',
        'FTE14006': 'Delete settings',
        'FTE14007': 'Do you want to remove the developer support settings?',
        'FTE14008': 'AI Assistant',
        'FTE14009': 'AI Selection',
        'FTE14010': 'Load model list',
        'FTE14011': 'setting',
        'FTE14012': 'Model information could not be retrieved.',
        'FTE14013': 'Loading development support',
        'FTE14014': 'AI assistant initialization failed.',
        'FTE14015': 'Close development support',
        'FTE14016': 'Download conversation history',
        'FTE14017': 'Press Enter to send the message. Press Shift+Enter to create a line break.',
        'FTE14018': 'Code attached',
        'FTE14019': 'How may I help you?',
        'FTE14020': 'Copied to clipboard.',
        'FTE14021': 'Failed to copy to the clipboard.',

        'FTE14022': 'AI Assistant',
        'FTE14023': 'Conversation',
        'FTE14024': 'Lessons',

        // Conversation history (conversation list)
        'FTE14025': 'Model',
        'FTE14026': 'Created',
        'FTE14028': 'Title',
        'FTE14029': 'Status',
        'FTE14030': 'Messages',
        'FTE14031': 'Tokens',
        'FTE14032': 'Conversation ID',
        'FTE14033': 'Resume',
        'FTE14034': 'Failed to retrieve the list.',

        // Resume conversation
        'FTE14035': 'The conversation cannot be resumed while the AI is responding.\nPlease wait until the response is finished, or stop it with the stop button, and then try again.',
        'FTE14036': 'This conversation has no history that can be restored.',
        'FTE14037': 'Failed to resume the conversation.',

        // Check conversation history
        'FTE14038': 'Failed to retrieve the history.',

        // Delete conversation
        'FTE14039': 'Delete conversation',
        'FTE14040': 'The selection includes a conversation for which the AI is responding, so it cannot be deleted.<br>Please wait until the response is finished, or stop it with the stop button, and then try again.',
        'FTE14041': function( num ){ return `The ${num} selected conversations will be deleted.\nTheir conversation histories will also be deleted and cannot be restored.\n\nAre you sure you want to delete them?`},
        'FTE14042': function( num ){ return `Failed to delete ${num} conversations.`},

        // Lessons (lesson list)
        'FTE14043': 'Content',
        'FTE14044': 'Category',
        'FTE14045': 'Priority',
        'FTE14046': 'Status',
        'FTE14047': 'Enabled',
        'FTE14048': 'Disabled',
        'FTE14049': 'Lesson ID',
        'FTE14050': 'Enable',
        'FTE14051': 'Disable',
        'FTE14052': function( max ){ return `Up to ${max} lessons can be registered.`},
        // If num is omitted, the current number is not included (when it is shown elsewhere, such as the table footer)
        'FTE14053': function( max, num ){ return `The number of lessons exceeds ${max}. `
            + (( num !== undefined && num !== null )? `(currently ${num}) `: '')
            + `Please delete unnecessary lessons and keep the number within ${max}.`},

        // Edit lesson
        'FTE14054': 'Edit lesson',
        'FTE14055': function( num ){ return `You can edit the content, category, priority and status. Of the enabled lessons, up to the ${num} with the highest priority are automatically given to the AI as prior knowledge in later sessions.`},
        'FTE14056': 'Enable',
        'FTE14057': 'Failed to update the lesson.',
        'FTE14058': function( value ){ return `${value} (highest)`},
        'FTE14059': function( value ){ return `${value} (lowest)`},

        // Enable or disable lessons
        'FTE14060': 'There is no lesson whose status can be changed.',
        'FTE14061': 'Failed to change the status of the lessons.',

        // Delete lesson
        'FTE14062': 'Delete lesson',
        'FTE14063': function( num ){ return `The ${num} selected lessons will be deleted.\nThey cannot be restored.\n\nAre you sure you want to delete them?`},
        'FTE14064': function( num ){ return `Failed to delete ${num} lessons.`},

        // Number of lessons given to the AI
        'FTE14065': function( num ){ return `Of the enabled lessons, only up to the ${num} with the highest priority are given to the AI.`},
        // Separator used when joining sentences. English needs a space after the period
        'FTE14066': ' ',

        // Register lesson (the register button in the lesson list)
        'FTE14067': 'Register lesson',
        'FTE14068': function( num ){ return `You can register a lesson by entering the content, category, priority and status. Of the enabled lessons, up to the ${num} with the highest priority are automatically given to the AI as prior knowledge in later sessions.`},
        'FTE14069': 'Failed to register the lesson.',

        // Edit the conversation title (conversation history tab)
        'FTE14070': 'Edit title',
        'FTE14071': 'You can change the title shown in the conversation list. This does not affect the conversation itself.',
        'FTE14072': 'Failed to update the title.',

        // Import and export (buttons in the list)
        'FTE14073': 'Import',
        'FTE14074': 'Export',

        // Export conversations
        'FTE14075': 'Export conversations',
        'FTE14076': function( num ){ return `The ${num} selected conversations will be exported to a JSON file together with their histories.\nThe conversation histories are fetched one at a time, so it takes a while when many are selected.\n\nAre you sure you want to start the export?`},
        // Progress (how many of the total have been processed)
        'FTE14077': function( num, total ){ return `${num} / ${total} records`},
        'FTE14078': function( num ){ return `The histories of ${num} conversations could not be fetched, so they are excluded from the export.`},
        'FTE14079': 'The export was stopped.<br>No file has been downloaded.',
        'FTE14080': 'There was nothing that could be exported.',

        // Export lessons
        'FTE14081': 'Export lessons',
        'FTE14082': function( num ){ return `The ${num} selected lessons will be exported to a JSON file.\n\nAre you sure you want to start the export?`},

        // Import conversations
        'FTE14083': 'Import conversations',
        'FTE14084': function( num ){ return `The ${num} conversations in the file will be imported.\nThey are registered as new conversations, so their creation and update dates are the date of the import, and the AI service and model are the ones in the AI settings.\nThe token count is counted for each request to the AI, so it is shown as unknown (a hyphen) for imported conversations.\n\nAre you sure you want to start the import?`},
        'FTE14085': 'The file contains no conversation that can be imported.<br>Please select an exported JSON file, or a conversation history JSON file downloaded from the check dialog.',
        'FTE14086': function( num ){ return `Failed to import ${num} conversations.`},
        // Title given to a file that contains only a history (the original title is unknown)
        'FTE14087': function( date ){ return `Imported history ${date}`},
        'FTE14088': 'No AI service is set, so conversations cannot be imported.<br>Please set an AI service and a model in the AI settings, and then try again.',
        'FTE14089': 'The import was stopped.<br>Whatever was registered before it stopped remains as it is.',

        // Import lessons
        'FTE14090': 'Import lessons',
        'FTE14091': function( num ){ return `The ${num} lessons in the file will be imported.\nThey are registered as new lessons, so their creation and update dates are the date of the import.\n\nAre you sure you want to start the import?`},
        'FTE14092': 'The file contains no lesson that can be imported.<br>Please select an exported JSON file.',
        'FTE14093': function( num ){ return `Failed to import ${num} lessons.`},

        // 一覧のトークン数が記録されていない場合の表示（ハイフン）に添える説明
        'FTE14094': 'The token count has not been recorded because there has been no request to the AI.',

        // AI assistant (HTML display tool)
        'FTE14105': 'The HTML has been displayed on the screen of the user (chat area). Only the user can view this content, and it is not returned to the LLM.',
        'FTE14106': 'Download PDF',
        'FTE14107': 'AI assistant display content',

        // AI assistant (communication with the AI service and conversation management)
        'FTE14110': 'No title',
        'FTE14111': 'No AI service to use is selected.',
        'FTE14112': 'No model to use is selected.',
        'FTE14113': 'Failed to create the conversation.',
        'FTE14114': 'No conversation ID is specified.',
        'FTE14115': 'No conversation title is specified.',
        'FTE14116': 'Title generation',
        'FTE14117': 'Failed to create the conversation used to generate the title.',
        'FTE14118': function( transcript ){ return `Please give a title to the following conversation.\n\n----\n${transcript}\n----`},
        'FTE14119': 'Lessons',
        'FTE14120': 'Failed to create the conversation used to extract the lessons.',
        'FTE14121': function( transcript ){ return `Please extract the lessons from the following conversation.\n\n----\n${transcript}\n----`},
        'FTE14122': 'No lesson content is specified.',
        'FTE14123': 'No lesson ID is specified.',
        'FTE14124': 'No lesson to enable or disable is specified.',
        'FTE14125': function( status ){ return `The response timed out (HTTP ${status}).\nDo you want to try again?`},
        'FTE14126': 'The retry was stopped because of the timeout.',

        // AI assistant (text passed to the AI as the information of the attached files)
        'FTE14127': 'The information of the attached files is as follows.',
        'FTE14128': 'Not supported (the AI cannot directly analyze the content of this format)',
        'FTE14129': 'Analysis off (the format is supported, but the content is not passed because the user has turned off "Analyze with AI")',
        'FTE14130': 'Analysis on (the content of the file is passed)',
        'FTE14131': function( fileId, filename, mimeType, size, state ){ return `the file_id is ${fileId}, the file name is ${filename}, the MIME type is ${mimeType}, the file size is ${size}, and the analysis state is "${state}"`},
        'FTE14132': '[Instructions for handling the attached files]\n- If the user asks about the content of an attached file (for example: check the content / summarize it / confirm the content) while the analysis state of that file is "Analysis off", do not answer the content by guessing. Answer that analysis with AI is off for the file and that the user has to turn on "Analyze with AI" for the file and send it again.\n- If you are asked about the content of a file whose analysis state is "Not supported", answer that the AI cannot directly analyze the content of that file format (MIME type).\n- For a file whose analysis state is "Analysis on", answer based on the content that was passed.\n- The attached files themselves are already registered in ITA. When you use a tool that handles files, such as reading or processing the content of a file or registering it in ITA, specify the file_id above as the argument as it is (do not invent a file_id).',
        'FTE14133': 'The AI requested the execution of a tool, but it cannot be executed because the response of the AI service does not contain the content of the tool call (tool_use block).',

        // AI assistant (AI service settings)
        'FTE14140': 'Please paste the whole content of the login cache of the AWS CLI (~/.aws/login/cache/*.json).',
        'FTE14141': 'Valid',
        'FTE14142': 'Expired',
        'FTE14143': 'Disabled',
        'FTE14144': 'Failed to get the Credential.',
        'FTE14145': 'AI service settings',
        'FTE14146': 'Apply',
        'FTE14147': 'Could not get the information of the AI service.',
        'FTE14148': 'Add an AI service',
        'FTE14149': 'No AI service is registered.',
        'FTE14150': 'Please register the authentication information of the AI service you use.',
        'FTE14151': 'The AI service to use cannot be changed during a conversation. The authentication information can be updated.',
        'FTE14152': 'Please select the AI service to use and apply it.',
        'FTE14153': 'Registered AI services',
        'FTE14154': function( num ){ return `${num} items`},
        'FTE14155': function( date ){ return `Expiration date: ${date}`},
        'FTE14156': function( date ){ return `Last used: ${date}`},
        'FTE14157': 'In use',
        'FTE14158': 'Model',
        'FTE14159': 'Update',
        'FTE14160': 'Check the authentication',
        'FTE14161': 'Delete',
        'FTE14162': 'No model is selected. Please select a model from Model.',
        'FTE14163': 'Pickup models',
        'FTE14164': 'Default model',
        'FTE14165': 'Could not get the registration status of some AI services.',
        'FTE14166': 'Application of the AI service',
        'FTE14167': 'The AI service to use cannot be changed during a conversation.<br>Please start a new chat before changing it.',
        'FTE14168': 'Please select the AI service to use.',
        'FTE14169': 'No model is selected.<br>Please select the model to use from "Model".',
        'FTE14170': function( name ){ return `${name} will be applied as the AI service to use.\n\nAre you sure you want to apply it?`},
        'FTE14171': function( message ){ return `Failed to apply the AI service.<br>${message}`},
        'FTE14172': 'Connection check',
        'FTE14173': 'The authentication information is valid.',
        'FTE14174': function( id ){ return `Account ID: ${id}`},
        'FTE14175': function( message ){ return `The authentication information is invalid.<br>${message}`},
        'FTE14176': function( message ){ return `Failed to check the connection.<br>${message}`},
        'FTE14177': 'Deletion of the AI service',
        'FTE14178': 'This AI service is in use. If you delete it, the settings of the applied AI service are also reset.',
        'FTE14179': function( name ){ return `Do you want to delete ${name}?`},
        'FTE14180': function( message ){ return `Failed to delete.<br>${message}`},
        'FTE14181': 'Update of the AI service',
        'FTE14182': 'Addition of the AI service',
        'FTE14183': 'Update',
        'FTE14184': 'Register',
        'FTE14185': 'There is no AI service that can be added.<br>Please update the registered AI services.',
        'FTE14186': function( message ){ return `Could not read the file.<br>${message}`},
        'FTE14187': 'AI service',
        'FTE14188': 'Credential name',
        'FTE14189': 'Authentication information',
        'FTE14190': 'There is no authentication information to enter for this AI service.',
        'FTE14191': 'Registered tokens and keys are not displayed. To update them, please enter them again.',
        'FTE14192': 'Select a file and read it',
        'FTE14193': 'Please select an AI service.',
        'FTE14194': 'Please enter the Credential name.',
        'FTE14195': function( modeText, message ){ return `Failed to ${modeText} the AI service.<br>${message}`},
        'FTE14196': 'Updated',
        'FTE14197': 'Registered',
        'FTE14198': function( savedText, message ){ return `${savedText}, but the verification of the authentication information failed.<br>${message}`},
        'FTE14199': 'The authentication information cannot be registered for this AI service.',
        'FTE14200': function( title ){ return `Please enter ${title}.`},
        'FTE14201': 'Please enter the authentication information.',
        'FTE14202': function( title, message ){ return `${title} is not in JSON format.<br>${message}`},
        'FTE14203': function( title ){ return `For ${title}, please paste a JSON enclosed in { }.`},
        'FTE14204': function( title, keys ){ return `${title} does not contain the following items.<br>${keys}`},
        'FTE14205': 'Model selection',
        'FTE14206': 'Set',
        'FTE14207': 'Could not get the model list.',
        'FTE14208': 'There is no model available.',
        'FTE14209': 'Please check the inference profiles available in the AWS account linked to the authentication information.',
        'FTE14210': 'Please select the models that can be switched in the chat.',
        'FTE14211': 'Filter by model name or model ID',
        'FTE14212': 'There is no matching model.',
        'FTE14213': 'Please select the model that is selected first from the pickup models.',
        'FTE14214': 'Please select the pickup models.',
        'FTE14215': 'Others',
        'FTE14216': 'Please select the default model.',
        'FTE14217': function( message ){ return `Failed to set the model.<br>${message}`},
        'FTE14218': function( message ){ return `The model was set, but the application of the AI service failed.<br>${message}<br>Please select the AI service to use in the list and apply it.`},

        // AI assistant (chat screen)
        'FTE14230': function( message ){ return `Could not get the list of tools used to operate ITA.<br>You can still talk with the AI, but the AI assistant cannot operate ITA.<br>${message}`},
        'FTE14231': 'Failed to get the user ID.',
        'FTE14232': 'Failed to load the script. (markdownit)',
        'FTE14233': function( status ){ return `This execution was monitored on the server side until completion and has already finished with the final status "${status}". Do not call execute-driver / dryrun-driver / get-driver-status again. Report this final status to the user and end the conversation.`},
        'FTE14234': function( reason ){ return `The progress monitoring on the server side ended before it reached the final status (reason: ${reason}). The execution itself has already started, so you must not run execute-driver / dryrun-driver again. Report the situation to the user and, if necessary, suggest checking the status manually.`},
        'FTE14235': function( num ){ return `Open the list narrowed down to the ${num} updated records`},
        'FTE14236': function( message ){ return `Could not load the AI usage settings.<br>${message}`},
        'FTE14237': function( name ){ return `the AI service (${name})`},
        'FTE14238': 'the AI service',
        'FTE14239': function( service ){ return `Failed to authenticate ${service}.\nThe authentication information may have expired.\nPlease update the authentication information from "AI service settings".`},
        'FTE14240': 'The authentication information has been updated. You can send the rest of the conversation.',
        'FTE14241': 'New chat',
        'FTE14242': 'End chat',
        'FTE14243': 'AI service settings',
        'FTE14244': 'Model',
        'FTE14245': 'Not selected',
        'FTE14246': function( message ){ return `Could not start the conversation.<br>${message}`},
        'FTE14247': 'Please enter your request.',
        'FTE14248': 'Attach a file',
        'FTE14249': 'Send',
        'FTE14250': 'Stop',
        'FTE14251': 'Good morning.',
        'FTE14252': 'Hello.',
        'FTE14253': 'Good evening.',
        'FTE14254': 'Thank you for working until so late.',
        'FTE14255': 'This is the Exastro AI assistant.',
        'FTE14256': '<br>How can I help you?',
        'FTE14257': function( name ){ return `Failed to authenticate the AI service (${name}).<br>The authentication information may have expired.<br>Please update your authentication information from "AI service settings".`},
        'FTE14258': 'The preparation for use is not complete.<br>Please complete the settings from "AI service settings".',
        'FTE14259': 'The answers and the operation results of the AI are not guaranteed to be accurate or complete. For operations performed through the AI assistant, check the content and the scope of the impact before the execution, and check that the result is in the intended state after the execution as well.',
        'FTE14260': 'Edit',
        'FTE14261': 'Preview',
        'FTE14262': 'When this is on, the AI reads and analyzes the content of the file',
        'FTE14263': 'Analyze with AI',
        'FTE14264': 'Delete',
        'FTE14265': function( status ){ return `Failed to register the attached file (HTTP ${status}).`},
        'FTE14266': 'Could not connect to the server. Please check the network connection and try again in a while.',
        'FTE14267': 'Rewind to this point',
        'FTE14268': 'Copy to the clipboard',
        'FTE14269': 'Set in the input field',
        'FTE14270': 'Please select an answer with a button, or write it directly in the input field below.',
        'FTE14271': 'Thinking',
        'FTE14272': 'Running a tool',
        'FTE14273': '(This option was processed together with the others.)',
        'FTE14274': 'Processing the attached files',
        'FTE14275': function( message ){ return `Failed to upload the file.\n\n${message}`},
        'FTE14276': 'The preparation for use is not complete. Please complete the settings from "AI service settings".',

        // AI assistant (instructions to resend when a response is cut off by the output limit or has a wrong format)
        'FTE14277': function( retries, max ){ return `Splitting the response and creating it again... (retry ${retries}/${max})`},
        'FTE14278': 'The previous response reached the upper limit of the amount that can be output at one time, and the arguments of the tool call were cut off. Instead of outputting the same content again at one time, please split the output as follows.\n- When you use display_html, do not pass the whole report at one time. Call it several times, section by section (for example: overview / work details / metrics). Use about 3000 characters of HTML per call as a guide.\n- Make the HTML of each call complete on its own (always include the root <div class="exa-report"> and the <style> of the design tokens).\n- Remove decoration and comments, and write it shorter while keeping the main points of the content.\n- Keep the explanation on the text side to a short introduction and supplement only.',
        'FTE14279': 'The previous response reached the upper limit of the amount that can be output at one time and was cut off. Instead of outputting the same content again at one time, please narrow it down to the main points and summarize it briefly, and if a continuation is needed, split the output into several responses.',
        'FTE14280': 'The response from the AI reached the output limit of one response, so the content was cut off.\nPlease narrow down the target (for example, split the report section by section) and try again.',
        'FTE14281': function( retries, max ){ return `Adjusting the response... (retry ${retries}/${max})`},
        'FTE14282': 'In the previous response you output the tool call as text (tags such as <invoke> or <parameter>), which is wrong. Do not write tags such as invoke / parameter / function_calls, or any part of them, as text. Always use the tool_use function to call the tool again.',
        'FTE14283': 'We are sorry. The processing could not be performed correctly. Please send the previous instruction again.',
        'FTE14284': 'The parameter format of the previous ask_user_choice call was wrong. Put all the options together in one array named options, and make each element an object of the form {"label": "text to display", "action": "positive|negative|other"}. You must not put label or action outside options, make options a string, or call ask_user_choice separately for each option. Please call ask_user_choice again only once, in the correct format.',
        'FTE14285': 'The responses from the LLM exceeded the specified number of times. The loop ends.',

        // AI assistant (progress monitoring and work status of a driver execution)
        'FTE14286': 'The progress monitoring was interrupted',
        'FTE14287': 'The progress check timed out',
        'FTE14288': 'Failed to check the progress',
        'FTE14289': 'Check the work status',
        'FTE14290': 'Result data',
        'FTE14291': 'Waiting',
        'FTE14292': 'The Driver or the execution No. is unknown.',
        'FTE14293': 'Failed to perform the emergency stop.',

        // AI assistant (restoring and rewinding a conversation)
        'FTE14294': 'The format of the history is invalid.',
        'FTE14295': 'The format of the conversation ID is invalid.',
        'FTE14296': 'The conversation cannot be resumed because the preparation for use is not complete.',
        'FTE14297': 'The conversation will be rewound to this point. The exchanges after this point are deleted from the conversation.\n\n[Note] The work actually performed in ITA (Exastro) up to this point (creating or updating menus, running drivers, and so on) is not undone. Only the display of the conversation and the memory of the AI (the conversation history) are rewound.\n\nAre you sure you want to rewind it?',
        'FTE14298': '(The result of this operation was discarded because the conversation was rewound.)',
        'FTE14299': 'Stopped because the page was left.<br>The work status cannot be checked from this screen because the execution No. is not recorded. The execution may be continuing or may already have finished on the server side, so please check the status in the list of the execution history and so on.',
        'FTE14300': 'Stopped because the page was left.<br>The execution may be continuing or may already have finished on the server side. Please check the latest status with "Check the work status".',
        'FTE14301': 'Ended without being able to determine the execution status.<br>Please check the latest status with "Check the work status".',
        'FTE14302': '(This operation was interrupted because the page was left. It may already have been executed on the server side. Do not carelessly run the same operation again. If necessary, check the current status and then report it to the user.)',
        'FTE14303': function( message ){ return `There is a conversation that was interrupted last time, but it cannot be resumed because the authentication does not pass.\n\n${message}`},
        'FTE14304': 'The previous conversation has been restored. If you answer the options above, you can resume from there.',
        'FTE14305': 'The previous conversation has been restored.',
        'FTE14306': 'The page was closed in the middle of the work last time.',
        'FTE14307': 'There is work that was interrupted last time. Do you want to resume it?\n\nIf you select "Yes", the AI resumes the processing (operations on ITA (Exastro) and token consumption may occur).\nIf you select "No", the conversation stays in the restored state and you can continue it manually.',
        'FTE14308': 'The sending has been stopped',

        // AI assistant (new chat and end of the chat)
        'FTE14309': 'A new chat cannot be started because the AI is responding.\nPlease try again after the response finishes, or after you stop it with the stop button.',
        'FTE14310': 'The chat cannot be ended because the AI is responding.\nPlease try again after the response finishes, or after you stop it with the stop button.',
        'FTE14311': 'The chat has ended. The selected processing will be performed.',
        'FTE14312': 'This chat has ended. To continue the conversation, please send a message.',
        'FTE14313': 'This chat has ended. (The processing at the end was not performed.) To continue the conversation, please send a message.',
        'FTE14314': 'End of the chat',
        'FTE14315': 'End',
        'FTE14316': 'Cancel',
        'FTE14317': 'Do not create a report',
        'FTE14318': 'Create a work report (Markdown)',
        'FTE14319': 'Create a graphical report (HTML)',
        'FTE14320': 'The chat will be ended. Please select the processing to perform at the end.<br>If you select nothing, the chat ends without any processing.',
        'FTE14321': 'Create a summary of the conversation',
        'FTE14322': 'Register the lessons<br>(handover to the next session / you can check the content before registering them)',
        'FTE14323': 'Have the AI give a title to this chat<br>(the title displayed in the list of the conversation history is set again from the content of the conversation)',

        // AI assistant (instructions passed to the AI when the chat ends)
        'FTE14324': [
            '[Summary of the conversation]',
            'Please briefly summarize the request of the user and the work performed for it.'
        ],
        'FTE14325': [
            '[Work report (Markdown)]',
            'Please create a quality report of the work performed, in Markdown. Include the following points.',
            '- What kind of work was performed: the request of the user and the content of the work performed for it.',
            '- What changes occurred in the system: the menus and data created, updated, or deleted, the work performed, and other impacts on ITA (Exastro).',
            '- What the result of the work was: whether it succeeded or failed, and the work log that is the basis for it (the tools and processes that were run and their results, and so on).',
            '- Quantitative analysis: the number of pieces of work performed, the number of successes and failures, the number of calls of the tools and processes used, and other metrics that can be shown as numbers, as far as possible.',
            '- Qualitative analysis: an evaluation from the viewpoint of the accuracy, the coverage, and the efficiency of the work, and what went well, the issues, and the points to improve.',
            '- Supplement: the points that were hard to judge, and the matters that the user needs to check or handle.'
        ],
        'FTE14326': [
            '[Graphical report (HTML)]',
            'Please use the display_html tool to create a graphical report in HTML with which the work of this time can be grasped visually.',
            '- What kind of work was performed: the request of the user and the content of the work performed for it.',
            '- What changes occurred in the system: the menus and data created, updated, or deleted, the work performed, and other impacts on ITA (Exastro).',
            '- What the result of the work was: whether it succeeded or failed, and the work log that is the basis for it (the tools and processes that were run and their results, and so on).',
            '- Quantitative analysis: the number of pieces of work performed, the number of successes and failures, the number of calls of the tools and processes used, and other metrics that can be shown as numbers, as far as possible.',
            '- Qualitative analysis: an evaluation from the viewpoint of the accuracy, the coverage, and the efficiency of the work, and what went well, the issues, and the points to improve.',
            '- Supplement: the points that were hard to judge, and the matters that the user needs to check or handle.'
        ],
        'FTE14327': '- Please create the design as follows. Use rich expressions that are hard to express in normal Markdown, such as a card layout, diagrams, and charts. Do not make the appearance different every time. Always follow the common design guidelines shown in the description of the display_html tool (the design tokens, the cards, the stat cards, and the color rules), and output a design with a unified look.',
        'FTE14328': '- Please observe the following about the volume. Because there is an upper limit to the amount that can be output in one response, do not pass the whole report in one display_html. Split it section by section, such as "overview and metrics", "work details", and "analysis and supplement", and call display_html several times. Use about 3000 characters of HTML per call as a guide, and make the HTML of each call complete on its own (always include the root <div class="exa-report"> and the <style> of the design tokens).',
        'FTE14329': [
            'The conversation will be ended. As the conclusion of this conversation, please create the following selected content.',
            'Base it only on what was actually done in this conversation. Do not inflate the work results with guesses, and do not state numbers that cannot be confirmed as if they were facts.'
        ],

        // AI assistant (the thinking time totals passed to the AI as the basis data)
        'FTE14330': '(Unknown)',
        'FTE14331': function( toolNames ){ return `Tool call: ${toolNames}`},
        'FTE14332': '(No content)',
        'FTE14333': '[Thinking time data (measured values; use the following numbers as they are)]',
        'FTE14334': function( count ){ return `- Number of LLM responses: ${count}`},
        'FTE14335': function( sec ){ return `- Total thinking time: ${sec} sec`},
        'FTE14336': function( sec ){ return `- Average thinking time: ${sec} sec/response`},
        'FTE14337': function( min, max ){ return `- Shortest: ${min} sec / Longest: ${max} sec`},
        'FTE14338': '- Responses that took especially long (slowest first):',
        'FTE14339': function( order, sec, model, label ){ return `    - Response No. ${order} (${sec} sec / model: ${model}): ${label}`},
        'FTE14340': '- Thinking time by model (slowest average first):',
        'FTE14341': function( model, count, avg, min, max ){ return `    - ${model}: ${count} responses, average ${avg} sec (shortest ${min} sec / longest ${max} sec)`},
        'FTE14342': function( modelNote ){ return `Always include this thinking time data in the "Quantitative analysis" of the report. Also mention which responses took long and with which model they were generated. ${modelNote}The above are measured values. Quote them as they are, without changing them or filling them in with guesses. Note that the thinking time is the round-trip time of the LLM response and does not include the execution time of the tools.`},
        'FTE14343': 'Because the model was changed during the conversation, also mention the tendency of slow and fast by model. ',

        // AI assistant (extracting and registering the lessons)
        'FTE14344': 'There was no lesson that should be recorded from this conversation.',
        'FTE14345': 'Extracting the lessons',
        'FTE14346': function( message ){ return `Failed to extract the lessons.\n${message}`},
        'FTE14347': 'The registration of the lessons was cancelled.',
        'FTE14348': 'Nothing was recorded because no lesson to register was selected.',
        'FTE14349': function( num, errors ){ return `\n${num} lessons could not be recorded.\n${errors}`},
        'FTE14350': function( num ){ return `${num} lessons have been recorded. They are automatically reflected as prior knowledge for the AI in the following sessions.\n`},
        'FTE14351': 'The lessons could not be recorded.',
        'FTE14352': 'Assistant',
        'FTE14353': 'User',
        'FTE14354': '... (omitted) ...',
        'FTE14355': 'Confirmation of the lesson registration',
        'FTE14356': 'Register',
        'FTE14357': 'Register',
        'FTE14358': 'Category',
        'FTE14359': 'Importance',
        'FTE14360': 'Content of the lesson',
        'FTE14361': function( max ){ return `The following lessons were extracted from this conversation. Select the items to register, and correct the content, the category, and the importance (1 to 10) if necessary. The registered content is automatically reflected as prior knowledge for the AI in the following sessions (up to the ${max} lessons with the highest importance among the enabled lessons).`},
        'FTE14362': 'Select all',
        'FTE14363': function( count ){ return `${count} items to register`},
        'FTE14364': 'Recording the lessons',
        'FTE14365': function( head, message ){ return `- ${head}: ${message}`},

        // AI assistant (generating the title of the conversation)
        'FTE14366': 'A title could not be given because this conversation has not been saved yet.',
        'FTE14367': 'A title could not be given because there is no conversation content to base the title on.',
        'FTE14368': 'Generating the title of the conversation',
        'FTE14369': function( message ){ return `Failed to generate the title.\n${message}`},
        'FTE14370': 'The title could not be generated.',
        'FTE14371': function( message ){ return `Failed to save the title.\n${message}`},
        'FTE14372': function( title ){ return `The title of this conversation has been set to "${title}".\nThe title is displayed in the list of the conversation history (you can edit it from the conversation history tab).`},

        // AI assistant (file editor)
        'FTE14380': 'Open the AI assistant',
        'FTE14381': 'Close the AI assistant',
        'FTE14382': 'Loading the AI assistant',
        'FTE14383': 'Failed to open the AI assistant.',
        'FTE14384': 'Attach the file being edited',

        // LLM Editor(Playbook reflection)
        'FTE14390': 'Reflection',
        'FTE14391': 'Reflection difference',
        'FTE14392': 'Apply',
        'FTE14393': 'Cancel',

        //gemini
        'FTE14101': 'API KEY',
        'FTE14102': 'Model Selection',
        'FTE14103': 'Model initial values',
        'FTE14104': ['You are an AI assistant that will respond in English.','Questions other than translation will be answered in English, even if they are not in English.'],
    };

    return message;

}