-- 2.10.0: OASE Master Data Migration

-- ------------------------------------------------------------
-- T_COMN_MENU_COLUMN_LINK: INSERT - Add Action Result Column
-- ------------------------------------------------------------
-- 評価結果メニュー(110110)に「アクション結果」カラムを追加
INSERT IGNORE INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('11011028','110110','アクション結果','Action Result','action_result',NULL,'2',65,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'ACTION_RESULT',NULL,'0','1','1','0','0','1','0',NULL,NULL,NULL,NULL,NULL,'アクションの起動・実行時の詳細を表示します。','Displays action execution results and details.',NULL,'0',_____DATE_____,1);
INSERT IGNORE INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('11011028',_____DATE_____,'INSERT','11011028','110110','アクション結果','Action Result','action_result',NULL,'2',65,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'ACTION_RESULT',NULL,'0','1','1','0','0','1','0',NULL,NULL,NULL,NULL,NULL,'アクションの起動・実行時の詳細を表示します。','Displays action execution results and details.',NULL,'0',_____DATE_____,1);


-- ------------------------------------------------------------
-- T_OASE_ACTION_STATUS: INSERT - Add Launch Failed Status
-- ------------------------------------------------------------
-- アクションステータスに「起動失敗」を追加
INSERT IGNORE INTO T_OASE_ACTION_STATUS (ACTION_STASTUS_ID,ACTION_STASTUS_NAME_JA,ACTION_STASTUS_NAME_EN,DISP_SEQ,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('11','起動失敗','Launch failed',110,NULL,'0',_____DATE_____,1);

