-- ------------------------------------------------------------
-- T_COMN_MENU: ALTER TABLE
-- ------------------------------------------------------------
SET @exist := (
    SELECT COUNT(*)
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE table_schema = DATABASE()
      AND table_name   = 'T_COMN_MENU'
      AND column_name  = 'EXPORT_PERMISSION_CHECK_FLG'
);
SET @sql := IF(@exist = 0,
    'ALTER TABLE T_COMN_MENU ADD COLUMN EXPORT_PERMISSION_CHECK_FLG VARCHAR(2) AFTER SORT_KEY',
    'SELECT 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

SET @exist := (
    SELECT COUNT(*)
    FROM INFORMATION_SCHEMA.COLUMNS
    WHERE table_schema = DATABASE()
      AND table_name   = 'T_COMN_MENU_JNL'
      AND column_name  = 'EXPORT_PERMISSION_CHECK_FLG'
);
SET @sql := IF(@exist = 0,
    'ALTER TABLE T_COMN_MENU_JNL ADD COLUMN EXPORT_PERMISSION_CHECK_FLG VARCHAR(2) AFTER SORT_KEY',
    'SELECT 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- T_COMN_MENU にカラム追加
SET @exist := (
    SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'T_COMN_MENU'
    AND COLUMN_NAME = 'SHOW_IN_MENU'
);
SET @sql := IF(@exist = 0,
    'ALTER TABLE T_COMN_MENU ADD COLUMN SHOW_IN_MENU VARCHAR(2) AFTER EXPORT_PERMISSION_CHECK_FLG',
    'SELECT 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- T_COMN_MENU_JNL にカラム追加
SET @exist := (
    SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'T_COMN_MENU_JNL'
    AND COLUMN_NAME = 'SHOW_IN_MENU'
);
SET @sql := IF(@exist = 0,
    'ALTER TABLE T_COMN_MENU_JNL ADD COLUMN SHOW_IN_MENU VARCHAR(2) AFTER EXPORT_PERMISSION_CHECK_FLG',
    'SELECT 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- ------------------------------------------------------------
-- T_COMN_MENU_COLUMN_LINK: ALTER TABLE
-- ------------------------------------------------------------

-- T_COMN_MENU_COLUMN_LINK にカラム追加
SET @exist := (
    SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'T_COMN_MENU_COLUMN_LINK'
    AND COLUMN_NAME = 'DISP_SETTING_JSON'
);
SET @sql := IF(@exist = 0,
    'ALTER TABLE T_COMN_MENU_COLUMN_LINK ADD COLUMN DISP_SETTING_JSON LONGTEXT AFTER DESCRIPTION_EN',
    'SELECT 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;

-- T_COMN_MENU_COLUMN_LINK_JNL にカラム追加
SET @exist := (
    SELECT COUNT(*) FROM INFORMATION_SCHEMA.COLUMNS
    WHERE TABLE_SCHEMA = DATABASE()
    AND TABLE_NAME = 'T_COMN_MENU_COLUMN_LINK_JNL'
    AND COLUMN_NAME = 'DISP_SETTING_JSON'
);
SET @sql := IF(@exist = 0,
    'ALTER TABLE T_COMN_MENU_COLUMN_LINK_JNL ADD COLUMN DISP_SETTING_JSON LONGTEXT AFTER DESCRIPTION_EN',
    'SELECT 1'
);
PREPARE stmt FROM @sql;
EXECUTE stmt;
DEALLOCATE PREPARE stmt;
