-- Issue#3079: Agentic AI用に新しいシートタイプを追加
INSERT IGNORE INTO T_COMN_SHEET_TYPE (SHEET_TYPE_NAME_ID,SHEET_TYPE_NAME_JA,SHEET_TYPE_NAME_EN,MENU_CREATE_TARGET_FLAG,DISP_SEQ,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(29,'AIアシスタント','AI Assistant','0',29,NULL,'0',_____DATE_____,1);

-- エクスポート権限チェックのカラム定義を追加
INSERT IGNORE INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('1010318','10103','エクスポート権限チェック','EXPORT_PERMISSION_CHECK_FLG','export_permission_check_flg',NULL,'7',135,'T_COMN_BOOLEAN_FLAG','FLAG_ID','FLAG_NAME',NULL,'0',NULL,NULL,NULL,NULL,'EXPORT_PERMISSION_CHECK_FLG',NULL,'0','1','1','0','1','1','0',NULL,NULL,NULL,NULL,NULL,'プルダウン選択 必須項目
True: する
False: しない','Pull-down selection  required item
True: Required
False: Not required',NULL,'0',_____DATE_____,1);
INSERT IGNORE INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(1010318,_____DATE_____,'INSERT','1010318','10103','エクスポート権限チェック','EXPORT_PERMISSION_CHECK_FLG','export_permission_check_flg',NULL,'7',135,'T_COMN_BOOLEAN_FLAG','FLAG_ID','FLAG_NAME',NULL,'0',NULL,NULL,NULL,NULL,'EXPORT_PERMISSION_CHECK_FLG',NULL,'0','1','1','0','1','1','0',NULL,NULL,NULL,NULL,NULL,'プルダウン選択 必須項目
True: する
False: しない','Pull-down selection  required item
True: Required
False: Not required',NULL,'0',_____DATE_____,1);
