-- Issue#2961: 重複排除設定メニュー(110111)に登録後バリデーション(external_valid_menu_after)を紐付ける
UPDATE T_COMN_MENU_TABLE_LINK       SET AFTER_VALIDATE_REGISTER = 'external_valid_menu_after', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE TABLE_DEFINITION_ID = '110111';
UPDATE T_COMN_MENU_TABLE_LINK_JNL   SET AFTER_VALIDATE_REGISTER = 'external_valid_menu_after', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE TABLE_DEFINITION_ID = '110111';

-- Issue#2961: 既存の有効な重複排除設定に対して、1行ロック用のロックキーを事前登録する
INSERT INTO T_COMN_RECODE_LOCK_TABLE (TABLE_NAME) SELECT CONCAT('OASE_DEDUPLICATION_', DEDUPLICATION_SETTING_ID) FROM T_OASE_DEDUPLICATION_SETTINGS WHERE DISUSE_FLAG = '0';
