-- - AAP2.5対応
UPDATE T_COMN_MENU SET MENU_NAME_JA = 'Ansible Automation Platform ノード一覧', MENU_NAME_EN = 'Ansible Automation Platform node list' WHERE MENU_ID = '20103';
UPDATE T_COMN_MENU_JNL SET MENU_NAME_JA = 'Ansible Automation Platform ノード一覧', MENU_NAME_EN = 'Ansible Automation Platform node list' WHERE MENU_ID = '20103';

UPDATE T_COMN_MENU_TABLE_LINK SET MENU_INFO_JA='Ansible Automation Platformのノード情報をメンテナンス(閲覧/登録/更新/廃止)できます。
クラスター構成で構築されている場合、クラスター内のホップノードを除いたノード情報を登録して下さい。クラスター構成でない場合は、対象ノード(1台)の情報を登録して下さい。', MENU_INFO_EN='Maintenance (view/update) can be performe Ansible Automation Platform Node information. case of cluster configuration, If constructed with a cluster configuration, register the node information(excluding the hop node within the cluster). If it is not constructed with a cluster configuration, register information for the target node (for 1 node).' WHERE MENU_ID='20103';
UPDATE T_COMN_MENU_TABLE_LINK_JNL SET MENU_INFO_JA='Ansible Automation Platformのノード情報をメンテナンス(閲覧/登録/更新/廃止)できます。
クラスター構成で構築されている場合、クラスター内のホップノードを除いたノード情報を登録して下さい。クラスター構成でない場合は、対象ノード(1台)の情報を登録して下さい。', MENU_INFO_EN='Maintenance (view/update) can be performe Ansible Automation Platform Node information. case of cluster configuration, If constructed with a cluster configuration, register the node information(excluding the hop node within the cluster). If it is not constructed with a cluster configuration, register information for the target node (for 1 node).' WHERE MENU_ID='20103';

UPDATE T_COMN_MENU_COLUMN_LINK SET DESCRIPTION_JA = 'ITAと接続するAnsible Automation Controller/Platform Gatewayのホスト名です。
Ansible Automation Platform ノード一覧に登録されているAnsible Automation Controller/Platform Gatewayより選択します。', DESCRIPTION_EN = 'The host name of the Ansible Automation Controller/Platform Gateway that connects to ITA.Select from the nodes of Ansible Automation Controller/Platform Gateway registered in node list.' 
WHERE COLUMN_DEFINITION_ID = '2010203';

UPDATE T_COMN_MENU_COLUMN_LINK_JNL SET DESCRIPTION_JA = 'ITAと接続するAnsible Automation Controller/Platform Gatewayのホスト名です。
Ansible Automation Platform ノード一覧に登録されているAnsible Automation Controller/Platform Gatewayより選択します。', DESCRIPTION_EN = 'The host name of the Ansible Automation Controller/Platform Gateway that connects to ITA.Select from the nodes of Ansible Automation Controller/Platform Gateway registered in node list.' WHERE COLUMN_DEFINITION_ID = '2010203';

UPDATE T_COMN_MENU_COLUMN_LINK SET DESCRIPTION_JA = 'Ansible Automation Controller/Platform Gatewayの接続ポートを入力します。
通常は443です。', DESCRIPTION_EN = 'Ansible Automation Controller/Platform Gateway server connection port.\nNormal is 443.' 
WHERE COLUMN_DEFINITION_ID = '2010205';
UPDATE T_COMN_MENU_COLUMN_LINK_JNL SET DESCRIPTION_JA = 'Ansible Automation Controller/Platform Gatewayの接続ポートを入力します。
通常は443です。', DESCRIPTION_EN = 'Ansible Automation Controller/Platform Gateway server connection port.
Normal is 443.' WHERE COLUMN_DEFINITION_ID = '2010205';

UPDATE T_COMN_MENU_COLUMN_LINK SET DESCRIPTION_JA = 'Ansible Automation Platformに登録されている組織名を入力します。', DESCRIPTION_EN = 'Enter the Organization name registered in Ansible Automation Platform.' WHERE COLUMN_DEFINITION_ID = '2010206';
UPDATE T_COMN_MENU_COLUMN_LINK_JNL SET DESCRIPTION_JA = 'Ansible Automation Platformに登録されている組織名を入力します。', DESCRIPTION_EN = 'Enter the Organization name registered in Ansible Automation Platform.' WHERE COLUMN_DEFINITION_ID = '2010206';

UPDATE T_COMN_MENU_COLUMN_LINK SET DESCRIPTION_JA = 'ITAからRestAPIでAnsible Automation Controller/Platform Gatewayに接続するユーザの認証トークンを入力します。', DESCRIPTION_EN = 'A user authentication token for connecting to Ansible Automation Controller/Platform Gateway from astrol using RestAPI. Enter the token generated by Ansible Automation Controller. Enter the token generated by Ansible Automation Controller.' WHERE COLUMN_DEFINITION_ID = '2010207';
UPDATE T_COMN_MENU_COLUMN_LINK_JNL SET DESCRIPTION_JA = 'ITAからRestAPIでAnsible Automation Controller/Platform Gatewayに接続するユーザの認証トークンを入力します。', DESCRIPTION_EN = 'A user authentication token for connecting to Ansible Automation Controller/Platform Gateway from astrol using RestAPI. Enter the token generated by Ansible Automation Controller. Enter the token generated by Ansible Automation Controller.' WHERE COLUMN_DEFINITION_ID = '2010207';

UPDATE T_COMN_MENU_COLUMN_LINK SET DESCRIPTION_JA = 'Ansible Automation Controller/Platform GatewayへのRestAPI発行時のタイムアウト値を60～3600の範囲で入力します。
通常は60秒程度が推奨値です。
空白の場合は、デフォルト値(60)を使用します。', DESCRIPTION_EN = 'Enter a timeout value between 60 and 3600 for issuing RestAPI to the Ansible Automation Controller/Platform Gateway.
60 seconds is the recommended value.
If blank, the default value (60) will be used.' WHERE COLUMN_DEFINITION_ID = '2010208';
UPDATE T_COMN_MENU_COLUMN_LINK_JNL SET DESCRIPTION_JA = 'Ansible Automation Controller/Platform GatewayへのRestAPI発行時のタイムアウト値を60～3600の範囲で入力します。
通常は60秒程度が推奨値です。
空白の場合は、デフォルト値(60)を使用します。', DESCRIPTION_EN = 'Enter a timeout value between 60 and 3600 for issuing RestAPI to the Ansible Automation Controller/Platform Gateway.
60 seconds is the recommended value.
If blank, the default value (60) will be used.' WHERE COLUMN_DEFINITION_ID = '2010208';

UPDATE T_COMN_MENU_COLUMN_LINK SET DESCRIPTION_JA = 'Ansible Automation Platformに作成される一時オブジェクトを削除するかを選択します。', DESCRIPTION_EN = 'Select whether to delete temporary objects created in Ansible Automation Platform.' WHERE COLUMN_DEFINITION_ID = '2010211';
UPDATE T_COMN_MENU_COLUMN_LINK_JNL SET DESCRIPTION_JA = 'Ansible Automation Platformに作成される一時オブジェクトを削除するかを選択します。', DESCRIPTION_EN = 'Select whether to delete temporary objects created in Ansible Automation Platform.' WHERE COLUMN_DEFINITION_ID = '2010211';

UPDATE T_COMN_MENU_COLUMN_LINK SET DESCRIPTION_JA = 'Ansible Automation Platformの登録するノードのホスト名(またはIPアドレス)を入力します。', DESCRIPTION_EN = 'It is host name (or IP address) of the node in Ansible Automation Platform.' WHERE COLUMN_DEFINITION_ID = '2010302';
UPDATE T_COMN_MENU_COLUMN_LINK_JNL SET DESCRIPTION_JA = 'Ansible Automation Platformの登録するノードのホスト名(またはIPアドレス)を入力します。', DESCRIPTION_EN = 'It is host name (or IP address) of the node in Ansible Automation Platform.' WHERE COLUMN_DEFINITION_ID = '2010302';

UPDATE T_COMN_MENU_COLUMN_LINK SET DESCRIPTION_JA = 'sshで該当ノードに接続する場合の認証方式を選択します。
・パスワード認証
　パスワードの入力が必須です。
・鍵認証(パスフレーズなし)
　ssh秘密鍵ファイルのアップロードが必須です。
・鍵認証(パスフレーズあり)
　ssh秘密鍵ファイルのアップロードと、パスフレーズの入力が必須です。', DESCRIPTION_EN = 'Select the authentication method when connecting to the node with ssh.
-Password authentication
 Select ● in the login password management and enter the login password.
-Key authentication (no passphrase)
 Uploading the ssh private key file is required.
-Key authentication (with passphrase)
 You must upload the ssh private key file and enter the passphrase.' WHERE COLUMN_DEFINITION_ID = '2010303';
UPDATE T_COMN_MENU_COLUMN_LINK_JNL SET DESCRIPTION_JA = 'sshで該当ノードに接続する場合の認証方式を選択します。
・パスワード認証
　パスワードの入力が必須です。
・鍵認証(パスフレーズなし)
　ssh秘密鍵ファイルのアップロードが必須です。
・鍵認証(パスフレーズあり)
　ssh秘密鍵ファイルのアップロードと、パスフレーズの入力が必須です。', DESCRIPTION_EN = 'Select the authentication method when connecting to the node with ssh.
-Password authentication
 Select ● in the login password management and enter the login password.
-Key authentication (no passphrase)
 Uploading the ssh private key file is required.
-Key authentication (with passphrase)
 You must upload the ssh private key file and enter the passphrase.' WHERE COLUMN_DEFINITION_ID = '2010303';

UPDATE T_COMN_MENU_COLUMN_LINK SET DESCRIPTION_JA = 'sshで該当ノードに接続する場合のユーザ名を入力します。ExecutionNode又はHybridNodeではITA作業用ディレクトリ(/var/lib/exastro)への書込み権限が必要です。', DESCRIPTION_EN = 'User when connecting to Ansible Automation Controller with ssh. Write permission to the ITA working Directory (/var/lib/exastro) is required.' WHERE COLUMN_DEFINITION_ID = '2010304';
UPDATE T_COMN_MENU_COLUMN_LINK_JNL SET DESCRIPTION_JA = 'sshで該当ノードに接続する場合のユーザ名を入力します。ExecutionNode又はHybridNodeではITA作業用ディレクトリ(/var/lib/exastro)への書込み権限が必要です。', DESCRIPTION_EN = 'User when connecting to Ansible Automation Controller with ssh. Write permission to the ITA working Directory (/var/lib/exastro) is required.' WHERE COLUMN_DEFINITION_ID = '2010304';

UPDATE T_COMN_MENU_COLUMN_LINK SET DESCRIPTION_JA = '該当ノードがAnsible Automation Platformのexecution nodeの場合に「True」を選択します。', DESCRIPTION_EN = 'If the target node is an execution node for Ansible Automation Platform, select \"True\"' WHERE COLUMN_DEFINITION_ID = '2010309';
UPDATE T_COMN_MENU_COLUMN_LINK_JNL SET DESCRIPTION_JA = '該当ノードがAnsible Automation Platformのexecution nodeの場合に「True」を選択します。', DESCRIPTION_EN = 'If the target node is an execution node for Ansible Automation Platform, select \"True\"' WHERE COLUMN_DEFINITION_ID = '2010309';




-- - AAP2.5対応には直接関係ないが、不自然な表現を微修正
UPDATE T_COMN_MENU_COLUMN_LINK SET DESCRIPTION_JA = 'http/httpsのいずれかを入力します。
通常はhttpsです。' WHERE COLUMN_DEFINITION_ID = '2010204';
UPDATE T_COMN_MENU_COLUMN_LINK_JNL SET DESCRIPTION_JA = 'http/httpsのいずれかを入力します。
通常はhttpsです。' WHERE COLUMN_DEFINITION_ID = '2010204';

UPDATE T_COMN_MENU_COLUMN_LINK SET DESCRIPTION_JA = 'ansible-vaultコマンドで変数の具体値を暗号化する場合のパスワードを入力します。
空白の場合は、デフォルト値を使用します。
[最大長]64バイト' WHERE COLUMN_DEFINITION_ID = '2010212';
UPDATE T_COMN_MENU_COLUMN_LINK_JNL SET DESCRIPTION_JA = 'ansible-vaultコマンドで変数の具体値を暗号化する場合のパスワードを入力します。
空白の場合は、デフォルト値を使用します。
[最大長]64バイト' WHERE COLUMN_DEFINITION_ID = '2010212';

UPDATE T_COMN_MENU_COLUMN_LINK SET DESCRIPTION_JA = 'パスワード認証で接続する場合のパスワードを入力します。' WHERE COLUMN_DEFINITION_ID = '2010305';
UPDATE T_COMN_MENU_COLUMN_LINK_JNL SET DESCRIPTION_JA = 'パスワード認証で接続する場合のパスワードを入力します。' WHERE COLUMN_DEFINITION_ID = '2010305';

UPDATE T_COMN_MENU_COLUMN_LINK SET DESCRIPTION_JA = '鍵認証で接続する場合のssh秘密鍵ファイルを入力します。
アップロードしたファイルは暗号化されて保存されます。' WHERE COLUMN_DEFINITION_ID = '2010306';
UPDATE T_COMN_MENU_COLUMN_LINK_JNL SET DESCRIPTION_JA = '鍵認証で接続する場合のssh秘密鍵ファイルを入力します。
アップロードしたファイルは暗号化されて保存されます。' WHERE COLUMN_DEFINITION_ID = '2010306';

UPDATE T_COMN_MENU_COLUMN_LINK SET DESCRIPTION_JA = '該当ノードにsshで接続する際のポート番号を入力します。空白の場合は、デフォルト値(22)を使用します。' WHERE COLUMN_DEFINITION_ID = '2010308';
UPDATE T_COMN_MENU_COLUMN_LINK_JNL SET DESCRIPTION_JA = '該当ノードにsshで接続する際のポート番号を入力します。空白の場合は、デフォルト値(22)を使用します。' WHERE COLUMN_DEFINITION_ID = '2010308';
