INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('44','20112');

-- ▼Issue 2714 文言修正
UPDATE T_COMN_MENU_COLUMN_LINK      SET DESCRIPTION_JA = 'モードが時刻指定の場合、指定時刻以降のレコードがエクスポート/インポートされます。', LAST_UPDATE_TIMESTAMP = _____DATE_____  WHERE COLUMN_DEFINITION_ID = '6010306';
UPDATE T_COMN_MENU_COLUMN_LINK_JNL      SET DESCRIPTION_JA = 'モードが時刻指定の場合、指定時刻以降のレコードがエクスポート/インポートされます。', LAST_UPDATE_TIMESTAMP = _____DATE_____  WHERE COLUMN_DEFINITION_ID = '6010306';
