global:
  itaGlobalDefinition:
    persistence:
      enabled: true
      accessMode: ReadWriteMany
      size: "{{ size }}"
      storageClass: "{{ storageClass }}" # e.g.) azurefile or - (None)
  gitlabDefinition:
    secret:
      GITLAB_ROOT_TOKEN: "{{ GITLAB_ROOT_TOKEN }}"
    config:
      GITLAB_PROTOCOL: "{{ GITLAB_PROTOCOL }}"
      GITLAB_HOST: "{{ GITLAB_HOST }}"
      GITLAB_PORT: "{{ GITLAB_PORT }}"
  itaDatabaseDefinition:
    config:
      DB_HOST: "{{ DB_HOST }}"
    secret:
      DB_ADMIN_USER: "{{ DB_ADMIN_USER }}"
      DB_ADMIN_PASSWORD: "{{ DB_ADMIN_PASSWORD }}"
      DB_USER: "{{ DB_USER }}"
      DB_PASSWORD: "{{ DB_PASSWORD }}"

extraEnv:
  EXECUTE_INTERVAL: "{{ EXECUTE_INTERVAL }}"
  ANSIBLE_AGENT_IMAGE: "{{ ANSIBLE_AGENT_IMAGE }}"
  ANSIBLE_AGENT_IMAGE_TAG: "{{ ANSIBLE_AGENT_IMAGE_TAG }}"

replicaCount: "{{ replicaCount }}"

image:
  repository: "{{ repository }}"
  tag: "{{ tag }}"
  pullPolicy: Always

ita-api-admin:
  image:
    repository: "{{ repository }}"
    tag: "{{ tag }}"
    pullPolicy: Always

ita-api-organization:
  replicaCount: "{{ replicaCount }}"
  image:
    repository: "{{ repository }}"
    tag: "{{ tag }}"
    pullPolicy: Always

ita-by-ansible-execute:
  replicaCount: "{{ replicaCount }}"
  image:
    repository: "{{ repository }}"
    tag: "{{ tag }}"
    pullPolicy: Always
  extraEnv:
    EXECUTE_INTERVAL: "{{ EXECUTE_INTERVAL }}"
    ANSIBLE_AGENT_IMAGE: "{{ ANSIBLE_AGENT_IMAGE }}"
    ANSIBLE_AGENT_IMAGE_TAG: "{{ ANSIBLE_AGENT_IMAGE_TAG }}"

ita-by-ansible-legacy-role-vars-listup:
  replicaCount: "{{ replicaCount }}"
  extraEnv:
    EXECUTE_INTERVAL: "{{ EXECUTE_INTERVAL }}"
  image:
    repository: "{{ repository }}"
    tag: "{{ tag }}"
    pullPolicy: Always

ita-by-ansible-towermaster-sync:
  replicaCount: "{{ replicaCount }}"
  extraEnv:
    EXECUTE_INTERVAL: "{{ EXECUTE_INTERVAL }}"
  image:
    repository: "{{ repository }}"
    tag: "{{ tag }}"
    pullPolicy: Always

ita-by-conductor-synchronize:
  replicaCount: "{{ replicaCount }}"
  extraEnv:
    EXECUTE_INTERVAL: "{{ EXECUTE_INTERVAL }}"
  image:
    repository: "{{ repository }}"
    tag: "{{ tag }}"
    pullPolicy: Always

ita-by-menu-create:
  replicaCount: "{{ replicaCount }}"
  extraEnv:
    EXECUTE_INTERVAL: "{{ EXECUTE_INTERVAL }}"
  image:
    repository: "{{ repository }}"
    tag: "{{ tag }}"
    pullPolicy: Always

ita-database-setup-job:
  image:
    repository: "{{ repository }}"
    tag: "{{ tag }}"
    pullPolicy: Always

ita-web-server:
  replicaCount: "{{ replicaCount }}"
  image:
    repository: "{{ repository }}"
    tag: "{{ tag }}"
    pullPolicy: Always

