-- ------------------------------------------------------------
-- ▼VIEW UPDATE START
-- ------------------------------------------------------------
-- V001_代入値自動登録用項目表示ビュー
CREATE OR REPLACE VIEW V_ANSC_COLUMN_LIST AS 
SELECT
TAB_A.COLUMN_DEFINITION_ID,
TAB_A.MENU_ID,
TAB_A.COLUMN_NAME_JA,
TAB_A.COLUMN_NAME_EN,
TAB_A.COLUMN_NAME_REST,
TAB_A.COL_GROUP_ID,
TAB_A.COLUMN_CLASS,
TAB_A.COLUMN_DISP_SEQ,
TAB_A.REF_TABLE_NAME,
TAB_A.REF_PKEY_NAME,
TAB_A.REF_COL_NAME,
TAB_A.REF_SORT_CONDITIONS,
TAB_A.REF_MULTI_LANG,
TAB_A.SENSITIVE_COL_NAME,
TAB_A.FILE_UPLOAD_PLACE,
TAB_A.COL_NAME,
TAB_A.SAVE_TYPE,
TAB_A.AUTO_INPUT,
TAB_A.INPUT_ITEM,
TAB_A.VIEW_ITEM,
TAB_A.UNIQUE_ITEM,
TAB_A.REQUIRED_ITEM,
TAB_A.AUTOREG_HIDE_ITEM,
TAB_A.AUTOREG_ONLY_ITEM,
TAB_A.INITIAL_VALUE,
TAB_A.VALIDATE_OPTION,
TAB_A.BEFORE_VALIDATE_REGISTER,
TAB_A.AFTER_VALIDATE_REGISTER,
TAB_A.DESCRIPTION_JA,
TAB_A.DESCRIPTION_EN,
TAB_A.NOTE,
TAB_A.DISUSE_FLAG,
TAB_A.LAST_UPDATE_TIMESTAMP,
TAB_A.LAST_UPDATE_USER,
TAB_B.VERTICAL,
concat(TAB_D.MENU_GROUP_NAME_JA, ":", concat(TAB_C.MENU_NAME_JA, ":" , TAB_E.FULL_COL_GROUP_NAME_JA, '/', TAB_A.COLUMN_NAME_JA)) as GROUP_MENU_COLUMN_NAME_JA,
concat(TAB_D.MENU_GROUP_NAME_EN, ":", concat(TAB_C.MENU_NAME_EN, ":" , TAB_E.FULL_COL_GROUP_NAME_EN, '/', TAB_A.COLUMN_NAME_EN)) as GROUP_MENU_COLUMN_NAME_EN
FROM T_COMN_MENU_COLUMN_LINK TAB_A 
LEFT JOIN T_COMN_MENU_TABLE_LINK TAB_B ON (TAB_A.MENU_ID = TAB_B.MENU_ID)
LEFT JOIN T_COMN_MENU TAB_C ON (TAB_B.MENU_ID = TAB_C.MENU_ID)
LEFT JOIN T_COMN_MENU_GROUP TAB_D ON ( TAB_C.MENU_GROUP_ID = TAB_D.MENU_GROUP_ID )
LEFT JOIN T_COMN_COLUMN_GROUP TAB_E ON ( TAB_A.COL_GROUP_ID = TAB_E.COL_GROUP_ID )
WHERE TAB_A.AUTOREG_HIDE_ITEM = 0
AND TAB_A.DISUSE_FLAG = 0
AND (TAB_B.SHEET_TYPE = 1 OR TAB_B.SHEET_TYPE = 4)
AND TAB_B.DISUSE_FLAG = 0
AND TAB_B.SUBSTITUTION_VALUE_LINK_FLAG =1
AND TAB_C.DISUSE_FLAG = 0
AND TAB_D.DISUSE_FLAG = 0
AND TAB_E.DISUSE_FLAG = 0;
CREATE OR REPLACE VIEW V_ANSC_COLUMN_LIST_JNL AS 
SELECT
TAB_A.JOURNAL_SEQ_NO,
TAB_A.JOURNAL_REG_DATETIME,
TAB_A.JOURNAL_ACTION_CLASS,
TAB_A.COLUMN_DEFINITION_ID,
TAB_A.MENU_ID,
TAB_A.COLUMN_NAME_JA,
TAB_A.COLUMN_NAME_EN,
TAB_A.COLUMN_NAME_REST,
TAB_A.COL_GROUP_ID,
TAB_A.COLUMN_CLASS,
TAB_A.COLUMN_DISP_SEQ,
TAB_A.REF_TABLE_NAME,
TAB_A.REF_PKEY_NAME,
TAB_A.REF_COL_NAME,
TAB_A.REF_SORT_CONDITIONS,
TAB_A.REF_MULTI_LANG,
TAB_A.SENSITIVE_COL_NAME,
TAB_A.FILE_UPLOAD_PLACE,
TAB_A.COL_NAME,
TAB_A.SAVE_TYPE,
TAB_A.AUTO_INPUT,
TAB_A.INPUT_ITEM,
TAB_A.VIEW_ITEM,
TAB_A.UNIQUE_ITEM,
TAB_A.REQUIRED_ITEM,
TAB_A.AUTOREG_HIDE_ITEM,
TAB_A.AUTOREG_ONLY_ITEM,
TAB_A.INITIAL_VALUE,
TAB_A.VALIDATE_OPTION,
TAB_A.BEFORE_VALIDATE_REGISTER,
TAB_A.AFTER_VALIDATE_REGISTER,
TAB_A.DESCRIPTION_JA,
TAB_A.DESCRIPTION_EN,
TAB_A.NOTE,
TAB_A.DISUSE_FLAG,
TAB_A.LAST_UPDATE_TIMESTAMP,
TAB_A.LAST_UPDATE_USER,
TAB_B.VERTICAL,
concat(TAB_D.MENU_GROUP_NAME_JA, ":", concat(TAB_C.MENU_NAME_JA, ":" , TAB_E.FULL_COL_GROUP_NAME_JA, '/', TAB_A.COLUMN_NAME_JA)) as GROUP_MENU_COLUMN_NAME_JA,
concat(TAB_D.MENU_GROUP_NAME_EN, ":", concat(TAB_C.MENU_NAME_EN, ":" , TAB_E.FULL_COL_GROUP_NAME_EN, '/', TAB_A.COLUMN_NAME_EN)) as GROUP_MENU_COLUMN_NAME_EN
FROM T_COMN_MENU_COLUMN_LINK_JNL TAB_A 
LEFT JOIN T_COMN_MENU_TABLE_LINK_JNL TAB_B ON (TAB_A.MENU_ID = TAB_B.MENU_ID)
LEFT JOIN T_COMN_MENU_JNL TAB_C ON (TAB_B.MENU_ID = TAB_C.MENU_ID)
LEFT JOIN T_COMN_MENU_GROUP_JNL TAB_D ON ( TAB_C.MENU_GROUP_ID = TAB_D.MENU_GROUP_ID )
LEFT JOIN T_COMN_COLUMN_GROUP_JNL TAB_E ON ( TAB_A.COL_GROUP_ID = TAB_E.COL_GROUP_ID )
WHERE TAB_A.AUTOREG_HIDE_ITEM = 0
AND TAB_A.DISUSE_FLAG = 0
AND (TAB_B.SHEET_TYPE = 1 OR TAB_B.SHEET_TYPE = 4)
AND TAB_B.DISUSE_FLAG = 0
AND TAB_B.SUBSTITUTION_VALUE_LINK_FLAG =1
AND TAB_C.DISUSE_FLAG = 0
AND TAB_D.DISUSE_FLAG = 0
AND TAB_E.DISUSE_FLAG = 0;


-- V013_代入値自動登録用項目表示ビュー
CREATE OR REPLACE VIEW V_ANSP_COLUMN_LIST AS 
SELECT
TAB_A.COLUMN_DEFINITION_ID,
TAB_A.MENU_ID,
TAB_A.COLUMN_NAME_JA,
TAB_A.COLUMN_NAME_EN,
TAB_A.COLUMN_NAME_REST,
TAB_A.COL_GROUP_ID,
TAB_A.COLUMN_CLASS,
TAB_A.COLUMN_DISP_SEQ,
TAB_A.REF_TABLE_NAME,
TAB_A.REF_PKEY_NAME,
TAB_A.REF_COL_NAME,
TAB_A.REF_SORT_CONDITIONS,
TAB_A.REF_MULTI_LANG,
TAB_A.SENSITIVE_COL_NAME,
TAB_A.FILE_UPLOAD_PLACE,
TAB_A.COL_NAME,
TAB_A.SAVE_TYPE,
TAB_A.AUTO_INPUT,
TAB_A.INPUT_ITEM,
TAB_A.VIEW_ITEM,
TAB_A.UNIQUE_ITEM,
TAB_A.REQUIRED_ITEM,
TAB_A.AUTOREG_HIDE_ITEM,
TAB_A.AUTOREG_ONLY_ITEM,
TAB_A.INITIAL_VALUE,
TAB_A.VALIDATE_OPTION,
TAB_A.BEFORE_VALIDATE_REGISTER,
TAB_A.AFTER_VALIDATE_REGISTER,
TAB_A.DESCRIPTION_JA,
TAB_A.DESCRIPTION_EN,
TAB_A.NOTE,
TAB_A.DISUSE_FLAG,
TAB_A.LAST_UPDATE_TIMESTAMP,
TAB_A.LAST_UPDATE_USER,
TAB_B.VERTICAL,
concat(TAB_D.MENU_GROUP_NAME_JA, ":", concat(TAB_C.MENU_NAME_JA, ":" , TAB_E.FULL_COL_GROUP_NAME_JA, '/', TAB_A.COLUMN_NAME_JA)) as GROUP_MENU_COLUMN_NAME_JA,
concat(TAB_D.MENU_GROUP_NAME_EN, ":", concat(TAB_C.MENU_NAME_EN, ":" , TAB_E.FULL_COL_GROUP_NAME_EN, '/', TAB_A.COLUMN_NAME_EN)) as GROUP_MENU_COLUMN_NAME_EN
FROM T_COMN_MENU_COLUMN_LINK TAB_A 
LEFT JOIN T_COMN_MENU_TABLE_LINK TAB_B ON (TAB_A.MENU_ID = TAB_B.MENU_ID)
LEFT JOIN T_COMN_MENU TAB_C ON (TAB_B.MENU_ID = TAB_C.MENU_ID)
LEFT JOIN T_COMN_MENU_GROUP TAB_D ON ( TAB_C.MENU_GROUP_ID = TAB_D.MENU_GROUP_ID )
LEFT JOIN T_COMN_COLUMN_GROUP TAB_E ON ( TAB_A.COL_GROUP_ID = TAB_E.COL_GROUP_ID )
WHERE TAB_A.AUTOREG_HIDE_ITEM = 0
AND TAB_A.DISUSE_FLAG = 0
AND (TAB_B.SHEET_TYPE = 1 OR TAB_B.SHEET_TYPE = 4)
AND TAB_A.COLUMN_CLASS <> 2 
AND TAB_B.DISUSE_FLAG = 0
AND TAB_B.SUBSTITUTION_VALUE_LINK_FLAG =1
AND TAB_C.DISUSE_FLAG = 0
AND TAB_D.DISUSE_FLAG = 0
AND TAB_E.DISUSE_FLAG = 0;
CREATE OR REPLACE VIEW V_ANSP_COLUMN_LIST_JNL AS 
SELECT
TAB_A.JOURNAL_SEQ_NO,
TAB_A.JOURNAL_REG_DATETIME,
TAB_A.JOURNAL_ACTION_CLASS,
TAB_A.COLUMN_DEFINITION_ID,
TAB_A.MENU_ID,
TAB_A.COLUMN_NAME_JA,
TAB_A.COLUMN_NAME_EN,
TAB_A.COLUMN_NAME_REST,
TAB_A.COL_GROUP_ID,
TAB_A.COLUMN_CLASS,
TAB_A.COLUMN_DISP_SEQ,
TAB_A.REF_TABLE_NAME,
TAB_A.REF_PKEY_NAME,
TAB_A.REF_COL_NAME,
TAB_A.REF_SORT_CONDITIONS,
TAB_A.REF_MULTI_LANG,
TAB_A.SENSITIVE_COL_NAME,
TAB_A.FILE_UPLOAD_PLACE,
TAB_A.COL_NAME,
TAB_A.SAVE_TYPE,
TAB_A.AUTO_INPUT,
TAB_A.INPUT_ITEM,
TAB_A.VIEW_ITEM,
TAB_A.UNIQUE_ITEM,
TAB_A.REQUIRED_ITEM,
TAB_A.AUTOREG_HIDE_ITEM,
TAB_A.AUTOREG_ONLY_ITEM,
TAB_A.INITIAL_VALUE,
TAB_A.VALIDATE_OPTION,
TAB_A.BEFORE_VALIDATE_REGISTER,
TAB_A.AFTER_VALIDATE_REGISTER,
TAB_A.DESCRIPTION_JA,
TAB_A.DESCRIPTION_EN,
TAB_A.NOTE,
TAB_A.DISUSE_FLAG,
TAB_A.LAST_UPDATE_TIMESTAMP,
TAB_A.LAST_UPDATE_USER,
TAB_B.VERTICAL,
concat(TAB_D.MENU_GROUP_NAME_JA, ":", concat(TAB_C.MENU_NAME_JA, ":" , TAB_E.FULL_COL_GROUP_NAME_JA, '/', TAB_A.COLUMN_NAME_JA)) as GROUP_MENU_COLUMN_NAME_JA,
concat(TAB_D.MENU_GROUP_NAME_EN, ":", concat(TAB_C.MENU_NAME_EN, ":" , TAB_E.FULL_COL_GROUP_NAME_EN, '/', TAB_A.COLUMN_NAME_EN)) as GROUP_MENU_COLUMN_NAME_EN
FROM T_COMN_MENU_COLUMN_LINK_JNL TAB_A 
LEFT JOIN T_COMN_MENU_TABLE_LINK_JNL TAB_B ON (TAB_A.MENU_ID = TAB_B.MENU_ID)
LEFT JOIN T_COMN_MENU_JNL TAB_C ON (TAB_B.MENU_ID = TAB_C.MENU_ID)
LEFT JOIN T_COMN_MENU_GROUP_JNL TAB_D ON ( TAB_C.MENU_GROUP_ID = TAB_D.MENU_GROUP_ID )
LEFT JOIN T_COMN_COLUMN_GROUP_JNL TAB_E ON ( TAB_A.COL_GROUP_ID = TAB_E.COL_GROUP_ID )
WHERE TAB_A.AUTOREG_HIDE_ITEM = 0
AND TAB_A.DISUSE_FLAG = 0
AND (TAB_B.SHEET_TYPE = 1 OR TAB_B.SHEET_TYPE = 4)
AND TAB_A.COLUMN_CLASS <> 2 
AND TAB_B.DISUSE_FLAG = 0
AND TAB_B.SUBSTITUTION_VALUE_LINK_FLAG =1
AND TAB_C.DISUSE_FLAG = 0
AND TAB_D.DISUSE_FLAG = 0
AND TAB_E.DISUSE_FLAG = 0;


-- V014_入力用項目表示ビュー
CREATE OR REPLACE VIEW V_ANSC_INPUT_COLUMN_LIST AS 
SELECT
TAB_A.COLUMN_DEFINITION_ID,
TAB_A.MENU_ID,
TAB_A.COLUMN_NAME_JA,
TAB_A.COLUMN_NAME_EN,
TAB_A.COLUMN_NAME_REST,
TAB_A.COL_GROUP_ID,
TAB_A.COLUMN_CLASS,
TAB_A.COLUMN_DISP_SEQ,
TAB_A.REF_TABLE_NAME,
TAB_A.REF_PKEY_NAME,
TAB_A.REF_COL_NAME,
TAB_A.REF_SORT_CONDITIONS,
TAB_A.REF_MULTI_LANG,
TAB_A.SENSITIVE_COL_NAME,
TAB_A.FILE_UPLOAD_PLACE,
TAB_A.COL_NAME,
TAB_A.SAVE_TYPE,
TAB_A.AUTO_INPUT,
TAB_A.INPUT_ITEM,
TAB_A.VIEW_ITEM,
TAB_A.UNIQUE_ITEM,
TAB_A.REQUIRED_ITEM,
TAB_A.AUTOREG_HIDE_ITEM,
TAB_A.AUTOREG_ONLY_ITEM,
TAB_A.INITIAL_VALUE,
TAB_A.VALIDATE_OPTION,
TAB_A.BEFORE_VALIDATE_REGISTER,
TAB_A.AFTER_VALIDATE_REGISTER,
TAB_A.DESCRIPTION_JA,
TAB_A.DESCRIPTION_EN,
TAB_A.NOTE,
TAB_A.DISUSE_FLAG,
TAB_A.LAST_UPDATE_TIMESTAMP,
TAB_A.LAST_UPDATE_USER,
TAB_B.VERTICAL,
concat(TAB_D.MENU_GROUP_NAME_JA, ":", concat(TAB_C.MENU_NAME_JA, ":" , TAB_E.FULL_COL_GROUP_NAME_JA, '/', TAB_A.COLUMN_NAME_JA)) as GROUP_MENU_COLUMN_NAME_JA,
concat(TAB_D.MENU_GROUP_NAME_EN, ":", concat(TAB_C.MENU_NAME_EN, ":" , TAB_E.FULL_COL_GROUP_NAME_EN, '/', TAB_A.COLUMN_NAME_EN)) as GROUP_MENU_COLUMN_NAME_EN
FROM T_COMN_MENU_COLUMN_LINK TAB_A 
LEFT JOIN T_COMN_MENU_TABLE_LINK TAB_B ON (TAB_A.MENU_ID = TAB_B.MENU_ID)
LEFT JOIN T_COMN_MENU TAB_C ON (TAB_B.MENU_ID = TAB_C.MENU_ID)
LEFT JOIN T_COMN_MENU_GROUP TAB_D ON ( TAB_C.MENU_GROUP_ID = TAB_D.MENU_GROUP_ID )
LEFT JOIN T_COMN_COLUMN_GROUP TAB_E ON ( TAB_A.COL_GROUP_ID = TAB_E.COL_GROUP_ID )
WHERE TAB_A.AUTOREG_HIDE_ITEM = 0
AND TAB_A.DISUSE_FLAG = 0
AND TAB_A.INPUT_ITEM =1
AND (TAB_B.SHEET_TYPE = 1 OR TAB_B.SHEET_TYPE = 4)
AND TAB_B.DISUSE_FLAG = 0
AND TAB_B.SUBSTITUTION_VALUE_LINK_FLAG =0
AND TAB_C.DISUSE_FLAG = 0
AND TAB_D.DISUSE_FLAG = 0
AND TAB_E.DISUSE_FLAG = 0;
CREATE OR REPLACE VIEW V_ANSC_INPUT_COLUMN_LIST_JNL AS 
SELECT
TAB_A.JOURNAL_SEQ_NO,
TAB_A.JOURNAL_REG_DATETIME,
TAB_A.JOURNAL_ACTION_CLASS,
TAB_A.COLUMN_DEFINITION_ID,
TAB_A.MENU_ID,
TAB_A.COLUMN_NAME_JA,
TAB_A.COLUMN_NAME_EN,
TAB_A.COLUMN_NAME_REST,
TAB_A.COL_GROUP_ID,
TAB_A.COLUMN_CLASS,
TAB_A.COLUMN_DISP_SEQ,
TAB_A.REF_TABLE_NAME,
TAB_A.REF_PKEY_NAME,
TAB_A.REF_COL_NAME,
TAB_A.REF_SORT_CONDITIONS,
TAB_A.REF_MULTI_LANG,
TAB_A.SENSITIVE_COL_NAME,
TAB_A.FILE_UPLOAD_PLACE,
TAB_A.COL_NAME,
TAB_A.SAVE_TYPE,
TAB_A.AUTO_INPUT,
TAB_A.INPUT_ITEM,
TAB_A.VIEW_ITEM,
TAB_A.UNIQUE_ITEM,
TAB_A.REQUIRED_ITEM,
TAB_A.AUTOREG_HIDE_ITEM,
TAB_A.AUTOREG_ONLY_ITEM,
TAB_A.INITIAL_VALUE,
TAB_A.VALIDATE_OPTION,
TAB_A.BEFORE_VALIDATE_REGISTER,
TAB_A.AFTER_VALIDATE_REGISTER,
TAB_A.DESCRIPTION_JA,
TAB_A.DESCRIPTION_EN,
TAB_A.NOTE,
TAB_A.DISUSE_FLAG,
TAB_A.LAST_UPDATE_TIMESTAMP,
TAB_A.LAST_UPDATE_USER,
TAB_B.VERTICAL,
concat(TAB_D.MENU_GROUP_NAME_JA, ":", concat(TAB_C.MENU_NAME_JA, ":" , TAB_E.FULL_COL_GROUP_NAME_JA, '/', TAB_A.COLUMN_NAME_JA)) as GROUP_MENU_COLUMN_NAME_JA,
concat(TAB_D.MENU_GROUP_NAME_EN, ":", concat(TAB_C.MENU_NAME_EN, ":" , TAB_E.FULL_COL_GROUP_NAME_EN, '/', TAB_A.COLUMN_NAME_EN)) as GROUP_MENU_COLUMN_NAME_EN
FROM T_COMN_MENU_COLUMN_LINK_JNL TAB_A 
LEFT JOIN T_COMN_MENU_TABLE_LINK_JNL TAB_B ON (TAB_A.MENU_ID = TAB_B.MENU_ID)
LEFT JOIN T_COMN_MENU_JNL TAB_C ON (TAB_B.MENU_ID = TAB_C.MENU_ID)
LEFT JOIN T_COMN_MENU_GROUP_JNL TAB_D ON ( TAB_C.MENU_GROUP_ID = TAB_D.MENU_GROUP_ID )
LEFT JOIN T_COMN_COLUMN_GROUP_JNL TAB_E ON ( TAB_A.COL_GROUP_ID = TAB_E.COL_GROUP_ID )
WHERE TAB_A.AUTOREG_HIDE_ITEM = 0
AND TAB_A.DISUSE_FLAG = 0
AND TAB_A.INPUT_ITEM =1
AND (TAB_B.SHEET_TYPE = 1 OR TAB_B.SHEET_TYPE = 4)
AND TAB_B.DISUSE_FLAG = 0
AND TAB_B.SUBSTITUTION_VALUE_LINK_FLAG =0
AND TAB_C.DISUSE_FLAG = 0
AND TAB_D.DISUSE_FLAG = 0
AND TAB_E.DISUSE_FLAG = 0;


-- ------------------------------------------------------------
-- ▲ VIEW UPDATE END
-- ------------------------------------------------------------