-- INSERT/UPDATE: -2.3.0
    -- T_COMN_MENU_TABLE_LINK : UPDATE

-- ------------------------------------------------------------
-- ▼TABLE MASTER UPDATE START
-- ------------------------------------------------------------

-- T_COMN_MENU_TABLE_LINK: UPDATE
UPDATE T_COMN_MENU_TABLE_LINK SET SHEET_TYPE = '28', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE TABLE_DEFINITION_ID = '20210';
UPDATE T_COMN_MENU_TABLE_LINK_JNL SET SHEET_TYPE = '28', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE TABLE_DEFINITION_ID = '20210';
UPDATE T_COMN_MENU_TABLE_LINK SET SHEET_TYPE = '28', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE TABLE_DEFINITION_ID = '20312';
UPDATE T_COMN_MENU_TABLE_LINK_JNL SET SHEET_TYPE = '28', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE TABLE_DEFINITION_ID = '20312';
UPDATE T_COMN_MENU_TABLE_LINK SET SHEET_TYPE = '28', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE TABLE_DEFINITION_ID = '20412';
UPDATE T_COMN_MENU_TABLE_LINK_JNL SET SHEET_TYPE = '28', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE TABLE_DEFINITION_ID = '20412';

-- T_COMN_MENU_COLUMN_LINK: UPDATE
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2020108','20201','ヘッダーセクション','Header section','header_section','1020201','2',80,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'ANS_PLAYBOOK_HED_DEF',NULL,'0','1','1','0','0','1','0','- hosts: all
  remote_user: \"{{ __loginuser__ }}\"
  gather_facts: no','{
"max_length": 4000
}',NULL,NULL,NULL,'ITAが自動生成する親Playbookの先頭からtasksセクションまでのセクションを編集 します。
未入力の場合は、以下を適用します。

  - hosts: all
    remote_user: \"{{ __loginuser__ }}\"
    gather_facts: no
    become: yes

winrm接続の場合は「become: yes」は省略されます。','Edit the section from the top of the parent Playbook automatically generated by ITA is executed to the tasks section.
Setting value when not enter.

  - hosts: all
    remote_user: \'{{ __loginuser__ }}\'
    gather_facts: no
    become: yes

become is omitted for winrm connection.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2020108,_____DATE_____,'INSERT','2020108','20201','ヘッダーセクション','Header section','header_section','1020201','2',80,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'ANS_PLAYBOOK_HED_DEF',NULL,'0','1','1','0','0','1','0','- hosts: all
  remote_user: \"{{ __loginuser__ }}\"
  gather_facts: no','{
"max_length": 4000
}',NULL,NULL,NULL,'ITAが自動生成する親Playbookの先頭からtasksセクションまでのセクションを編集 します。
未入力の場合は、以下を適用します。

  - hosts: all
    remote_user: \"{{ __loginuser__ }}\"
    gather_facts: no
    become: yes

winrm接続の場合は「become: yes」は省略されます。','Edit the section from the top of the parent Playbook automatically generated by ITA is executed to the tasks section.
Setting value when not enter.

  - hosts: all
    remote_user: \'{{ __loginuser__ }}\'
    gather_facts: no
    become: yes

become is omitted for winrm connection.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2040208','20402','ヘッダーセクション','Header section','header_section','1020201','2',80,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'ANS_PLAYBOOK_HED_DEF',NULL,'0','1','1','0','0','1','0','- hosts: all
  remote_user: \"{{ __loginuser__ }}\"
  gather_facts: no','{
"max_length": 4000
}',NULL,NULL,NULL,'ITAが自動生成する親Playbookの先頭からrolesセクションまでのセクションを編集します。
未入力の場合は、以下を適用します。

  - hosts: all
    remote_user: \'{{ __loginuser__ }}\'
    gather_facts: no
    become: yes

winrm接続の場合は「become: yes」は省略されます。','Edit the section from the top of the parent Playbook automatically generated by ITA is executed to the roles section.
Setting value when not enter.

  - hosts: all
    remote_user: \'{{ __loginuser__ }}\'
    gather_facts: no
    become: yes

become is omitted for winrm connection.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2040208,_____DATE_____,'INSERT','2040208','20402','ヘッダーセクション','Header section','header_section','1020201','2',80,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'ANS_PLAYBOOK_HED_DEF',NULL,'0','1','1','0','0','1','0','- hosts: all
  remote_user: \"{{ __loginuser__ }}\"
  gather_facts: no','{
"max_length": 4000
}',NULL,NULL,NULL,'ITAが自動生成する親Playbookの先頭からrolesセクションまでのセクションを編集します。
未入力の場合は、以下を適用します。

  - hosts: all
    remote_user: \'{{ __loginuser__ }}\'
    gather_facts: no
    become: yes

winrm接続の場合は「become: yes」は省略されます。','Edit the section from the top of the parent Playbook automatically generated by ITA is executed to the roles section.
Setting value when not enter.

  - hosts: all
    remote_user: \'{{ __loginuser__ }}\'
    gather_facts: no
    become: yes

become is omitted for winrm connection.',NULL,'0',_____DATE_____,1);

-- ------------------------------------------------------------
-- ▼TABLE MASTER UPDATE END
-- ------------------------------------------------------------