UPDATE T_COMN_MENU_GROUP SET DISP_SEQ=200, LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE MENU_GROUP_ID="1001";
UPDATE T_COMN_MENU_GROUP_JNL SET DISP_SEQ=200, LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE MENU_GROUP_ID="1001";
