INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('41','110103');
INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('42','110104');
INSERT INTO T_DP_HIDE_MENU_LIST (HIDE_ID,MENU_ID) VALUES('43','110110');

UPDATE T_COMN_MENU SET SORT_KEY = 'NULL', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE MENU_ID = '60101';
UPDATE T_COMN_MENU_JNL SET SORT_KEY = 'NULL', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE MENU_ID = '60101';
UPDATE T_COMN_MENU SET SORT_KEY = 'NULL', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE MENU_ID = '60102';
UPDATE T_COMN_MENU_JNL SET SORT_KEY = 'NULL', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE MENU_ID = '60102';
UPDATE T_COMN_MENU SET SORT_KEY = '[{"DESC":"last_update_date_time"}]', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE MENU_ID = '60103';
UPDATE T_COMN_MENU_JNL SET SORT_KEY = '[{"DESC":"last_update_date_time"}]', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE MENU_ID = '60103';
UPDATE T_COMN_MENU SET SORT_KEY = 'NULL', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE MENU_ID = '60104';
UPDATE T_COMN_MENU_JNL SET SORT_KEY = 'NULL', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE MENU_ID = '60104';
UPDATE T_COMN_MENU SET SORT_KEY = 'NULL', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE MENU_ID = '60105';
UPDATE T_COMN_MENU_JNL SET SORT_KEY = 'NULL', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE MENU_ID = '60105';
UPDATE T_COMN_MENU SET SORT_KEY = '[{"DESC":"last_update_date_time"}]', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE MENU_ID = '60106';
UPDATE T_COMN_MENU_JNL SET SORT_KEY = '[{"DESC":"last_update_date_time"}]', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE MENU_ID = '60106';
