INSERT INTO T_COMN_BACKYARD_USER (USER_ID,USER_NAME_JA,USER_NAME_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(110102,'OASEルールマッチング機能','OASE Conclusion function',NULL,'0',_____DATE_____,1);

INSERT INTO T_COMN_COLUMN_CLASS (COLUMN_CLASS_ID,COLUMN_CLASS_NAME,COLUMN_CLASS_DISP_NAME_JA,COLUMN_CLASS_DISP_NAME_EN,MENU_CREATE_TARGET_FLAG,DISP_SEQ,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(28,'NotificationIDColumn','プルダウン選択(通知先複数選択)','Pulldown selection(Multiple notification)','0',280,NULL,'0',_____DATE_____,1);
