openapi: 3.0.3
info:
  title: Exastro ITA Ansible Execution API
  description: Exastro ITA Ansible Execution API
  version: "2.5"

servers:
  - url: "https://{host}"
    description: API endpoint
    variables:
      host:
        default: localhost
  - url: "http://{host}"
    description: API endpoint
    variables:
      host:
        default: localhost
  - url: "{protocol}://{host}:{port}"
    description: API endpoint (Development)
    variables:
      protocol:
        enum:
          - http
          - https
        default: https
      host:
        default: localhost
      port:
        default: '30080'

tags:
  - name: InternalHealthCheckService
    description: ヘルスチェックに関する操作(内部用)

paths:
  /internal-api/health-check/liveness:
    get:
      tags:
        - InternalHealthCheckService
      summary: Internal health check liveness
      x-openapi-router-controller: controllers.internal_health_check_service_controller
      operationId: internal_health_check_liveness
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: 000-00000
                  data:
                    type: string
                    example: ""
                  message:
                    type: string
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'

  /internal-api/health-check/readiness:
    get:
      tags:
        - InternalHealthCheckService
      summary: Internal health check readiness
      x-openapi-router-controller: controllers.internal_health_check_service_controller
      operationId: internal_health_check_readiness
      responses:
        '200':
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    example: 000-00000
                  data:
                    type: string
                    example: ""
                  message:
                    type: string
        default:
          description: An unexpected error response.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ERROR_TEMPLATE'

components:
  schemas:
    ERROR_TEMPLATE:
      type: object
      properties:
        result:
          type: string
          example: 001-002
        message:
          type: string

  securitySchemes:
    BearerAuth:
      description: Credentials or access token for API
      type: http
      scheme: bearer
      bearerFormat: JWT
    BasicAuth:
      description: Value converted from ID/Password in base64
      type: http
      scheme: basic
  responses:
    UnauthorizedError:
      description: Access token is missing or invalid
security:
- BearerAuth: []
- BasicAuth: []
