# This Playbook file installs package names specified by "ITA_DFLT_Target_Package_Name".
# Nothing will happen if the specified package names are already installed.
# "ITA_DFLT_Target_Package_Name" can specify multiple package names (list type).
- name: Manages Python library dependencies
  ansible.builtin.pip:
    name: "{{ item }}"
  with_items:
    - "{{ ITA_DFLT_Target_Package_Name }}"
