- name: Ensure ITA variable is recognized
  ansible.builtin.set_fact:
    ITA_DFLT_Uninstall_Target_packages: "{{ ITA_DFLT_Uninstall_Target_packages }}"
  when: ITA_DFLT_Uninstall_Target_packages is defined

- name: Uninstall packages with the generic OS package manager
  ansible.builtin.package:
    name: "{{ item }}"
    state: absent
  loop: >-
    {{
      ITA_DFLT_Uninstall_Target_packages if ITA_DFLT_Uninstall_Target_packages is sequence and ITA_DFLT_Uninstall_Target_packages is not string else [ITA_DFLT_Uninstall_Target_packages]
    }}
