- name: Ensure ITA variable is recognized
  ansible.builtin.set_fact:
    ITA_DFLT_Create_Directory: "{{ ITA_DFLT_Create_Directory }}"
  when: ITA_DFLT_Create_Directory is defined

- name: Create folders
  ansible.windows.win_file:
    path: "{{ item }}"
    state: directory
  loop: >-
    {{
      ITA_DFLT_Create_Directory if ITA_DFLT_Create_Directory is sequence and ITA_DFLT_Create_Directory is not string else [ITA_DFLT_Create_Directory]
    }}
