#   Copyright 2022 NEC Corporation
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.
version: '3.1'
services:
  platform-auth:
    user: 1000:1000
    image: exastro/exastro-platform-auth:${PLATFORM_VERSION:-latest}
    environment:
      - TZ=Asia/Tokyo
      - LISTEN_PORT=38000
      - LISTEN_PORT_PF_MNG=38001
      # - PYTHONPATH=/app/
      - CONFIG_API_PATH=/app/api.conf
      - PYTHONIOENCODING=utf-8
      # - EXASTRO_KEYCLOAK_USER=admin
      # - EXASTRO_KEYCLOAK_PASSWORD=password
      # - EXASTRO_KEYCLOAK_MASTER_REALM=master
      - API_KEYCLOAK_HOST=keycloak
      - API_KEYCLOAK_PROTOCOL=http
      - API_KEYCLOAK_PORT=8080
      #- KEYCLOAK_LOCATION=/auth/
      - KEYCLOAK_PROTOCOL=http
      - KEYCLOAK_HOST=keycloak
      - KEYCLOAK_PORT=8080
      #- ITA_WEB_LOCATION=/*/workspaces/*/ita/
      - ITA_WEB_PROTOCOL=http
      - ITA_WEB_HOST=ita-web-server
      - ITA_WEB_PORT=80
      - ITA_API_PROTOCOL=http
      - ITA_API_HOST=ita-api-organization
      - ITA_API_PORT=8000
      - ITA_API_ADMIN_PROTOCOL=http
      - ITA_API_ADMIN_HOST=ita-api-admin
      - ITA_API_ADMIN_PORT=8079
      #- PLATFORM_WEB_LOCATION=/*/platform/
      - PLATFORM_WEB_PROTOCOL=http
      - PLATFORM_WEB_HOST=platform-web
      - PLATFORM_WEB_PORT=80
      - PLATFORM_API_PROTOCOL=http
      - PLATFORM_API_HOST=platform-api
      - PLATFORM_API_PORT=8000
      - DB_HOST=platform-db
      - DB_DATABASE=platform
      - DB_USER=app_user
      - DB_PASSWORD=password
      - ENCRYPT_KEY=${ENCRYPT_KEY}
    ports:
      - "0.0.0.0:38000:38000"
      - "0.0.0.0:38001:38001"
  keycloak:
    image: exastro/keycloak:${PLATFORM_VERSION:-latest}
    healthcheck:
      test: curl http://localhost:8080/auth/realms/master
    environment:
      - TZ=Asia/Tokyo
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - PROXY_ADDRESS_FORWARDING=true
      - DB_VENDOR=mariadb
      - DB_ADDR=platform-db
      - DB_DATABASE=keycloak
      - DB_USER=keycloak
      - DB_PASSWORD=password
    depends_on:
      platform-db:
        condition: service_healthy
  platform-db:
    image: exastro/exastro-common-auth-platform-db:1.0.1
    healthcheck:
      test: mysqladmin ping --silent && mysql -u $${KEYCLOAK_DB_USER} -p$${KEYCLOAK_DB_PASSWORD} -D $${KEYCLOAK_DB_DATABASE} -e 'select 1;'
    volumes:
      - ../.volumes/platform-db/data:/var/lib/mysql
    environment:
      - TZ=Asia/Tokyo
      - MYSQL_ROOT_PASSWORD=password
      - KEYCLOAK_DB_DATABASE=keycloak
      - KEYCLOAK_DB_USER=keycloak
      - KEYCLOAK_DB_PASSWORD=password
  platform-web:
    user: 1000:1000
    image: exastro/exastro-platform-web:${PLATFORM_VERSION:-latest}
    environment:
      - TZ=Asia/Tokyo
      - LISTEN_PORT=80

  platform-api:
    user: 1000:1000
    image: exastro/exastro-platform-api:${PLATFORM_VERSION:-latest}
    environment:
      - TZ=Asia/Tokyo
      - LISTEN_PORT=8000
      # - PYTHONPATH=/app/
      - CONFIG_API_PATH=/app/api.conf
      - PYTHONIOENCODING=utf-8
      - API_KEYCLOAK_HOST=keycloak
      - API_KEYCLOAK_PROTOCOL=http
      - API_KEYCLOAK_PORT=8080
      - ITA_API_ADMIN_PROTOCOL=http
      - ITA_API_ADMIN_HOST=ita-api-admin
      - ITA_API_ADMIN_PORT=8079
      - DB_HOST=platform-db
      - DB_DATABASE=platform
      - DB_USER=app_user
      - DB_PASSWORD=password
      - DB_ADMIN_USER=root
      - DB_ADMIN_PASSWORD=password
      - ENCRYPT_KEY=${ENCRYPT_KEY}
  platform-job:
    user: 1000:1000
    image: exastro/exastro-platform-job:${PLATFORM_VERSION:-latest}
    command: python3 /app/platform_init.py
    environment:
      - TZ=Asia/Tokyo
      - PYTHONIOENCODING=utf-8
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - API_KEYCLOAK_HOST=keycloak
      - API_KEYCLOAK_PROTOCOL=http
      - API_KEYCLOAK_PORT=8080
      - DB_HOST=platform-db
      - DB_DATABASE=platform
      - DB_USER=app_user
      - DB_PASSWORD=password
      - DB_ADMIN_USER=root
      - DB_ADMIN_PASSWORD=password
      - ENCRYPT_KEY=${ENCRYPT_KEY}
    depends_on:
      platform-db:
        condition: service_healthy
      keycloak:
        condition: service_healthy
