version: '3.7'
services:
  ita-api-organization:
    user: 1000:1000
    build:
      dockerfile: ./ita_root/ita_api_organization/Dockerfile
      context: ../.
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - http_proxy=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - https_proxy=${HTTPS_PROXY}
    environment:
      - TZ=Asia/Tokyo
      - LISTEN_PORT=8000
      - DEFAULT_LANGUAGE=ja
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATADBASE=${DB_DATADBASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - PLATFORM_API_HOST=platform-api
      - PLATFORM_API_PORT=8000
  ita-api-admin:
    user: 1000:1000
    build:
      dockerfile: ./ita_root/ita_api_admin/Dockerfile
      context: ../.
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - http_proxy=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - https_proxy=${HTTPS_PROXY}
    environment:
      - TZ=Asia/Tokyo
      - LISTEN_PORT=8079
      - DEFAULT_LANGUAGE=ja
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATADBASE=${DB_DATADBASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - GITLAB_PROTOCOL=${GITLAB_PROTOCOL:-http}
      - GITLAB_HOST=${GITLAB_HOST}
      - GITLAB_PORT=${GITLAB_PORT}
      - GITLAB_ROOT_TOKEN=${GITLAB_ROOT_TOKEN}
  ita-web-server:
    user: 1000:1000
    build:
      dockerfile: ./ita_root/ita_web_server/Dockerfile
      context: ../.
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - http_proxy=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - https_proxy=${HTTPS_PROXY}
    environment:
      - TZ=Asia/Tokyo
      - LISTEN_PORT=80
    ports:
      - "0.0.0.0:80:80"
  ita-mariadb:
    build:
      dockerfile: ./ita_root/ita_mariadb/Dockerfile
      context: ../.
    volumes:
      - ../.volumes/ita-mariadb/data:/var/lib/mysql
    environment:
      - TZ=Asia/Tokyo
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}

  ita-by-ansible-execute:
    user: 1000:1000
    build:
      dockerfile: ./ita_root/ita_by_ansible_execute/Dockerfile
      context: ../.
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - http_proxy=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - https_proxy=${HTTPS_PROXY}
    environment:
      - TZ=Asia/Tokyo
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATADBASE=${DB_DATADBASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - HOST_STORAGEPATH=${HOST_STORAGEPATH}
      - CONTAINER_BASE=${CONTAINER_BASE}
      - GITLAB_PROTOCOL=${GITLAB_PROTOCOL:-http}
      - GITLAB_HOST=${GITLAB_HOST}
      - GITLAB_PORT=${GITLAB_PORT}
      - GITLAB_ROOT_TOKEN=${GITLAB_ROOT_TOKEN}
      - ANSIBLE_AGENT_IMAGE=${ANSIBLE_AGENT_IMAGE}
      - ANSIBLE_AGENT_IMAGE_TAG=${ANSIBLE_AGENT_IMAGE_TAG}
    # init: true
  ita-by-ansible-legacy-role-vars-listup:
    user: 1000:1000
    build:
      dockerfile: ./ita_root/ita_by_ansible_legacy_role_vars_listup/Dockerfile
      context: ../.
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - http_proxy=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - https_proxy=${HTTPS_PROXY}
    environment:
      - TZ=Asia/Tokyo
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATADBASE=${DB_DATADBASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
  ita-by-ansible-towermaster-sync:
    user: 1000:1000
    build:
      dockerfile: ./ita_root/ita_by_ansible_towermaster_sync/Dockerfile
      context: ../.
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - http_proxy=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - https_proxy=${HTTPS_PROXY}
    environment:
      - TZ=Asia/Tokyo
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATADBASE=${DB_DATADBASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
  ita-by-conductor-synchronize:
    user: 1000:1000
    build:
      dockerfile: ./ita_root/ita_by_conductor_synchronize/Dockerfile
      context: ../.
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - http_proxy=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - https_proxy=${HTTPS_PROXY}
    environment:
      - TZ=Asia/Tokyo
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATADBASE=${DB_DATADBASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
  ita-by-menu-create:
    user: 1000:1000
    build:
      dockerfile: ./ita_root/ita_by_menu_create/Dockerfile
      context: ../.
      args:
        - HTTP_PROXY=${HTTP_PROXY}
        - http_proxy=${HTTP_PROXY}
        - HTTPS_PROXY=${HTTPS_PROXY}
        - https_proxy=${HTTPS_PROXY}
    environment:
      - TZ=Asia/Tokyo
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATADBASE=${DB_DATADBASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
