DELETE FROM T_COMN_MENU WHERE MENU_GROUP_ID = "1001";
DELETE FROM T_COMN_MENU_JNL WHERE MENU_GROUP_ID = "1001";

DELETE FROM T_COMN_MENU_GROUP WHERE MENU_GROUP_ID = "1001";
DELETE FROM T_COMN_MENU_GROUP_JNL WHERE MENU_GROUP_ID = "1001";

DELETE FROM T_COMN_ROLE_MENU_LINK WHERE MENU_ID = "100101";
DELETE FROM T_COMN_ROLE_MENU_LINK_JNL WHERE MENU_ID = "100101";
DELETE FROM T_COMN_ROLE_MENU_LINK WHERE MENU_ID = "100102";
DELETE FROM T_COMN_ROLE_MENU_LINK_JNL WHERE MENU_ID = "100102";
DELETE FROM T_COMN_ROLE_MENU_LINK WHERE MENU_ID = "100103";
DELETE FROM T_COMN_ROLE_MENU_LINK_JNL WHERE MENU_ID = "100103";

DELETE FROM T_COMN_MENU_TABLE_LINK WHERE MENU_ID = "100101";
DELETE FROM T_COMN_MENU_TABLE_LINK_JNL WHERE MENU_ID = "100101";
DELETE FROM T_COMN_MENU_TABLE_LINK WHERE MENU_ID = "100102";
DELETE FROM T_COMN_MENU_TABLE_LINK_JNL WHERE MENU_ID = "100102";
DELETE FROM T_COMN_MENU_TABLE_LINK WHERE MENU_ID = "100103";
DELETE FROM T_COMN_MENU_TABLE_LINK_JNL WHERE MENU_ID = "100103";

DELETE FROM T_COMN_MENU_COLUMN_LINK WHERE MENU_ID = "100101";
DELETE FROM T_COMN_MENU_COLUMN_LINK_JNL WHERE MENU_ID = "100101";
DELETE FROM T_COMN_MENU_COLUMN_LINK WHERE MENU_ID = "100102";
DELETE FROM T_COMN_MENU_COLUMN_LINK_JNL WHERE MENU_ID = "100102";
DELETE FROM T_COMN_MENU_COLUMN_LINK WHERE MENU_ID = "100103";
DELETE FROM T_COMN_MENU_COLUMN_LINK_JNL WHERE MENU_ID = "100103";

DELETE FROM T_COMN_RECODE_LOCK_TABLE WHERE TABLE_NAME = "T_CICD_REPOSITORY_LIST";
DELETE FROM T_COMN_RECODE_LOCK_TABLE WHERE TABLE_NAME = "T_CICD_MATL_LIST";
DELETE FROM T_COMN_RECODE_LOCK_TABLE WHERE TABLE_NAME = "T_CICD_MATL_LINK";
