DROP TABLE IF EXISTS T_CICD_REPOSITORY_LIST;
DROP TABLE IF EXISTS T_CICD_REPOSITORY_LIST_JNL;
DROP TABLE IF EXISTS T_CICD_MATL_LIST;
DROP TABLE IF EXISTS T_CICD_MATL_LINK;
DROP TABLE IF EXISTS T_CICD_MATL_LINK_JNL;
DROP TABLE IF EXISTS T_CICD_GIT_PROTOCOL_TYPE;
DROP TABLE IF EXISTS T_CICD_GIT_REPOSITORY_TYPE;
DROP TABLE IF EXISTS T_CICD_REPO_SYNC_STATUS;
DROP TABLE IF EXISTS T_CICD_MATL_TYPE;
DROP TABLE IF EXISTS T_CICD_MATL_FILE_TYPE;

DROP VIEW IF EXISTS V_CICD_REPOSITORY_MATL_PATH_LINK;
DROP VIEW IF EXISTS V_CICD_MATL_TYPE;
