DROP TABLE IF EXISTS T_TERF_EXEC_STATUS;
DROP TABLE IF EXISTS T_TERF_EXEC_MODE;
DROP TABLE IF EXISTS T_TERF_TYPE_MASTER;
DROP TABLE IF EXISTS T_TERF_AUTOREG_REG_TYPE;

DROP VIEW IF EXISTS V_TERF_COLUMN_LIST;
DROP VIEW IF EXISTS V_TERF_COLUMN_LIST_JNL;
DROP VIEW IF EXISTS V_TERF_MENU;
DROP VIEW IF EXISTS V_TERF_MENU_JNL;