-- -----------------------------------------------------------------------------
-- - ▼誤字修正
-- -   locla->local
-- -----------------------------------------------------------------------------
UPDATE T_COMN_MENU_COLUMN_LINK     SET DESCRIPTION_JA = 'Ansible Automation Controller認証情報の接続タイプを設定します。通常はmachineを選択します。ansible_connectionをlocalに設定する必要があるネットワーク機器の場合にNetworkを選択します。', DESCRIPTION_EN = 'Sets the connection type for Ansible Automation Controller credentials. Basically, select machine. Select Network for network devices that require ansible_connection set to local.' WHERE COLUMN_DEFINITION_ID = '2010120';
UPDATE T_COMN_MENU_COLUMN_LINK_JNL SET DESCRIPTION_JA = 'Ansible Automation Controller認証情報の接続タイプを設定します。通常はmachineを選択します。ansible_connectionをlocalに設定する必要があるネットワーク機器の場合にNetworkを選択します。', DESCRIPTION_EN = 'Sets the connection type for Ansible Automation Controller credentials. Basically, select machine. Select Network for network devices that require ansible_connection set to local.' WHERE COLUMN_DEFINITION_ID = '2010120';

-- -----------------------------------------------------------------------------
-- - ▼Issue #2653　文字列カラムの最大長変更
-- -   8192バイト->65536バイト
-- -----------------------------------------------------------------------------
UPDATE T_COMN_MENU_COLUMN_LINK      SET VALIDATE_OPTION = '{
"min_length": 0,
"max_length": 65536
}', DESCRIPTION_JA = '[最大長]65536バイト', DESCRIPTION_EN = '[Maximum length] 65536 byte'  WHERE COLUMN_DEFINITION_ID = '2020708';
UPDATE T_COMN_MENU_COLUMN_LINK_JNL  SET VALIDATE_OPTION = '{
"min_length": 0,
"max_length": 65536
}', DESCRIPTION_JA = '[最大長]65536バイト', DESCRIPTION_EN = '[Maximum length] 65536 byte'  WHERE COLUMN_DEFINITION_ID = '2020708';
UPDATE T_COMN_MENU_COLUMN_LINK      SET VALIDATE_OPTION = '{
"min_length": 0,
"max_length": 65536
}', DESCRIPTION_JA = '[最大長]65536バイト', DESCRIPTION_EN = '[Maximum length] 65536 byte'  WHERE COLUMN_DEFINITION_ID = '2030908';
UPDATE T_COMN_MENU_COLUMN_LINK_JNL  SET VALIDATE_OPTION = '{
"min_length": 0,
"max_length": 65536
}', DESCRIPTION_JA = '[最大長]65536バイト', DESCRIPTION_EN = '[Maximum length] 65536 byte'  WHERE COLUMN_DEFINITION_ID = '2030908';
UPDATE T_COMN_MENU_COLUMN_LINK      SET VALIDATE_OPTION = '{
"min_length": 0,
"max_length": 65536
}', DESCRIPTION_JA = '[最大長]65536バイト', DESCRIPTION_EN = '[Maximum length] 65536 byte'  WHERE COLUMN_DEFINITION_ID = '2040909';
UPDATE T_COMN_MENU_COLUMN_LINK_JNL  SET VALIDATE_OPTION = '{
"min_length": 0,
"max_length": 65536
}', DESCRIPTION_JA = '[最大長]65536バイト', DESCRIPTION_EN = '[Maximum length] 65536 byte'  WHERE COLUMN_DEFINITION_ID = '2040909';


-- -----------------------------------------------------------------------------
-- - ▼Issue #2548
-- -----------------------------------------------------------------------------

-- global_variable_list
UPDATE T_COMN_MENU_TABLE_LINK SET BEFORE_VALIDATE_REGISTER = 'external_valid_menu_before', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE TABLE_DEFINITION_ID = '20104';
UPDATE T_COMN_MENU_TABLE_LINK_JNL SET BEFORE_VALIDATE_REGISTER = 'external_valid_menu_before', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE JOURNAL_SEQ_NO = '20104';

UPDATE T_COMN_MENU_COLUMN_LINK SET DESCRIPTION_JA =
'接頭文字として必ず「GBL_」を付与して下さい。
グローバル変数(センシティブ)管理含めて一意である必要があります。',
DESCRIPTION_EN =
'Make sure to assign \"GBL_\" as prefix string.
Must be unique, including global_variable_list_for_sensitiv.',
LAST_UPDATE_TIMESTAMP = _____DATE_____
WHERE COLUMN_DEFINITION_ID = '2010402';

UPDATE T_COMN_MENU_COLUMN_LINK_JNL SET DESCRIPTION_JA =
'接頭文字として必ず「GBL_」を付与して下さい。
グローバル変数(センシティブ)管理含めて一意である必要があります。',
DESCRIPTION_EN =
'Make sure to assign \"GBL_\" as prefix string.
Must be unique, including global_variable_list_for_sensitiv.',
LAST_UPDATE_TIMESTAMP = _____DATE_____
WHERE JOURNAL_SEQ_NO = '2010402';

-- global_variable_list_for_sensitiv
INSERT INTO T_COMN_MENU (MENU_ID,MENU_GROUP_ID,MENU_NAME_JA,MENU_NAME_EN,MENU_NAME_REST,DISP_SEQ,AUTOFILTER_FLG,INITIAL_FILTER_FLG,WEB_PRINT_LIMIT,WEB_PRINT_CONFIRM,XLS_PRINT_LIMIT,SORT_KEY,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('20113',201,'グローバル変数（センシティブ）管理','Global variable list (sensitiv)','global_variable_list_for_sensitiv',45,1,1,10000,1000,NULL,'[{"ASC":"global_variable_name"}]',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,MENU_ID,MENU_GROUP_ID,MENU_NAME_JA,MENU_NAME_EN,MENU_NAME_REST,DISP_SEQ,AUTOFILTER_FLG,INITIAL_FILTER_FLG,WEB_PRINT_LIMIT,WEB_PRINT_CONFIRM,XLS_PRINT_LIMIT,SORT_KEY,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('20113',_____DATE_____,'INSERT','20113',201,'グローバル変数（センシティブ）管理','Global variable list (sensitiv)','global_variable_list_for_sensitiv',45,1,1,10000,1000,NULL,'[{"ASC":"global_variable_name"}]',NULL,'0',_____DATE_____,1);

INSERT INTO T_COMN_ROLE_MENU_LINK (LINK_ID,MENU_ID,ROLE_ID,PRIVILEGE,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('20113','20113','__ROLE_ID__','1',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_ROLE_MENU_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,LINK_ID,MENU_ID,ROLE_ID,PRIVILEGE,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('20113',_____DATE_____,'INSERT','20113','20113','__ROLE_ID__','1',NULL,'0',_____DATE_____,1);

INSERT INTO T_COMN_MENU_TABLE_LINK (TABLE_DEFINITION_ID,MENU_ID,TABLE_NAME,VIEW_NAME,PK_COLUMN_NAME_REST,MENU_INFO_JA,MENU_INFO_EN,SHEET_TYPE,HISTORY_TABLE_FLAG,INHERIT,VERTICAL,HOSTGROUP,ROW_INSERT_FLAG,ROW_UPDATE_FLAG,ROW_DISUSE_FLAG,ROW_REUSE_FLAG,ROW_DELETE_FLAG,SUBSTITUTION_VALUE_LINK_FLAG,LOCK_TABLE,UNIQUE_CONSTRAINT,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('20113','20113','T_ANSC_GLOBAL_VAR_SENSITIVE',NULL,'item_no','Playbookや対話ファイルで使用するグローバル変数（センシティブ）をメンテナンス(閲覧/登録/更新/廃止)できます。','You can perform maintenance (view/register/update/discard) to global variables sensitive used in the Playbook and dialog files.','0','1','0','0','0','1','1','1','1','0','0',NULL,NULL,'external_valid_menu_before',NULL,NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_TABLE_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,TABLE_DEFINITION_ID,MENU_ID,TABLE_NAME,VIEW_NAME,PK_COLUMN_NAME_REST,MENU_INFO_JA,MENU_INFO_EN,SHEET_TYPE,HISTORY_TABLE_FLAG,INHERIT,VERTICAL,HOSTGROUP,ROW_INSERT_FLAG,ROW_UPDATE_FLAG,ROW_DISUSE_FLAG,ROW_REUSE_FLAG,ROW_DELETE_FLAG,SUBSTITUTION_VALUE_LINK_FLAG,LOCK_TABLE,UNIQUE_CONSTRAINT,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('20113',_____DATE_____,'INSERT','20113','20113','T_ANSC_GLOBAL_VAR_SENSITIVE',NULL,'item_no','Playbookや対話ファイルで使用するグローバル変数（センシティブ）をメンテナンス(閲覧/登録/更新/廃止)できます。','You can perform maintenance (view/register/update/discard) to global variables sensitive used in the Playbook and dialog files.','0','1','0','0','0','1','1','1','1','0','0',NULL,NULL,'external_valid_menu_before',NULL,NULL,'0',_____DATE_____,1);

INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2011301','20113','項番','Item No.','item_no',NULL,'1',10,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'GBL_VARS_NAME_ID',NULL,'1','1','1','1','1','1','0',NULL,NULL,NULL,NULL,NULL,'自動採番のため編集不可。実行処理種別が【登録】の場合、空白のみ可。','Cannot edit because of auto-numbering. Must be blank when execution process type is [Register].',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2011301',_____DATE_____,'INSERT','2011301','20113','項番','Item No.','item_no',NULL,'1',10,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'GBL_VARS_NAME_ID',NULL,'1','1','1','1','1','1','0',NULL,NULL,NULL,NULL,NULL,'自動採番のため編集不可。実行処理種別が【登録】の場合、空白のみ可。','Cannot edit because of auto-numbering. Must be blank when execution process type is [Register].',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2011302','20113','グローバル変数名','Global variable name','global_variable_name',NULL,'1',20,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'VARS_NAME',NULL,'0','1','1','1','1','1','0',NULL,'{
"min_length": 1,
"max_length": 255
}','^GBL_[_a-zA-Z0-9]+$',NULL,NULL,'接頭文字として必ず「GBL_」を付与して下さい。
グローバル変数管理含めて一意である必要があります。','Make sure to assign \"GBL_\" as prefix string.
Must be unique, including Global variable list.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2011302',_____DATE_____,'INSERT','2011302','20113','グローバル変数名','Global variable name','global_variable_name',NULL,'1',20,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'VARS_NAME',NULL,'0','1','1','1','1','1','0',NULL,'{
"min_length": 1,
"max_length": 255
}','^GBL_[_a-zA-Z0-9]+$',NULL,NULL,'接頭文字として必ず「GBL_」を付与して下さい。
グローバル変数管理含めて一意である必要があります。','Make sure to assign \"GBL_\" as prefix string.
Must be unique, including Global variable list.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2011303','20113','具体値','Specific value','specific_value',NULL,'34',30,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'VARS_ENTRY',NULL,'0','1','1','0','0','1','0',NULL,'{
"min_length": 0,
"max_length": 4000
}',NULL,NULL,NULL,'[最大長]4000バイト','[Maximum length] 4000 byte',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2011303',_____DATE_____,'INSERT','2011303','20113','具体値','Specific value','specific_value',NULL,'34',30,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'VARS_ENTRY',NULL,'0','1','1','0','0','1','0',NULL,'{
"min_length": 0,
"max_length": 4000
}',NULL,NULL,NULL,'[最大長]4000バイト','[Maximum length] 4000 byte',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2011304','20113','変数名説明','Variable name description','variable_name_description',NULL,'2',40,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'VARS_DESCRIPTION',NULL,'0','1','1','0','0','1','0',NULL,'{
"min_length": 0,
"max_length": 4000
}',NULL,NULL,NULL,'[最大長]4000バイト','[Maximum length] 4000 byte',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2011304',_____DATE_____,'INSERT','2011304','20113','変数名説明','Variable name description','variable_name_description',NULL,'2',40,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'VARS_DESCRIPTION',NULL,'0','1','1','0','0','1','0',NULL,'{
"min_length": 0,
"max_length": 4000
}',NULL,NULL,NULL,'[最大長]4000バイト','[Maximum length] 4000 byte',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2011305','20113','備考','Remarks','remarks',NULL,'12',50,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'NOTE',NULL,'0','1','1','0','0','1','0',NULL,'{
"min_length": 0,
"max_length": 4000
}',NULL,NULL,NULL,'自由記述欄。レコードの廃止・復活時にも記載可能。','Comments section. Can comment when removing or restoring records.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2011305',_____DATE_____,'INSERT','2011305','20113','備考','Remarks','remarks',NULL,'12',50,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'NOTE',NULL,'0','1','1','0','0','1','0',NULL,'{
"min_length": 0,
"max_length": 4000
}',NULL,NULL,NULL,'自由記述欄。レコードの廃止・復活時にも記載可能。','Comments section. Can comment when removing or restoring records.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2011306','20113','廃止フラグ','Discard','discard',NULL,'1',60,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'DISUSE_FLAG',NULL,'1','1','1','0','1','1','0',NULL,NULL,NULL,NULL,NULL,'廃止フラグ。復活以外のオペレーションは不可','Discard flag. Cannot do operation other than restore.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2011306',_____DATE_____,'INSERT','2011306','20113','廃止フラグ','Discard','discard',NULL,'1',60,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'DISUSE_FLAG',NULL,'1','1','1','0','1','1','0',NULL,NULL,NULL,NULL,NULL,'廃止フラグ。復活以外のオペレーションは不可','Discard flag. Cannot do operation other than restore.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2011307','20113','最終更新日時','Last update date/time','last_update_date_time',NULL,'13',70,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'LAST_UPDATE_TIMESTAMP',NULL,'1','0','1','0','1','1','0',NULL,NULL,NULL,NULL,NULL,'レコードの最終更新日。更新可否判定に使用。自動登録のため編集不可。','Last update date of record. Useful for judging the possibility of an update. Cannot edit because of auto-numbering.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2011307',_____DATE_____,'INSERT','2011307','20113','最終更新日時','Last update date/time','last_update_date_time',NULL,'13',70,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'LAST_UPDATE_TIMESTAMP',NULL,'1','0','1','0','1','1','0',NULL,NULL,NULL,NULL,NULL,'レコードの最終更新日。更新可否判定に使用。自動登録のため編集不可。','Last update date of record. Useful for judging the possibility of an update. Cannot edit because of auto-numbering.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2011308','20113','最終更新者','Last updated by','last_updated_user',NULL,'14',80,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'LAST_UPDATE_USER',NULL,'1','0','1','0','1','1','0',NULL,NULL,NULL,NULL,NULL,'更新者。ログインユーザのIDが自動的に登録される。編集不可。','Updated by. Login user ID is automatically registered. Cannot edit.',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2011308',_____DATE_____,'INSERT','2011308','20113','最終更新者','Last updated by','last_updated_user',NULL,'14',80,NULL,NULL,NULL,NULL,'0',NULL,NULL,NULL,NULL,'LAST_UPDATE_USER',NULL,'1','0','1','0','1','1','0',NULL,NULL,NULL,NULL,NULL,'更新者。ログインユーザのIDが自動的に登録される。編集不可。','Updated by. Login user ID is automatically registered. Cannot edit.',NULL,'0',_____DATE_____,1);

-- -----------------------------------------------------------------------------
-- - ▼Issue #2545
-- -----------------------------------------------------------------------------
INSERT INTO T_COMN_ROLE_MENU_LINK (LINK_ID,MENU_ID,ROLE_ID,PRIVILEGE,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('20208-001','20208','__ANSIBLE_EXECUTION_AGENT_ROLE_ID__','1',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_ROLE_MENU_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,LINK_ID,MENU_ID,ROLE_ID,PRIVILEGE,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('20208-001',_____DATE_____,'INSERT','20208-001','20208','__ANSIBLE_EXECUTION_AGENT_ROLE_ID__','1',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_ROLE_MENU_LINK (LINK_ID,MENU_ID,ROLE_ID,PRIVILEGE,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('20310-001','20310','__ANSIBLE_EXECUTION_AGENT_ROLE_ID__','1',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_ROLE_MENU_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,LINK_ID,MENU_ID,ROLE_ID,PRIVILEGE,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('20310-001',_____DATE_____,'INSERT','20310-001','20310','__ANSIBLE_EXECUTION_AGENT_ROLE_ID__','1',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_ROLE_MENU_LINK (LINK_ID,MENU_ID,ROLE_ID,PRIVILEGE,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('20410-001','20410','__ANSIBLE_EXECUTION_AGENT_ROLE_ID__','1',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_ROLE_MENU_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,LINK_ID,MENU_ID,ROLE_ID,PRIVILEGE,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('20410-001',_____DATE_____,'INSERT','20410-001','20410','__ANSIBLE_EXECUTION_AGENT_ROLE_ID__','1',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_ROLE_MENU_LINK (LINK_ID,MENU_ID,ROLE_ID,PRIVILEGE,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('20112-001','20112','__ANSIBLE_EXECUTION_AGENT_ROLE_ID__','1',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_ROLE_MENU_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,LINK_ID,MENU_ID,ROLE_ID,PRIVILEGE,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('20112-001',_____DATE_____,'INSERT','20112-001','20112','__ANSIBLE_EXECUTION_AGENT_ROLE_ID__','1',NULL,'0',_____DATE_____,1);