UPDATE T_COMN_MENU_COLUMN_LINK SET COLUMN_CLASS = '33', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE COLUMN_DEFINITION_ID = '3010714';
UPDATE T_COMN_MENU_COLUMN_LINK_JNL SET COLUMN_CLASS = '33', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE COLUMN_DEFINITION_ID = '3010714';

INSERT INTO T_COMN_CONDUCTOR_REGULARLY_PERIOD (REGULARLY_PERIOD_ID,REGULARLY_PERIOD_NAME_JA,REGULARLY_PERIOD_NAME_EN,DISP_SEQ,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('7','分','Minutes',70,NULL,'0',_____DATE_____,1);
