INSERT INTO T_COMN_COLUMN_CLASS (COLUMN_CLASS_ID,COLUMN_CLASS_NAME,COLUMN_CLASS_DISP_NAME_JA,COLUMN_CLASS_DISP_NAME_EN,MENU_CREATE_TARGET_FLAG,DISP_SEQ,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(33,'MultiSelectIDColumn','プルダウン複数選択','Pulldown multiple selection','0',320,NULL,'0',_____DATE_____,1);

UPDATE T_COMN_MENU_COLUMN_LINK      SET VALIDATE_OPTION = '{
"min_length": 0,
"max_length": 65536
}', DESCRIPTION_JA = '[最大長]65536バイト', DESCRIPTION_EN = '[Maximum length] 65536 byte'  WHERE COLUMN_DEFINITION_ID = '1020427';
UPDATE T_COMN_MENU_COLUMN_LINK_JNL  SET VALIDATE_OPTION = '{
"min_length": 0,
"max_length": 65536
}', DESCRIPTION_JA = '[最大長]65536バイト', DESCRIPTION_EN = '[Maximum length] 65536 byte'  WHERE COLUMN_DEFINITION_ID = '1020427';