INSERT INTO T_COMN_COLUMN_CLASS (COLUMN_CLASS_ID,COLUMN_CLASS_NAME,COLUMN_CLASS_DISP_NAME_JA,COLUMN_CLASS_DISP_NAME_EN,MENU_CREATE_TARGET_FLAG,DISP_SEQ,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(33,'MultiSelectIDColumn','プルダウン複数選択','Pulldown multiple selection','0',320,NULL,'0',_____DATE_____,1);

UPDATE T_COMN_MENU_COLUMN_LINK      SET VALIDATE_OPTION = '{
"min_length": 0,
"max_length": 65536
}', DESCRIPTION_JA = '[最大長]65536バイト', DESCRIPTION_EN = '[Maximum length] 65536 byte'  WHERE COLUMN_DEFINITION_ID = '1020427';
UPDATE T_COMN_MENU_COLUMN_LINK_JNL  SET VALIDATE_OPTION = '{
"min_length": 0,
"max_length": 65536
}', DESCRIPTION_JA = '[最大長]65536バイト', DESCRIPTION_EN = '[Maximum length] 65536 byte'  WHERE COLUMN_DEFINITION_ID = '1020427';

UPDATE T_COMN_MENU_COLUMN_LINK      SET FILE_UPLOAD_PLACE = '/uploadfiles/10202/Ansible_cfg'    WHERE COLUMN_DEFINITION_ID = '1020210';
UPDATE T_COMN_MENU_COLUMN_LINK_JNL  SET FILE_UPLOAD_PLACE = '/uploadfiles/10202/Ansible_cfg'    WHERE COLUMN_DEFINITION_ID = '1020210';

-- - ▼Issue #2548
INSERT INTO T_COMN_COLUMN_CLASS (COLUMN_CLASS_ID,COLUMN_CLASS_NAME,COLUMN_CLASS_DISP_NAME_JA,COLUMN_CLASS_DISP_NAME_EN,MENU_CREATE_TARGET_FLAG,DISP_SEQ,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(34,'MultiPasswordColumn','パスワード(複数行)','Multi password','0',340,NULL,'0',_____DATE_____,1);


UPDATE T_COMN_MENU_TABLE_LINK       SET ROW_UPDATE_FLAG = '1'       WHERE TABLE_DEFINITION_ID = '10203';
UPDATE T_COMN_MENU_TABLE_LINK_JNL   SET ROW_UPDATE_FLAG = '1'       WHERE TABLE_DEFINITION_ID = '10203';

-- 削除許可フラグ追加(デフォルトは全て削除不許可)
UPDATE T_COMN_MENU_TABLE_LINK       SET ROW_DELETE_FLAG = '0';
UPDATE T_COMN_MENU_TABLE_LINK_JNL   SET ROW_DELETE_FLAG = '0';

INSERT IGNORE INTO T_COMN_MENU_COLUMN_LINK (COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('1020326','10203','削除許可フラグ','row delete flag','row_delete_flag',NULL,'7',165,'T_COMN_BOOLEAN_FLAG','FLAG_ID','FLAG_NAME',NULL,'0',NULL,NULL,NULL,NULL,'ROW_DELETE_FLAG',NULL,'0','1','1','0','0','1','0',NULL,NULL,NULL,NULL,NULL,'プルダウン選択 必須項目
True: はい
False: いいえ','Pull-down selection  required item
True: yes
False: no',NULL,'0',_____DATE_____,1);
INSERT IGNORE INTO T_COMN_MENU_COLUMN_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COLUMN_DEFINITION_ID,MENU_ID,COLUMN_NAME_JA,COLUMN_NAME_EN,COLUMN_NAME_REST,COL_GROUP_ID,COLUMN_CLASS,COLUMN_DISP_SEQ,REF_TABLE_NAME,REF_PKEY_NAME,REF_COL_NAME,REF_SORT_CONDITIONS,REF_MULTI_LANG,REFERENCE_ITEM,SENSITIVE_COL_NAME,FILE_UPLOAD_PLACE,BUTTON_ACTION,COL_NAME,SAVE_TYPE,AUTO_INPUT,INPUT_ITEM,VIEW_ITEM,UNIQUE_ITEM,REQUIRED_ITEM,AUTOREG_HIDE_ITEM,AUTOREG_ONLY_ITEM,INITIAL_VALUE,VALIDATE_OPTION,VALIDATE_REG_EXP,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,DESCRIPTION_JA,DESCRIPTION_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(1020326,_____DATE_____,'INSERT','1020326','10203','削除許可フラグ','row delete flag','row_delete_flag',NULL,'7',165,'T_COMN_BOOLEAN_FLAG','FLAG_ID','FLAG_NAME',NULL,'0',NULL,NULL,NULL,NULL,'ROW_DELETE_FLAG',NULL,'0','1','1','0','0','1','0',NULL,NULL,NULL,NULL,NULL,'プルダウン選択 必須項目
True: はい
False: いいえ','Pull-down selection  required item
True: yes
False: no',NULL,'0',_____DATE_____,1);

-- 削除も行えるメンテナンス可＋削除可権限を追加
INSERT IGNORE INTO T_COMN_OPERATION_PRIVILEGES (PRIVILEGES_ID,PRIVILEGES_NAME_JA,PRIVILEGES_NAME_EN,NOTE,DISP_SEQ,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(0,'メンテナンス可＋削除可','Can perform maintenance and delete',NULL,0,'0',_____DATE_____,1);

-- 全角のＭを半角に直す
UPDATE T_COMN_MENU_COLUMN_LINK      SET COLUMN_NAME_JA = 'MovemenID'  WHERE COLUMN_DEFINITION_ID = '1020201';
UPDATE T_COMN_MENU_COLUMN_LINK_JNL  SET COLUMN_NAME_JA = 'MovemenID'  WHERE COLUMN_DEFINITION_ID = '1020201';
