INSERT INTO T_COMN_COLUMN_CLASS (COLUMN_CLASS_ID,COLUMN_CLASS_NAME,COLUMN_CLASS_DISP_NAME_JA,COLUMN_CLASS_DISP_NAME_EN,MENU_CREATE_TARGET_FLAG,DISP_SEQ,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(33,'MultiSelectIDColumn','プルダウン複数選択','Pulldown multiple selection','0',320,NULL,'0',_____DATE_____,1);

UPDATE T_COMN_MENU_COLUMN_LINK      SET VALIDATE_OPTION = '{
"min_length": 0,
"max_length": 65536
}', DESCRIPTION_JA = '[最大長]65536バイト', DESCRIPTION_EN = '[Maximum length] 65536 byte'  WHERE COLUMN_DEFINITION_ID = '1020427';
UPDATE T_COMN_MENU_COLUMN_LINK_JNL  SET VALIDATE_OPTION = '{
"min_length": 0,
"max_length": 65536
}', DESCRIPTION_JA = '[最大長]65536バイト', DESCRIPTION_EN = '[Maximum length] 65536 byte'  WHERE COLUMN_DEFINITION_ID = '1020427';

UPDATE T_COMN_MENU_COLUMN_LINK      SET FILE_UPLOAD_PLACE = '/uploadfiles/10202/Ansible_cfg'    WHERE COLUMN_DEFINITION_ID = '1020210';
UPDATE T_COMN_MENU_COLUMN_LINK_JNL  SET FILE_UPLOAD_PLACE = '/uploadfiles/10202/Ansible_cfg'    WHERE COLUMN_DEFINITION_ID = '1020210';

-- - ▼Issue #2548
INSERT INTO T_COMN_COLUMN_CLASS (COLUMN_CLASS_ID,COLUMN_CLASS_NAME,COLUMN_CLASS_DISP_NAME_JA,COLUMN_CLASS_DISP_NAME_EN,MENU_CREATE_TARGET_FLAG,DISP_SEQ,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(34,'MultiPasswordColumn','パスワード(複数行)','Multi password','0',340,NULL,'0',_____DATE_____,1);


UPDATE T_COMN_MENU_TABLE_LINK       SET ROW_UPDATE_FLAG = '1'       WHERE TABLE_DEFINITION_ID = '10203';
UPDATE T_COMN_MENU_TABLE_LINK_JNL   SET ROW_UPDATE_FLAG = '1'       WHERE TABLE_DEFINITION_ID = '10203';

-- 削除許可フラグ追加(デフォルトは全て削除不許可)
UPDATE T_COMN_MENU_TABLE_LINK       SET ROW_DELETE_FLAG = '0';
UPDATE T_COMN_MENU_TABLE_LINK_JNL   SET ROW_DELETE_FLAG = '0';
-- 削除も行えるメンテナンス可＋削除可権限を追加
INSERT INTO T_COMN_OPERATION_PRIVILEGES (PRIVILEGES_ID,PRIVILEGES_NAME_JA,PRIVILEGES_NAME_EN,NOTE,DISP_SEQ,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(0,'メンテナンス可＋削除可','Can perform maintenance and delete',NULL,0,'0',_____DATE_____,1);
