ALTER TABLE T_COMN_MENU_COLUMN_LINK     MODIFY  INITIAL_VALUE LONGTEXT;
ALTER TABLE T_COMN_MENU_COLUMN_LINK_JNL MODIFY  INITIAL_VALUE LONGTEXT;

-- パラメータシート定義一覧
ALTER TABLE T_COMN_MENU_TABLE_LINK ADD COLUMN ROW_DELETE_FLAG VARCHAR(2) AFTER ROW_REUSE_FLAG;
ALTER TABLE T_COMN_MENU_TABLE_LINK_JNL ADD COLUMN ROW_DELETE_FLAG VARCHAR(2) AFTER ROW_REUSE_FLAG;
