

UPDATE T_COMN_MENU_COLUMN_LINK SET COLUMN_CLASS = '33', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE COLUMN_DEFINITION_ID = '3010714';
UPDATE T_COMN_MENU_COLUMN_LINK_JNL SET COLUMN_CLASS = '33', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE COLUMN_DEFINITION_ID = '3010714';

ALTER TABLE T_COMN_MENU_COLUMN_LINK     MODIFY  INITIAL_VALUE LONGTEXT;
ALTER TABLE T_COMN_MENU_COLUMN_LINK_JNL MODIFY  INITIAL_VALUE LONGTEXT;