-- T_ANSC_DEVICE: UPDATE
-- - サーバー証明書:WINRM_SSL_CA_FILEを削除
-- - winrm公開鍵ファイル:WINRM_CERT_PEM_FILEを追加
-- - winrm秘密鍵ファイル:WINRM_CERT_KEY_PEM_FILEを追加
ALTER TABLE T_ANSC_DEVICE     ADD  COLUMN WINRM_CERT_PEM_FILE VARCHAR(255)  AFTER WINRM_PORT;
ALTER TABLE T_ANSC_DEVICE     ADD  COLUMN WINRM_CERT_KEY_PEM_FILE VARCHAR(255)  AFTER WINRM_CERT_PEM_FILE;
ALTER TABLE T_ANSC_DEVICE     DROP COLUMN WINRM_SSL_CA_FILE;
ALTER TABLE T_ANSC_DEVICE_JNL ADD  COLUMN WINRM_CERT_PEM_FILE VARCHAR(255)  AFTER WINRM_PORT;
ALTER TABLE T_ANSC_DEVICE_JNL ADD  COLUMN WINRM_CERT_KEY_PEM_FILE VARCHAR(255)  AFTER WINRM_CERT_PEM_FILE;
ALTER TABLE T_ANSC_DEVICE_JNL DROP COLUMN WINRM_SSL_CA_FILE;

-- ------------------------------------------------------------
-- - ▼ Legacy 代入値自動登録・Pioneer 代入値自動登録・Role 代入値自動登録に
-- -    MENU_NAME_REST:メニュー名(Rest)追加
-- ------------------------------------------------------------
ALTER TABLE T_ANSL_VALUE_AUTOREG     ADD  COLUMN MENU_NAME_REST VARCHAR(40)  AFTER COLUMN_ID;
ALTER TABLE T_ANSP_VALUE_AUTOREG     ADD  COLUMN MENU_NAME_REST VARCHAR(40)  AFTER COLUMN_ID;
ALTER TABLE T_ANSR_VALUE_AUTOREG     ADD  COLUMN MENU_NAME_REST VARCHAR(40)  AFTER COLUMN_ID;
ALTER TABLE T_ANSL_VALUE_AUTOREG_JNL ADD  COLUMN MENU_NAME_REST VARCHAR(40)  AFTER COLUMN_ID;
ALTER TABLE T_ANSP_VALUE_AUTOREG_JNL ADD  COLUMN MENU_NAME_REST VARCHAR(40)  AFTER COLUMN_ID;
ALTER TABLE T_ANSR_VALUE_AUTOREG_JNL ADD  COLUMN MENU_NAME_REST VARCHAR(40)  AFTER COLUMN_ID;

-- ---------------------------------------------------
-- - ▼legacy pioneer role 作業管理
-- -   ABORT_EXECUTE_FLAG: 緊急停止フラグ　追加
-- -   I_ANS_VENT_PATH: 仮想環境パス　追加
-- ---------------------------------------------------
ALTER TABLE T_ANSL_EXEC_STS_INST     ADD  ABORT_EXECUTE_FLAG    VARCHAR(2)    AFTER EXEC_MODE;
ALTER TABLE T_ANSL_EXEC_STS_INST     ADD  I_ANS_VENT_PATH       VARCHAR(255)  AFTER I_ANS_PLAYBOOK_HED_DEF;
ALTER TABLE T_ANSP_EXEC_STS_INST     ADD  ABORT_EXECUTE_FLAG    VARCHAR(2)    AFTER EXEC_MODE;
ALTER TABLE T_ANSP_EXEC_STS_INST     ADD  I_ANS_VENT_PATH       VARCHAR(255)  AFTER I_ANS_PLAYBOOK_HED_DEF;
ALTER TABLE T_ANSR_EXEC_STS_INST     ADD  ABORT_EXECUTE_FLAG    VARCHAR(2)    AFTER EXEC_MODE;
ALTER TABLE T_ANSR_EXEC_STS_INST     ADD  I_ANS_VENT_PATH       VARCHAR(255)  AFTER I_ANS_PLAYBOOK_HED_DEF;
ALTER TABLE T_ANSL_EXEC_STS_INST_JNL ADD  ABORT_EXECUTE_FLAG    VARCHAR(2)    AFTER EXEC_MODE;
ALTER TABLE T_ANSL_EXEC_STS_INST_JNL ADD  I_ANS_VENT_PATH       VARCHAR(255)  AFTER I_ANS_PLAYBOOK_HED_DEF;
ALTER TABLE T_ANSP_EXEC_STS_INST_JNL ADD  ABORT_EXECUTE_FLAG    VARCHAR(2)    AFTER EXEC_MODE;
ALTER TABLE T_ANSP_EXEC_STS_INST_JNL ADD  I_ANS_VENT_PATH       VARCHAR(255)  AFTER I_ANS_PLAYBOOK_HED_DEF;
ALTER TABLE T_ANSR_EXEC_STS_INST_JNL ADD  ABORT_EXECUTE_FLAG    VARCHAR(2)    AFTER EXEC_MODE;
ALTER TABLE T_ANSR_EXEC_STS_INST_JNL ADD  I_ANS_VENT_PATH       VARCHAR(255)  AFTER I_ANS_PLAYBOOK_HED_DEF;

-- ----------------------------------------------------
-- - ▼Legacy Movemnet一覧
-- -   ANS_VENV_PATH:　仮想環境パス追加
-- ---------------------------------------------------
CREATE OR REPLACE VIEW V_ANSL_MOVEMENT AS
SELECT
MOVEMENT_ID,
MOVEMENT_NAME,
ITA_EXT_STM_ID,
TIME_LIMIT,
ANS_HOST_DESIGNATE_TYPE_ID,
ANS_PARALLEL_EXE,
ANS_WINRM_ID,
ANS_PLAYBOOK_HED_DEF,
ANS_EXEC_OPTIONS,
ANS_VENV_PATH,
ANS_EXECUTION_ENVIRONMENT_NAME,
ANS_ANSIBLE_CONFIG_FILE,
NOTE,
DISUSE_FLAG,
LAST_UPDATE_TIMESTAMP,
LAST_UPDATE_USER
FROM
  T_COMN_MOVEMENT
WHERE
  ITA_EXT_STM_ID = 1;

CREATE OR REPLACE VIEW V_ANSL_MOVEMENT_JNL AS
SELECT
JOURNAL_SEQ_NO,
JOURNAL_REG_DATETIME,
JOURNAL_ACTION_CLASS,
MOVEMENT_ID,
MOVEMENT_NAME,
ITA_EXT_STM_ID,
TIME_LIMIT,
ANS_HOST_DESIGNATE_TYPE_ID,
ANS_PARALLEL_EXE,
ANS_WINRM_ID,
ANS_PLAYBOOK_HED_DEF,
ANS_EXEC_OPTIONS,
ANS_VENV_PATH,
ANS_EXECUTION_ENVIRONMENT_NAME,
ANS_ANSIBLE_CONFIG_FILE,
NOTE,
DISUSE_FLAG,
LAST_UPDATE_TIMESTAMP,
LAST_UPDATE_USER
FROM
  T_COMN_MOVEMENT_JNL
WHERE
  ITA_EXT_STM_ID = 1;


-- ---------------------------------------------------
-- - ▼Pionner Movemnet一覧
-- -   ANS_VENV_PATH:　仮想環境パス追加
-- ---------------------------------------------------
CREATE OR REPLACE VIEW V_ANSP_MOVEMENT AS
SELECT
MOVEMENT_ID,
MOVEMENT_NAME,
ITA_EXT_STM_ID,
TIME_LIMIT,
ANS_HOST_DESIGNATE_TYPE_ID,
ANS_PARALLEL_EXE,
ANS_WINRM_ID,
ANS_PLAYBOOK_HED_DEF,
ANS_EXEC_OPTIONS,
ANS_VENV_PATH,
ANS_EXECUTION_ENVIRONMENT_NAME,
ANS_ANSIBLE_CONFIG_FILE,
NOTE,
DISUSE_FLAG,
LAST_UPDATE_TIMESTAMP,
LAST_UPDATE_USER
FROM
  T_COMN_MOVEMENT
WHERE
  ITA_EXT_STM_ID = 2;

CREATE OR REPLACE VIEW V_ANSP_MOVEMENT_JNL AS
SELECT
JOURNAL_SEQ_NO,
JOURNAL_REG_DATETIME,
JOURNAL_ACTION_CLASS,
MOVEMENT_ID,
MOVEMENT_NAME,
ITA_EXT_STM_ID,
TIME_LIMIT,
ANS_HOST_DESIGNATE_TYPE_ID,
ANS_PARALLEL_EXE,
ANS_WINRM_ID,
ANS_PLAYBOOK_HED_DEF,
ANS_EXEC_OPTIONS,
ANS_VENV_PATH,
ANS_EXECUTION_ENVIRONMENT_NAME,
ANS_ANSIBLE_CONFIG_FILE,
NOTE,
DISUSE_FLAG,
LAST_UPDATE_TIMESTAMP,
LAST_UPDATE_USER
FROM
  T_COMN_MOVEMENT_JNL
WHERE
  ITA_EXT_STM_ID = 2;

-- ---------------------------------------------------
-- - ▼Role Movemnet一覧
-- -   ANS_VENV_PATH:　仮想環境パス追加
-- ---------------------------------------------------
CREATE OR REPLACE VIEW V_ANSR_MOVEMENT AS
SELECT
MOVEMENT_ID,
MOVEMENT_NAME,
ITA_EXT_STM_ID,
TIME_LIMIT,
ANS_HOST_DESIGNATE_TYPE_ID,
ANS_PARALLEL_EXE,
ANS_WINRM_ID,
ANS_PLAYBOOK_HED_DEF,
ANS_EXEC_OPTIONS,
ANS_VENV_PATH,
ANS_EXECUTION_ENVIRONMENT_NAME,
ANS_ANSIBLE_CONFIG_FILE,
NOTE,
DISUSE_FLAG,
LAST_UPDATE_TIMESTAMP,
LAST_UPDATE_USER
FROM
  T_COMN_MOVEMENT
WHERE
  ITA_EXT_STM_ID = 3;

CREATE OR REPLACE VIEW V_ANSR_MOVEMENT_JNL AS
SELECT
JOURNAL_SEQ_NO,
JOURNAL_REG_DATETIME,
JOURNAL_ACTION_CLASS,
MOVEMENT_ID,
MOVEMENT_NAME,
ITA_EXT_STM_ID,
TIME_LIMIT,
ANS_HOST_DESIGNATE_TYPE_ID,
ANS_PARALLEL_EXE,
ANS_WINRM_ID,
ANS_PLAYBOOK_HED_DEF,
ANS_EXEC_OPTIONS,
ANS_VENV_PATH,
ANS_EXECUTION_ENVIRONMENT_NAME,
ANS_ANSIBLE_CONFIG_FILE,
NOTE,
DISUSE_FLAG,
LAST_UPDATE_TIMESTAMP,
LAST_UPDATE_USER
FROM
  T_COMN_MOVEMENT_JNL
WHERE
  ITA_EXT_STM_ID = 3;

