-- T_ANSC_DEVICE: UPDATE
-- - サーバー証明書:WINRM_SSL_CA_FILEを削除
-- - winrm公開鍵ファイル:WINRM_CERT_PEM_FILEを追加
-- - winrm秘密鍵ファイル:WINRM_CERT_KEY_PEM_FILEを追加
ALTER TABLE T_ANSC_DEVICE     ADD  COLUMN WINRM_CERT_PEM_FILE VARCHAR(255)  AFTER WINRM_PORT;
ALTER TABLE T_ANSC_DEVICE     ADD  COLUMN WINRM_CERT_KEY_PEM_FILE VARCHAR(255)  AFTER WINRM_CERT_PEM_FILE;
ALTER TABLE T_ANSC_DEVICE     DROP COLUMN WINRM_SSL_CA_FILE;
ALTER TABLE T_ANSC_DEVICE_JNL ADD  COLUMN WINRM_CERT_PEM_FILE VARCHAR(255)  AFTER WINRM_PORT;
ALTER TABLE T_ANSC_DEVICE_JNL ADD  COLUMN WINRM_CERT_KEY_PEM_FILE VARCHAR(255)  AFTER WINRM_CERT_PEM_FILE;
ALTER TABLE T_ANSC_DEVICE_JNL DROP COLUMN WINRM_SSL_CA_FILE;
