-- INSERT/UPDATE: -2.5.0
    -- T_COMN_MENU_COLUMN_LINK: UPDATE

-- T_COMN_MENU_COLUMN_LINK: UPDATE
UPDATE T_COMN_MENU_COLUMN_LINK SET DESCRIPTION_JA = '[元データ]Conductor作業履歴', DESCRIPTION_EN = '[Original data]Conductor history', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE COLUMN_DEFINITION_ID = '11011007';
UPDATE T_COMN_MENU_COLUMN_LINK_JNL SET DESCRIPTION_JA = '[元データ]Conductor作業履歴', DESCRIPTION_EN = '[Original data]Conductor history', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE COLUMN_DEFINITION_ID = '11011007';

UPDATE T_COMN_MENU_COLUMN_LINK SET DESCRIPTION_JA = '[元データ]Conductor作業履歴', DESCRIPTION_EN = '[Original data]Conductor history', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE COLUMN_DEFINITION_ID = '11011009';
UPDATE T_COMN_MENU_COLUMN_LINK_JNL SET DESCRIPTION_JA = '[元データ]Conductor作業履歴', DESCRIPTION_EN = '[Original data]Conductor history', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE COLUMN_DEFINITION_ID = '11011009';