-- ------------------------------------------------------------
-- - ▼ Movement一覧
-- -    AG_EXECUTION_ENVIRONMENT_NAME  実行環境                    追加
-- -    AG_BUILDER_OPTIONS             ansible-builder パラメータ  追加

-- ------------------------------------------------------------
ALTER TABLE T_COMN_MOVEMENT     ADD COLUMN AG_BUILDER_OPTIONS             TEXT         AFTER ANS_EXEC_OPTIONS;
ALTER TABLE T_COMN_MOVEMENT     ADD COLUMN AG_EXECUTION_ENVIRONMENT_NAME  VARCHAR(255) AFTER ANS_EXEC_OPTIONS;
ALTER TABLE T_COMN_MOVEMENT_JNL ADD COLUMN AG_BUILDER_OPTIONS             TEXT         AFTER ANS_EXEC_OPTIONS;
ALTER TABLE T_COMN_MOVEMENT_JNL ADD COLUMN AG_EXECUTION_ENVIRONMENT_NAME  VARCHAR(255) AFTER ANS_EXEC_OPTIONS;
