ALTER TABLE T_ANSL_MATL_COLL ADD COLUMN TARGET_LINUX VARCHAR(40) AFTER PLAYBOOK_MATTER_FILE;
ALTER TABLE T_ANSL_MATL_COLL ADD COLUMN TARGET_WINDOWS VARCHAR(40) AFTER TARGET_LINUX;
ALTER TABLE T_ANSL_MATL_COLL ADD COLUMN TARGET_OTHER TEXT AFTER TARGET_WINDOWS;
ALTER TABLE T_ANSL_MATL_COLL ADD COLUMN PYTHON_NECESSARY VARCHAR(40) AFTER TARGET_OTHER;
ALTER TABLE T_ANSL_MATL_COLL ADD COLUMN DESCRIPTION TEXT AFTER PYTHON_NECESSARY;
ALTER TABLE T_ANSL_MATL_COLL ADD COLUMN DESCRIPTION_EN TEXT AFTER DESCRIPTION;

ALTER TABLE T_ANSL_MATL_COLL_JNL ADD COLUMN TARGET_LINUX VARCHAR(40) AFTER PLAYBOOK_MATTER_FILE;
ALTER TABLE T_ANSL_MATL_COLL_JNL ADD COLUMN TARGET_WINDOWS VARCHAR(40) AFTER TARGET_LINUX;
ALTER TABLE T_ANSL_MATL_COLL_JNL ADD COLUMN TARGET_OTHER TEXT AFTER TARGET_WINDOWS;
ALTER TABLE T_ANSL_MATL_COLL_JNL ADD COLUMN PYTHON_NECESSARY VARCHAR(40) AFTER TARGET_OTHER;
ALTER TABLE T_ANSL_MATL_COLL_JNL ADD COLUMN DESCRIPTION TEXT AFTER PYTHON_NECESSARY;
ALTER TABLE T_ANSL_MATL_COLL_JNL ADD COLUMN DESCRIPTION_EN TEXT AFTER DESCRIPTION;

ALTER TABLE T_ANSP_MATL_COLL ADD COLUMN TARGET_LINUX VARCHAR(40) AFTER DIALOG_MATTER_FILE;
ALTER TABLE T_ANSP_MATL_COLL ADD COLUMN TARGET_WINDOWS VARCHAR(40) AFTER TARGET_LINUX;
ALTER TABLE T_ANSP_MATL_COLL ADD COLUMN TARGET_OTHER TEXT AFTER TARGET_WINDOWS;
ALTER TABLE T_ANSP_MATL_COLL ADD COLUMN PYTHON_NECESSARY VARCHAR(40) AFTER TARGET_OTHER;
ALTER TABLE T_ANSP_MATL_COLL ADD COLUMN DESCRIPTION TEXT AFTER PYTHON_NECESSARY;
ALTER TABLE T_ANSP_MATL_COLL ADD COLUMN DESCRIPTION_EN TEXT AFTER DESCRIPTION;

ALTER TABLE T_ANSP_MATL_COLL_JNL ADD COLUMN TARGET_LINUX VARCHAR(40) AFTER DIALOG_MATTER_FILE;
ALTER TABLE T_ANSP_MATL_COLL_JNL ADD COLUMN TARGET_WINDOWS VARCHAR(40) AFTER TARGET_LINUX;
ALTER TABLE T_ANSP_MATL_COLL_JNL ADD COLUMN TARGET_OTHER TEXT AFTER TARGET_WINDOWS;
ALTER TABLE T_ANSP_MATL_COLL_JNL ADD COLUMN PYTHON_NECESSARY VARCHAR(40) AFTER TARGET_OTHER;
ALTER TABLE T_ANSP_MATL_COLL_JNL ADD COLUMN DESCRIPTION TEXT AFTER PYTHON_NECESSARY;
ALTER TABLE T_ANSP_MATL_COLL_JNL ADD COLUMN DESCRIPTION_EN TEXT AFTER DESCRIPTION;

ALTER TABLE T_ANSR_MATL_COLL ADD COLUMN TARGET_LINUX VARCHAR(40) AFTER ROLE_PACKAGE_FILE;
ALTER TABLE T_ANSR_MATL_COLL ADD COLUMN TARGET_WINDOWS VARCHAR(40) AFTER TARGET_LINUX;
ALTER TABLE T_ANSR_MATL_COLL ADD COLUMN TARGET_OTHER TEXT AFTER TARGET_WINDOWS;
ALTER TABLE T_ANSR_MATL_COLL ADD COLUMN PYTHON_NECESSARY VARCHAR(40) AFTER TARGET_OTHER;
ALTER TABLE T_ANSR_MATL_COLL ADD COLUMN DESCRIPTION TEXT AFTER PYTHON_NECESSARY;
ALTER TABLE T_ANSR_MATL_COLL ADD COLUMN DESCRIPTION_EN TEXT AFTER DESCRIPTION;

ALTER TABLE T_ANSR_MATL_COLL_JNL ADD COLUMN TARGET_LINUX VARCHAR(40) AFTER ROLE_PACKAGE_FILE;
ALTER TABLE T_ANSR_MATL_COLL_JNL ADD COLUMN TARGET_WINDOWS VARCHAR(40) AFTER TARGET_LINUX;
ALTER TABLE T_ANSR_MATL_COLL_JNL ADD COLUMN TARGET_OTHER TEXT AFTER TARGET_WINDOWS;
ALTER TABLE T_ANSR_MATL_COLL_JNL ADD COLUMN PYTHON_NECESSARY VARCHAR(40) AFTER TARGET_OTHER;
ALTER TABLE T_ANSR_MATL_COLL_JNL ADD COLUMN DESCRIPTION TEXT AFTER PYTHON_NECESSARY;
ALTER TABLE T_ANSR_MATL_COLL_JNL ADD COLUMN DESCRIPTION_EN TEXT AFTER DESCRIPTION;
