UPDATE T_COMN_CONDUCTOR_IF_INFO     SET CONDUCTOR_REFRESH_INTERVAL=1000 WHERE CONDUCTOR_IF_INFO_ID='1' AND CONDUCTOR_REFRESH_INTERVAL=3000;
UPDATE T_COMN_CONDUCTOR_IF_INFO_JNL SET CONDUCTOR_REFRESH_INTERVAL=1000 WHERE CONDUCTOR_IF_INFO_ID='1' AND CONDUCTOR_REFRESH_INTERVAL=3000;
