-- メニューエクスポート・インポート管理
ALTER TABLE `T_MENU_EXPORT_IMPORT` ADD `LANGUAGE` VARCHAR(40) NOT NULL AFTER `EXECUTION_USER`;
ALTER TABLE `T_MENU_EXPORT_IMPORT_JNL` ADD `LANGUAGE` VARCHAR(40) NOT NULL AFTER `EXECUTION_USER`;
ALTER TABLE `T_MENU_EXPORT_IMPORT` ADD `EXEC_LOG` TEXT NOT NULL AFTER `LANGUAGE`;
ALTER TABLE `T_MENU_EXPORT_IMPORT_JNL` ADD `EXEC_LOG` TEXT NOT NULL AFTER `LANGUAGE`;
ALTER TABLE `T_MENU_EXPORT_IMPORT` MODIFY `FILE_NAME` VARCHAR(255);
ALTER TABLE `T_MENU_EXPORT_IMPORT_JNL` MODIFY `FILE_NAME` VARCHAR(255);