-- INSERT/UPDATE: -2.4.0
    -- T_COMN_BACKYARD_USER : UPDATE

-- T_COMN_BACKYARD_USER: UPDATE
UPDATE T_COMN_BACKYARD_USER SET USER_NAME_JA = 'OASE評価機能', USER_NAME_EN = 'OASE Evaluation function', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE USER_ID = '110102';
