-- INSERT/UPDATE: -2.4.0
    -- T_COMN_BACKYARD_USER : UPDATE

-- T_COMN_BACKYARD_USER: UPDATE
UPDATE T_COMN_BACKYARD_USER SET USER_NAME_JA = 'OASE評価機能', USER_NAME_EN = 'OASE Evaluation function', LAST_UPDATE_TIMESTAMP = _____DATE_____ WHERE USER_ID = '110102';

-- T_COMN_COLUMN_GROUP: INSERT
INSERT INTO T_COMN_COLUMN_GROUP (COL_GROUP_ID,PA_COL_GROUP_ID,COL_GROUP_NAME_JA,COL_GROUP_NAME_EN,FULL_COL_GROUP_NAME_JA,FULL_COL_GROUP_NAME_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('2020201',NULL,'ターゲット','Target','ターゲット','Target',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_COLUMN_GROUP_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,COL_GROUP_ID,PA_COL_GROUP_ID,COL_GROUP_NAME_JA,COL_GROUP_NAME_EN,FULL_COL_GROUP_NAME_JA,FULL_COL_GROUP_NAME_EN,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(2020201,_____DATE_____,'INSERT','2020201',NULL,'ターゲット','Target','ターゲット','Target',NULL,'0',_____DATE_____,1);

