-- IN ITA_ORG_xxxx-xxxx-xxxx-xxxx

CREATE TABLE IF NOT EXISTS DUMMY_TABLE
(
  DUMMY_ID INT,
  DUMMY_NAME VARCHAR(255),
  PRIMARY KEY (DUMMY_ID)
)

INSERT INTO DUMMY_TABLE (DUMMY_ID, DUMMY_NAME) VALUES (1, '名前')
