-- INSERT/UPDATE: -2.2.0
    -- T_COMN_RECODE_LOCK_TABLE: INSERT
    -- T_COMN_MENU_GROUP: INSERT
    -- T_COMN_MENU: INSERT
    -- T_COMN_ROLE_MENU_LINK: INSERT
    -- T_COMN_MENU_TABLE_LINK: INSERT

-- T_COMN_RECODE_LOCK_TABLE: INSERT
INSERT INTO T_COMN_RECODE_LOCK_TABLE (TABLE_NAME) VALUES('T_MENU_DEFINE');
INSERT INTO T_COMN_RECODE_LOCK_TABLE (TABLE_NAME) VALUES('T_MENU_COLUMN');
INSERT INTO T_COMN_RECODE_LOCK_TABLE (TABLE_NAME) VALUES('T_MENU_COLUMN_GROUP');
INSERT INTO T_COMN_RECODE_LOCK_TABLE (TABLE_NAME) VALUES('T_MENU_UNIQUE_CONSTRAINT');
INSERT INTO T_COMN_RECODE_LOCK_TABLE (TABLE_NAME) VALUES('T_MENU_ROLE');
INSERT INTO T_COMN_RECODE_LOCK_TABLE (TABLE_NAME) VALUES('T_MENU_OTHER_LINK');
INSERT INTO T_COMN_RECODE_LOCK_TABLE (TABLE_NAME) VALUES('T_MENU_REFERENCE_ITEM');

-- T_COMN_MENU_GROUP: INSERT
INSERT INTO T_COMN_MENU_GROUP (MENU_GROUP_ID,PARENT_MENU_GROUP_ID,MENU_GROUP_NAME_JA,MENU_GROUP_NAME_EN,MENU_GROUP_ICON,MENU_CREATE_TARGET_FLAG,DISP_SEQ,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(505,NULL,'パラメータ集','Parameter collection','parameter-collection.png','0',35,NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_GROUP_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,MENU_GROUP_ID,PARENT_MENU_GROUP_ID,MENU_GROUP_NAME_JA,MENU_GROUP_NAME_EN,MENU_GROUP_ICON,MENU_CREATE_TARGET_FLAG,DISP_SEQ,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(505,_____DATE_____,'INSERT',505,NULL,'パラメータ集','Parameter collection','parameter-collection.png','0',35,NULL,'0',_____DATE_____,1);

-- T_COMN_MENU: INSERT
INSERT INTO T_COMN_MENU (MENU_ID,MENU_GROUP_ID,MENU_NAME_JA,MENU_NAME_EN,MENU_NAME_REST,DISP_SEQ,AUTOFILTER_FLG,INITIAL_FILTER_FLG,WEB_PRINT_LIMIT,WEB_PRINT_CONFIRM,XLS_PRINT_LIMIT,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(50501,505,'パラメータ集','Parameter collection','parameter_collection',10,1,0,NULL,NULL,NULL,NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,MENU_ID,MENU_GROUP_ID,MENU_NAME_JA,MENU_NAME_EN,MENU_NAME_REST,DISP_SEQ,AUTOFILTER_FLG,INITIAL_FILTER_FLG,WEB_PRINT_LIMIT,WEB_PRINT_CONFIRM,XLS_PRINT_LIMIT,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(50501,_____DATE_____,'INSERT',50501,505,'パラメータ集','Parameter collection','parameter_collection',10,1,0,NULL,NULL,NULL,NULL,'0',_____DATE_____,1);

-- T_COMN_ROLE_MENU_LINK: INSERT
INSERT INTO T_COMN_ROLE_MENU_LINK (LINK_ID,MENU_ID,ROLE_ID,PRIVILEGE,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('50501','50501','__ROLE_ID__','1',NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_ROLE_MENU_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,LINK_ID,MENU_ID,ROLE_ID,PRIVILEGE,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(50501,_____DATE_____,'INSERT','50501','50501','__ROLE_ID__','1',NULL,'0',_____DATE_____,1);

-- T_COMN_MENU_TABLE_LINK: INSERT
INSERT INTO T_COMN_MENU_TABLE_LINK (TABLE_DEFINITION_ID,MENU_ID,TABLE_NAME,VIEW_NAME,PK_COLUMN_NAME_REST,MENU_INFO_JA,MENU_INFO_EN,SHEET_TYPE,HISTORY_TABLE_FLAG,INHERIT,VERTICAL,HOSTGROUP,ROW_INSERT_FLAG,ROW_UPDATE_FLAG,ROW_DISUSE_FLAG,ROW_REUSE_FLAG,SUBSTITUTION_VALUE_LINK_FLAG,LOCK_TABLE,UNIQUE_CONSTRAINT,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES('50501','50501',NULL,NULL,'uuid','登録されているパラメータシートに対して検索、メンテナンス(参照/更新/廃止/復活)できます。','Search and Maintenance (view/register/update/discard) can be performed on registered parameter sheets.','25','0','0','0','0','0','0','0','0','0',NULL,NULL,NULL,NULL,NULL,'0',_____DATE_____,1);
INSERT INTO T_COMN_MENU_TABLE_LINK_JNL (JOURNAL_SEQ_NO,JOURNAL_REG_DATETIME,JOURNAL_ACTION_CLASS,TABLE_DEFINITION_ID,MENU_ID,TABLE_NAME,VIEW_NAME,PK_COLUMN_NAME_REST,MENU_INFO_JA,MENU_INFO_EN,SHEET_TYPE,HISTORY_TABLE_FLAG,INHERIT,VERTICAL,HOSTGROUP,ROW_INSERT_FLAG,ROW_UPDATE_FLAG,ROW_DISUSE_FLAG,ROW_REUSE_FLAG,SUBSTITUTION_VALUE_LINK_FLAG,LOCK_TABLE,UNIQUE_CONSTRAINT,BEFORE_VALIDATE_REGISTER,AFTER_VALIDATE_REGISTER,NOTE,DISUSE_FLAG,LAST_UPDATE_TIMESTAMP,LAST_UPDATE_USER) VALUES(50501,_____DATE_____,'INSERT','50501','50501',NULL,NULL,'uuid','登録されているパラメータシートに対して検索、メンテナンス(参照/更新/廃止/復活)できます。','Search and Maintenance (view/register/update/discard) can be performed on registered parameter sheets.','25','0','0','0','0','0','0','0','0','0',NULL,NULL,NULL,NULL,NULL,'0',_____DATE_____,1);
