-- INSERT/UPDATE: -2.2.0
    -- T_COMN_RECODE_LOCK_TABLE: INSERT

-- T_COMN_RECODE_LOCK_TABLE: INSERT
INSERT INTO T_COMN_RECODE_LOCK_TABLE (TABLE_NAME) VALUES('T_MENU_DEFINE');
INSERT INTO T_COMN_RECODE_LOCK_TABLE (TABLE_NAME) VALUES('T_MENU_COLUMN');
INSERT INTO T_COMN_RECODE_LOCK_TABLE (TABLE_NAME) VALUES('T_MENU_COLUMN_GROUP');
INSERT INTO T_COMN_RECODE_LOCK_TABLE (TABLE_NAME) VALUES('T_MENU_UNIQUE_CONSTRAINT');
INSERT INTO T_COMN_RECODE_LOCK_TABLE (TABLE_NAME) VALUES('T_MENU_ROLE');
INSERT INTO T_COMN_RECODE_LOCK_TABLE (TABLE_NAME) VALUES('T_MENU_OTHER_LINK');
INSERT INTO T_COMN_RECODE_LOCK_TABLE (TABLE_NAME) VALUES('T_MENU_REFERENCE_ITEM');

