ALTER TABLE `T_CICD_REPOSITORY_LIST` MODIFY COLUMN `REMORT_REPO_URL` VARCHAR(4096);
ALTER TABLE `T_CICD_REPOSITORY_LIST` MODIFY COLUMN `PROXY_ADDRESS` VARCHAR(4096);
ALTER TABLE `T_CICD_REPOSITORY_LIST_JNL` MODIFY COLUMN `REMORT_REPO_URL` VARCHAR(4096);
ALTER TABLE `T_CICD_REPOSITORY_LIST_JNL` MODIFY COLUMN `PROXY_ADDRESS` VARCHAR(4096);
