ALTER TABLE `T_COMN_CONDUCTOR_NOTICE` MODIFY COLUMN `NOTICE_URL` VARCHAR(4096);
ALTER TABLE `T_COMN_CONDUCTOR_NOTICE` MODIFY COLUMN `HEADER` TEXT;
ALTER TABLE `T_COMN_CONDUCTOR_NOTICE` MODIFY COLUMN `PROXY_URL` VARCHAR(4096);
ALTER TABLE `T_COMN_CONDUCTOR_NOTICE` MODIFY COLUMN `FQDN` VARCHAR(4096);
ALTER TABLE `T_COMN_CONDUCTOR_NOTICE_JNL` MODIFY COLUMN `NOTICE_URL` VARCHAR(4096);
ALTER TABLE `T_COMN_CONDUCTOR_NOTICE_JNL` MODIFY COLUMN `HEADER` TEXT;
ALTER TABLE `T_COMN_CONDUCTOR_NOTICE_JNL` MODIFY COLUMN `PROXY_URL` VARCHAR(4096);
ALTER TABLE `T_COMN_CONDUCTOR_NOTICE_JNL` MODIFY COLUMN `FQDN` VARCHAR(4096);
