ALTER TABLE `T_OASE_EVENT_COLLECTION_SETTINGS` MODIFY COLUMN `URL` VARCHAR(4096);
ALTER TABLE `T_OASE_EVENT_COLLECTION_SETTINGS` MODIFY COLUMN `PROXY` VARCHAR(4096);
ALTER TABLE `T_OASE_EVENT_COLLECTION_SETTINGS` MODIFY COLUMN `AUTH_TOKEN` VARCHAR(4096);
ALTER TABLE `T_OASE_EVENT_COLLECTION_SETTINGS_JNL` MODIFY COLUMN `URL` VARCHAR(4096);
ALTER TABLE `T_OASE_EVENT_COLLECTION_SETTINGS_JNL` MODIFY COLUMN `PROXY` VARCHAR(4096);
ALTER TABLE `T_OASE_EVENT_COLLECTION_SETTINGS_JNL` MODIFY COLUMN `AUTH_TOKEN` VARCHAR(4096);
